Description of XeX
XeX
PURPOSE
XEX M-file for XeX.fig
SYNOPSIS
function varargout = XeX(varargin)
DESCRIPTION
 XEX M-file for XeX.fig
      XEX, by itself, creates a new XEX or raises the existing
      singleton*.
      H = XEX returns the handle to a new XEX or the handle to
      the existing singleton*.
      XEX('CALLBACK',hObject,eventData,handles,...) calls the local
      function named CALLBACK in XEX.M with the given input arguments.
      XEX('Property','Value',...) creates a new XEX or raises the
      existing singleton*.  Starting from the left, property value pairs
      are
      applied to the GUI before XeX_OpeningFunction gets called.  An
      unrecognized property name or invalid value makes property
      application
      stop.  All inputs are passed to XeX_OpeningFcn via varargin.
      *See GUI Options on GUIDE's Tools menu.  Choose "GUI allows only one
      instance to run (singleton)".
 See also: GUIDE, GUIDATA, GUIHANDLES
CROSS-REFERENCE INFORMATION
This function calls:
MakeHist Script to produce an histogram. Uses PlotHist to do the hard work
mrdr mrdr: MATLAB REX data reader.
FilterManagerGUI FILTERMANAGERGUI M-file for FilterManagerGUI.fig
TrialViewer TRIALVIEWER M-file for TrialViewer.fig
LayOutEditWindow takes care of edit window positioning
gset sets the gain graph layout
nineset
twelveset
endR Closes the R connection in RPROCESSHANDLE
ParamEval This function works in PlotData and in Graphcommandprocessor and serves to
TellMe This function uses tts to speak out the stringvar if speaktovar is set, else fprintfs it to cmd window
XeXUtters Legacy function (too slow) to speak out instead of printing to screen, if SpeakToMe is set
clearvars This function clears all the variables that were recently detached
detachvars This script detaches all the variables from a structure and assigns them
ftpsurf This scriptlet calls FTPSurfer from within Matlab
un This function takes in a vector (or a matrix) , and returns unique values (or rows). NaNs (and rows with NaNs) are removed.
AnalLoadedFileScript
FInterpreter This script does the filter interpretation; will grow
GraphCommandProcessor Basically does what Plot data does, but reads in commands from a gfx
SetBaseRate
SetVariablesScript
getCurrentParameters This script collects parameters from the GUI.
ClearGObjects This script is used to remove graphix objects properties when clear axes is called
DoUseProps This function makes the UseProps graphics objects visible or invisible based on handles.UseProps
ExportGFX Script that handles graph exporting in XeX
LinkHandle This is the buttondownfunction for the axis. Work on it !!
SwitchAxes This script switches axes based on axis list in GUI
UndefineAxisVars
UnlinkTheseAxes
WhatToDoStuff This function get the handles.WhatToDo string and then decides on what to show and not show in GUI
makeInvisible To make objects supplied invisible
makeVisible To make objects supplied visible
FTPLoadFileStuff This script handles file-loadign after FTP
FTPScript
LoadFileCallbackStuff This file handles file loading, from GUI.
UpdateAxis This script updates current axis with current properties
UpdateCellOrLoadGFX this script does all the hard work for updating a cell or loading
UpdateGObjects this script does the hard work for updateaxis
UpdateMarkers This script is what gets done for the markers callback
UpdateSlider this is the major update graphic objects file. poorly called
XeX XEX M-file for XeX.fig
This function is called by:
FilterManagerGUI FILTERMANAGERGUI M-file for FilterManagerGUI.fig
ftpsurf This scriptlet calls FTPSurfer from within Matlab
ParseStimString This script is used by getcurrentparameters.m among other scripts, to
ParseXCenters This script is used by getcurrentparameters.m among other scripts, to
XeX XEX M-file for XeX.fig
SUBFUNCTIONS
function XeX_OpeningFcn(hObject, eventdata, handles, varargin)
function varargout = XeX_OutputFcn(hObject, eventdata, handles)
function Options_Callback(hObject, eventdata, handles)
function SacOpts_Callback(hObject, eventdata, handles)
function LoadedFiles_Callback(hObject, eventdata, handles)
function LoadedFiles_CreateFcn(hObject, eventdata, handles)
function AnalysisFile_Callback(hObject, eventdata, handles)
function AnalysisFile_CreateFcn(hObject, eventdata, handles)
function AnalyzeFile_Callback(hObject, eventdata, handles)
function HoldStatus_Callback(hObject, eventdata, handles)
function PlotData_Callback(hObject, eventdata, handles)
function CodeBitMenu_Callback(hObject, eventdata, handles)
function CodeBitMenu_CreateFcn(hObject, eventdata, handles)
function LoadFile_Callback(hObject, eventdata, handles)
function AxesContext_Callback(hObject, eventdata, handles)
function FTPOptions_Callback(hObject, eventdata, handles)
function BinWidth_Callback(hObject, eventdata, handles)
function BinWidth_CreateFcn(hObject, eventdata, handles)
function SliderValue_CreateFcn(hObject, eventdata, handles)
function Utilities_Callback(hObject, eventdata, handles)
function StimulusAlignedTimeVector_Callback(hObject, eventdata, handles)
function StimulusAlignedTimeVector_CreateFcn(hObject, eventdata, handles)
function AxesToUpdate_Callback(hObject, eventdata, handles)
function AxesToUpdate_CreateFcn(hObject, eventdata, handles)
function TrialFilterVector_Callback(hObject, eventdata, handles)
function PlottingFileList_Callback(hObject, eventdata, handles)
function PlottingFileList_CreateFcn(hObject, eventdata, handles)
function TrialFilterVector_CreateFcn(hObject, eventdata, handles)
function CurrentAxes_Callback(hObject, eventdata, handles)
function CurrentAxes_CreateFcn(hObject, eventdata, handles)
function UpdateCell_Callback(hObject, eventdata, handles)
function Axis1Markers_Callback(hObject, eventdata, handles)
function Axis1Markers_CreateFcn(hObject, eventdata, handles)
function Axis2Markers_Callback(hObject, eventdata, handles)
function Axis2Markers_CreateFcn(hObject, eventdata, handles)
function Axis3Markers_Callback(hObject, eventdata, handles)
function Axis3Markers_CreateFcn(hObject, eventdata, handles)
function Axis4Markers_Callback(hObject, eventdata, handles)
function Axis4Markers_CreateFcn(hObject, eventdata, handles)
function Axis5Markers_Callback(hObject, eventdata, handles)
function Axis5Markers_CreateFcn(hObject, eventdata, handles)
function Axis6Markers_Callback(hObject, eventdata, handles)
function Axis6Markers_CreateFcn(hObject, eventdata, handles)
function Axis7Markers_Callback(hObject, eventdata, handles)
function Axis7Markers_CreateFcn(hObject, eventdata, handles)
function Axis8Markers_Callback(hObject, eventdata, handles)
function Axis8Markers_CreateFcn(hObject, eventdata, handles)
function Axis9Markers_Callback(hObject, eventdata, handles)
function Axis9Markers_CreateFcn(hObject, eventdata, handles)
function ResetProps_Callback(hObject, eventdata, handles)
function UseProps_Callback(hObject, eventdata, handles)
function AddAnalysisFileButton_Callback(hObject, eventdata, handles)
function pushbutton23_Callback(hObject, eventdata, handles)
function pushbutton24_Callback(hObject, eventdata, handles)
function pushbutton25_Callback(hObject, eventdata, handles)
function AnalyzeFile_CreateFcn(hObject, eventdata, handles)
function LoadFile_CreateFcn(hObject, eventdata, handles)
function AddAnalysisFileButton_CreateFcn(hObject, eventdata, handles)
function DeleteLoadedFiles_Callback(hObject, eventdata, handles)
function DeleteLoadedFiles_CreateFcn(hObject, eventdata, handles)
function axes1_CreateFcn(hObject, eventdata, handles)
function axes2_CreateFcn(hObject, eventdata, handles)
function axes3_CreateFcn(hObject, eventdata, handles)
function axes4_CreateFcn(hObject, eventdata, handles)
function axes5_CreateFcn(hObject, eventdata, handles)
function axes6_CreateFcn(hObject, eventdata, handles)
function axes7_CreateFcn(hObject, eventdata, handles)
function axes8_CreateFcn(hObject, eventdata, handles)
function axes9_CreateFcn(hObject, eventdata, handles)
function text30_CreateFcn(hObject, eventdata, handles)
function SaveGraphics_CreateFcn(hObject, eventdata, handles)
function UpdateTheseAxes_CreateFcn(hObject, eventdata, handles)
function AlignCode_Callback(hObject, eventdata, handles)
function AlignCode_CreateFcn(hObject, eventdata, handles)
function ClearAxes_Callback(hObject, eventdata, handles)
function General_Callback(hObject, eventdata, handles)
function GetInsideMe_Callback(hObject, eventdata, handles)
function FTPFile_Callback(hObject, eventdata, handles)
function ClearAll_Callback(hObject, eventdata, handles)
function PlotEdit_Callback(hObject, eventdata, handles)
function AnnotateAxis_Callback(hObject, eventdata, handles)
function UnitNumber_Callback(hObject, eventdata, handles)
function UnitNumber_CreateFcn(hObject, eventdata, handles)
function SetDataDirectory_Callback(hObject, eventdata, handles)
function GetVariables_Callback(hObject, eventdata, handles)
function LaunchViewer_Callback(hObject, eventdata, handles)
function BrowseFTP_Callback(hObject, eventdata, handles)
function edit27_CreateFcn(hObject, eventdata, handles)
function ExportGraphics_Callback(hObject, eventdata, handles)
function ExploreVariables_Callback(hObject, eventdata, handles)
function UseAxisVars_Callback(hObject, eventdata, handles)
function AddVariable_Callback(hObject, eventdata, handles)
function SpikeTruncate_Callback(hObject, eventdata, handles)
function ClearPolar_Callback(hObject, eventdata, handles)
function GetObjectAxes_Callback(hObject, eventdata, handles)
function GetObjectAxes_CreateFcn(hObject, eventdata, handles)
function ObjectNumber_Callback(hObject, eventdata, handles)
function ObjectNumber_CreateFcn(hObject, eventdata, handles)
function OldAxis_Callback(hObject, eventdata, handles)
function OldAxis_CreateFcn(hObject, eventdata, handles)
function NewAxis_Callback(hObject, eventdata, handles)
function NewAxis_CreateFcn(hObject, eventdata, handles)
function DeleteObjects_Callback(hObject, eventdata, handles)
function MoveObj_Callback(hObject, eventdata, handles)
function GetObjectPropsButton_Callback(hObject, eventdata, handles)
function CopyObj_Callback(hObject, eventdata, handles)
function PlotSig_Callback(hObject, eventdata, handles)
function SpeakToMeMenu_Callback(hObject, eventdata, handles)
function MainStuff_Callback(hObject, eventdata, handles)
function QuitXeX_Callback(hObject, eventdata, handles)
function AnalysisOptions_Callback(hObject, eventdata, handles)
function PlotLatency_Callback(hObject, eventdata, handles)
function SetBaselineWindow_Callback(hObject, eventdata, handles)
function PlottingContext_Callback(hObject, eventdata, handles)
function TalkToMe_Callback(hObject, eventdata, handles)
function ErrorBarType_Callback(hObject, eventdata, handles)
function PlotCB_Callback(hObject, eventdata, handles)
function FiltersList_Callback(hObject, eventdata, handles)
function GainGraph_Callback(hObject, eventdata, handles)
function WhatToDo_Callback(hObject, eventdata, handles)
function WhatToDo_CreateFcn(hObject, eventdata, handles)
function UseTheseAxes_Callback(hObject, eventdata, handles)
function UseTheseAxes_CreateFcn(hObject, eventdata, handles)
function LatencyAfter_Callback(hObject, eventdata, handles)
function SetCellProps_Callback(hObject, eventdata, handles)
function VariablesList_Callback(hObject, eventdata, handles)
function VariablesList_CreateFcn(hObject, eventdata, handles)
function Layouts_Callback(hObject, eventdata, handles)
function SixGraph_Callback(hObject, eventdata, handles)
function ManageObjects_Callback(hObject, eventdata, handles)
function ManageObjects_CreateFcn(hObject, eventdata, handles)
function UnBut_Callback(hObject, eventdata, handles)
function UnBut_CreateFcn(hObject, eventdata, handles)
function GraphCommandFiles_Callback(hObject, eventdata, handles)
function GraphCommandFiles_CreateFcn(hObject, eventdata, handles)
function AddGrapher_Callback(hObject, eventdata, handles)
function RunGraph_Callback(hObject, eventdata, handles)
function SetGraphicDir_Callback(hObject, eventdata, handles)
function UnitNumberPop_Callback(hObject, eventdata, handles)
function UnitNumberPop_CreateFcn(hObject, eventdata, handles)
function DelTrials_Callback(hObject, eventdata, handles)
function RmIndicators_Callback(hObject, eventdata, handles)
function ResetLayout_Callback(hObject, eventdata, handles)
function ClearTitle_Callback(hObject, eventdata, handles)
function Axis10Markers_Callback(hObject, eventdata, handles)
function Axis10Markers_CreateFcn(hObject, eventdata, handles)
function Axis11Markers_Callback(hObject, eventdata, handles)
function Axis11Markers_CreateFcn(hObject, eventdata, handles)
function Axis12Markers_Callback(hObject, eventdata, handles)
function Axis12Markers_CreateFcn(hObject, eventdata, handles)
function NineGraphs_Callback(hObject, eventdata, handles)
function EditCmdFile_Callback(hObject, eventdata, handles)
function SigLevel_Callback(hObject, eventdata, handles)
function FTPFileName_Callback(hObject, eventdata, handles)
function FTPFileName_CreateFcn(hObject, eventdata, handles)
function FTPMe_Callback(hObject, eventdata, handles)
function FTPRelated_Callback(hObject, eventdata, handles)
function FTPMode_Callback(hObject, eventdata, handles)
function HelpTips_Callback(hObject, eventdata, handles)
function Help_Callback(hObject, eventdata, handles)
function ResetAxisProps_Callback(hObject, eventdata, handles)
function XAxisVariable_Callback(hObject, eventdata, handles)
function XAxisVariable_CreateFcn(hObject, eventdata, handles)
function X1AxisVariable_Callback(hObject, eventdata, handles)
function X1AxisVariable_CreateFcn(hObject, eventdata, handles)
function XAxisDiscretize_Callback(hObject, eventdata, handles)
function X1AxisDiscretize_Callback(hObject, eventdata, handles)
function XAxisCenters_Callback(hObject, eventdata, handles)
function XAxisCenters_CreateFcn(hObject, eventdata, handles)
function X1AxisCenters_Callback(hObject, eventdata, handles)
function X1AxisCenters_CreateFcn(hObject, eventdata, handles)
function YAxisVariable_Callback(hObject, eventdata, handles)
function YAxisVariable_CreateFcn(hObject, eventdata, handles)
function FTPUpdate_Callback(hObject, eventdata, handles)
function ShowObjWin_Callback(hObject, eventdata, handles)
function AxisObj1_Callback(hObject, eventdata, handles)
function AxisObj1_CreateFcn(hObject, eventdata, handles)
function AxisObj4_Callback(hObject, eventdata, handles)
function AxisObj4_CreateFcn(hObject, eventdata, handles)
function AxisObj9_Callback(hObject, eventdata, handles)
function AxisObj9_CreateFcn(hObject, eventdata, handles)
function AxisObj2_Callback(hObject, eventdata, handles)
function AxisObj2_CreateFcn(hObject, eventdata, handles)
function AxisObj6_Callback(hObject, eventdata, handles)
function AxisObj6_CreateFcn(hObject, eventdata, handles)
function AxisObj10_Callback(hObject, eventdata, handles)
function AxisObj10_CreateFcn(hObject, eventdata, handles)
function AxisObj3_Callback(hObject, eventdata, handles)
function AxisObj3_CreateFcn(hObject, eventdata, handles)
function AxisObj7_Callback(hObject, eventdata, handles)
function AxisObj7_CreateFcn(hObject, eventdata, handles)
function AxisObj11_Callback(hObject, eventdata, handles)
function AxisObj11_CreateFcn(hObject, eventdata, handles)
function edit59_Callback(hObject, eventdata, handles)
function edit59_CreateFcn(hObject, eventdata, handles)
function AxisObj8_Callback(hObject, eventdata, handles)
function AxisObj8_CreateFcn(hObject, eventdata, handles)
function AxisObj12_Callback(hObject, eventdata, handles)
function AxisObj12_CreateFcn(hObject, eventdata, handles)
function AxisObj5_Callback(hObject, eventdata, handles)
function AxisObj5_CreateFcn(hObject, eventdata, handles)
function ShowAllObjWin_Callback(hObject, eventdata, handles)
function MakeLinkable_Callback(hObject, eventdata, handles)
function LinkAxis_Callback(hObject, eventdata, handles)
function ReverseXY_Callback(hObject, eventdata, handles)
function Documentation_Callback(hObject, eventdata, handles)
function DelTrials_CreateFcn(hObject, eventdata, handles)
SOURCE CODE
function varargout = XeX(varargin)
% XEX M-file for XeX.fig
%      XEX, by itself, creates a new XEX or raises the existing
%      singleton*.
%
%      H = XEX returns the handle to a new XEX or the handle to
%      the existing singleton*.
%
%      XEX('CALLBACK',hObject,eventData,handles,...) calls the local
%      function named CALLBACK in XEX.M with the given input arguments.
%
%      XEX('Property','Value',...) creates a new XEX or raises the
%      existing singleton*.  Starting from the left, property value pairs
%      are
%      applied to the GUI before XeX_OpeningFunction gets called.  An
%      unrecognized property name or invalid value makes property
%      application
%      stop.  All inputs are passed to XeX_OpeningFcn via varargin.
%
%      *See GUI Options on GUIDE's Tools menu.  Choose "GUI allows only one
%      instance to run (singleton)".
%
% See also: GUIDE, GUIDATA, GUIHANDLES
% Copyright 2002-2003 The MathWorks, Inc.
% Edit the above text to modify the response to help XeX
% Last Modified by GUIDE v2.5 12-Dec-2006 22:23:26
% Begin initialization code - DO NOT EDIT
gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
                   'gui_Singleton',  gui_Singleton, ...
                   'gui_OpeningFcn', @XeX_OpeningFcn, ...
                   'gui_OutputFcn',  @XeX_OutputFcn, ...
                   'gui_LayoutFcn',  [] , ...
                   'gui_Callback',   []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end
if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end
% End initialization code - DO NOT EDIT
% --- Executes just before XeX is made visible.
function XeX_OpeningFcn(hObject, eventdata, handles, varargin)
% This function has no output args, see OutputFcn.
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% varargin   command line arguments to XeX (see VARARGIN)
XeXDir=which('XeX');
if ~isempty(XeXDir)
handles.XeXDir=XeXDir(1:(end-5));
addpath(genpath(handles.XeXDir),'-begin');
cd(handles.XeXDir);
else
fprintf('%s\n','%Couldnt Find XeX.m on path; assuming XeX lives in current directory and adding it (with subdirectories) to PATH !!');
handles.XeXDir=pwd;
addpath(genpath(handles.XeXDir),'-begin');
end
handles.NumberOfAxes=12;
handles.AxisVariable=repmat(struct('XAxis','Undefined','YAxis','Undefined'),1,handles.NumberOfAxes); %assuming there are 12 axes; safe, I think, for now.
handles.HandlesList=NaN*[1:handles.NumberOfAxes];
for TemporaryVariable=1:handles.NumberOfAxes
eval(['handles.HandlesList(TemporaryVariable)=handles.axes' num2str(TemporaryVariable) ';']);
end
handles.EditWindows=NaN*[1:handles.NumberOfAxes];
for TemporaryVariable=1:handles.NumberOfAxes
eval(['handles.EditWindows(TemporaryVariable)=handles.AxisObj' num2str(TemporaryVariable) ';']);
end
handles.AxisLinkTexts=NaN*[1:handles.NumberOfAxes];
for TemporaryVariable=1:handles.NumberOfAxes
eval(['handles.AxisLinkTexts(TemporaryVariable)=handles.AxisLinkText' num2str(TemporaryVariable) ';']);
end
if strcmp(get(handles.ShowAllObjWin,'checked'),'on') makeVisible(handles.EditWindows); else makeInvisible(handles.EditWindows);end
makeInvisible([handles.AxisLinkTexts]);
LayOutEditWindow;
handles.CurrentDataDirectory='C:\MATLAB\work\physiology\ziggydata';
handles.GraphCommandsDirectory='C:\MATLAB\work\XeX\MyGraphs';
handles.SaccadeOptions.Threshold=0.1;
handles.SaccadeOptions.MinLat=0;
handles.SaccadeOptions.ISICut=0;
handles.SaccadeOptions.CorrectCode=1003;
% handles.ShowSignificance=1;
set(handles.PlotSig,'checked','on');
handles.BaselineWindow=[-50 0];
handles.BaselineFiringRate=NaN;
handles.SpeakToMe=0;
set(handles.SpeakToMeMenu,'checked','off');
setappdata(0,'TrialFilterHandle',(handles.TrialFilterVector));
setappdata(0,'RFLocation',[-15 0]); %default RF
setappdata(0,'XeXGUIHandle',handles.figure1);
% setappdata(0,'UseFilterHandle',handles.UseFilters);
setappdata(0,'UsePlottingHandle',handles.UseProps);
setappdata(0,'HoldFilterHandle',handles.HoldStatus);
% Choose default command line output for XeX
handles.output = hObject;
handles.LatInitTime=0;
handles.SignificanceCutoff=0.05;
handles.LastSelectedDirectory=handles.XeXDir(1:(end-4));
% MyVariableChoices=struct('XAxisVariable','RFx','X1AxisVariable','RFy','YAxisMeasureStr','SpikeRate','DiscretizeX',0,'DiscretizeX1',0,'X1AxisCentersStr','','XAxisCentersStr','','OK',0);
% handles.MyVariableChoices=MyVariableChoices;
set(handles.SpikeTruncate,'checked','on');
set(handles.figure1,'windowstyle','docked');
fprintf('%s\n','*********************************************************************************************');
fprintf('%s\n','Designed to be used with Monitor Resolution Set to 1680 by 1050; 1280 by 1024 appears to work somewhat well too.');
fprintf('%s\n','*********************************************************************************************');
set(gcf,'CloseRequestFcn','fprintf(''%s\n'',''You cannot close XeX like that. Choose Quit'')');
handles.UnitNumber=613;
handles.RFLocation=[15 15];
WhatToDoStuff;
% ShowSlider;
DoUseProps;
Objs=[handles.GetObjectPropsButton, handles.GetObjectAxes, handles.DeleteObjects, handles.MoveObj, handles.CopyObj, handles.text64, handles.text65, handles.text66, handles.ObjectNumber, handles.OldAxis,handles.NewAxis];
if strcmp(get(handles.ManageObjects,'string'), 'ManageObjects'),
    makeInvisible(Objs);
elseif strcmp(get(handles.ManageObjects,'string'),'HideManager'),
    makeVisible(Objs);
end
% GetPositions;
% handles.PosArray=PosArray;
% Update handles structure
guidata(hObject, handles);
% UIWAIT makes XeX wait for user response (see UIRESUME)
% uiwait(handles.figure1);
% --- Outputs from this function are returned to the command line.
function varargout = XeX_OutputFcn(hObject, eventdata, handles)
% varargout  cell array for returning output args (see VARARGOUT);
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Get default command line output from handles structure
varargout{1} = handles.output;
% --------------------------------------------------------------------
function Options_Callback(hObject, eventdata, handles)
% hObject    handle to Options (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% --------------------------------------------------------------------
function SacOpts_Callback(hObject, eventdata, handles)
% hObject    handle to SacOpts (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
if ~isfield(handles,'SaccadeOptions'),
    CurrentThreshold='';
    CurrentMinLat='';
    CurrentISICut='';
    CurrentCorrectCode='';
else
    CurrentThreshold=handles.SaccadeOptions.Threshold;
    CurrentMinLat=handles.SaccadeOptions.MinLat;
    CurrentISICut=handles.SaccadeOptions.ISICut;
    CurrentCorrectCode=handles.SaccadeOptions.CorrectCode;
end
   prompt={'Enter Sac Threshold','Enter Min Lat','Enter ISI Cut','Enter Correct Code; use NaN for null'};
   name='Saccade Options ';
   numlines=1;
   defaultanswer={num2str(CurrentThreshold) num2str(CurrentMinLat) num2str(CurrentISICut) num2str(CurrentCorrectCode)};
   Answer=inputdlg(prompt,name,numlines,defaultanswer);
   if ~isempty(Answer)
handles.SaccadeOptions.Threshold=str2num(Answer{1});
handles.SaccadeOptions.MinLat=str2num(Answer{2});
handles.SaccadeOptions.ISICut=str2num(Answer{3});
handles.SaccadeOptions.CorrectCode=str2num(Answer{4});
   end
   guidata(hObject,handles);
% --- Executes on selection change in LoadedFiles.
function LoadedFiles_Callback(hObject, eventdata, handles)
% hObject    handle to LoadedFiles (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: contents = get(hObject,'String') returns LoadedFiles contents as cell array
%        contents{get(hObject,'Value')} returns selected item from LoadedFiles
Contents=cellstr(get(hObject,'String'));
fprintf('You just selected   %s\n',Contents{get(hObject,'Value')});
 LoadedFileList=get(handles.LoadedFiles,'string');
 if ~iscell(LoadedFileList), TempVar{1}=LoadedFileList; LoadedFileList=TempVar;end
 CurrentValue=get(handles.LoadedFiles,'value'); CurrentValue=CurrentValue(1);
 CurrentDataFile=LoadedFileList{CurrentValue};
if ~strcmp(CurrentDataFile,'LoadedFiles')
eval(['Trials=handles.' CurrentDataFile '.Trials;']);
eval(['if ~isfield(handles.' CurrentDataFile ',''Analysis''), GoOn=0;else GoOn=1;end']);
eval(['if GoOn==1, MyVariableList=handles.' CurrentDataFile '.Analysis.MyVariableList;end']);
eval(['if GoOn==1, MyResponseVariableList=handles.' CurrentDataFile '.Analysis.MyResponseVariableList;end']);
eval(['if GoOn==1, CurrentVariables=handles.' CurrentDataFile '.Analysis;end']);
if GoOn==1, fprintf('%s\n',CurrentVariables.summaryString);end
if GoOn==1,
%     if get(handles.XAxisVariable,'value')>length(MyVariableList), set(handles.XAxisVariable,'value',1);end
%  set(handles.XAxisVariable,'string',MyVariableList);
%     if get(handles.X1AxisVariable,'value')>length(MyVariableList), set(handles.X1AxisVariable,'value',1);end
%  set(handles.X1AxisVariable,'string',MyVariableList);
%     if get(handles.YAxisVariable,'value')>length(MyVariableList), set(handles.YAxisVariable,'value',1);end
%  set(handles.YAxisVariable,'string',{'SpikeRate',MyVariableList{:}});
SetVariablesScript;
end
end
% --- Executes during object creation, after setting all properties.
function LoadedFiles_CreateFcn(hObject, eventdata, handles)
% hObject    handle to LoadedFiles (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: listbox controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
set(hObject,'tooltipstring','This is the list of loaded files');
guidata(hObject,handles);
% --- Executes on selection change in AnalysisFile.
function AnalysisFile_Callback(hObject, eventdata, handles)
% hObject    handle to AnalysisFile (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: contents = get(hObject,'String') returns AnalysisFile contents as cell array
%        contents{get(hObject,'Value')} returns selected item from AnalysisFile
% --- Executes during object creation, after setting all properties.
function AnalysisFile_CreateFcn(hObject, eventdata, handles)
% hObject    handle to AnalysisFile (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: popupmenu controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
set(hObject,'tooltipstring',sprintf('This is the list of analysis files: will generate\nvectors of length=number of trials\n that you can then run trial filters on'));
guidata(hObject,handles);
% --- Executes on button press in AnalyzeFile.
function AnalyzeFile_Callback(hObject, eventdata, handles)
% hObject    handle to AnalyzeFile (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
LoadedFileList=get(handles.LoadedFiles,'string');
CurrentValues=get(handles.LoadedFiles,'value');
if ~iscell(LoadedFileList), LoadedFileList={LoadedFileList};end
CurrentlyLoadedFiles=LoadedFileList(CurrentValues);
% CurrentUseAx=get(handles.UseStimAxes,'Value');
% if CurrentUseAx==1, CurrentUseAx=handles.axes7;else CurrentUseAx=[];end
if ~strcmp(CurrentlyLoadedFiles{1},'LoadedFiles')
for FileIndex=1:length(CurrentlyLoadedFiles)
    CurrentFile=CurrentlyLoadedFiles{FileIndex};
    %Reload files if necessary
    eval(['TempStore=handles.' CurrentFile '.Trials;']);
    if isnumeric(TempStore) && isnan(TempStore)
        eval(['TempFile=handles.' CurrentFile '.FileName;']);
        if strfind(TempFile,'.mat')
            JustLoadedTrials=load(TempFile);
            fprintf('%s\n',['Loaded trials from ' TempFile]);
        else
            try,
             eval(['JustLoadedTrials = mrdr(''-s 1001'',''800'',''-d'',''',TempFile(1:(end-1)),''');']);
             JustLoadedTrials=JustLoadedTrials(2:(end-1));
                         fprintf('%s\n',['Loaded trials from ' TempFile]);
            catch,
                fprintf('%s\n','mrdr failed !!!!!!!!!!!!');
             end
        end
                if length(JustLoadedTrials)>0     eval([CurrentFile ' .Trials=JustLoadedTrials;']); clear JustLoadedTrials; end
    else
           eval([CurrentFile '.Trials=handles.' CurrentFile '.Trials;']);
    end
    AnalysisFiles=get(handles.AnalysisFile,'string');
    AnalysisFileValue=get(handles.AnalysisFile,'value');
    CurrentAnalysisFile=AnalysisFiles{AnalysisFileValue};
    CurrentAnalysisFile=CurrentAnalysisFile(1:(end-2));
%     if ~isempty(CurrentUseAx)
%     eval(['ResultVariables=' CurrentAnalysisFile '(' CurrentFile '.Trials,''' CurrentFile ''', CurrentUseAx, handles.SaccadeOptions);']);
% else
     eval(['ResultVariables=' CurrentAnalysisFile '(' CurrentFile '.Trials,''' CurrentFile ''', 0, handles.SaccadeOptions);']);
%     end
                 eval(['handles.' CurrentFile '.Analysis=ResultVariables;']);
                 MyVariableList=ResultVariables.MyVariableList;
%                  set(handles.XAxisVariable,'value',1);
%                  set(handles.XAxisVariable,'string',ResultVariables.MyVariableList);
%                                   set(handles.X1AxisVariable,'value',1);
%                  set(handles.X1AxisVariable,'string',ResultVariables.MyVariableList);
%                  set(handles.YAxisVariable,'value',1);
%                  set(handles.YAxisVariable,'string',{'SpikeRate',ResultVariables.MyVariableList{:}});
    TellMe('%s\n',['Completed one   ' CurrentAnalysisFile ],handles.SpeakToMe);
end
AnalLoadedFileScript;
else TellMe('%s\n','Load a file first !',handles.SpeakToMe);
end
% ShowSlider;
% eval(['clear ' CurrentFile]);
guidata(hObject,handles);
% --- Executes on button press in HoldStatus.
function HoldStatus_Callback(hObject, eventdata, handles)
% hObject    handle to HoldStatus (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hint: get(hObject,'Value') returns toggle state of HoldStatus
% --- Executes on button press in PlotData.
function PlotData_Callback(hObject, eventdata, handles)
% hObject    handle to PlotData (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
ThingsToDo=get(handles.WhatToDo,'string');
WhatToDo=ThingsToDo{get(handles.WhatToDo,'value')};
if strcmp(WhatToDo,'UpdateAxis')
%     BackupGraphs;
       NextCommandSetBaseRate=0;
UpdateGObjects;
elseif strcmp(WhatToDo,'UpdateCell')
%         BackupGraphs;
       NextCommandSetBaseRate=0;
LoadGFXVar=0; UpdateCellOrLoadGFX;
elseif strcmp(WhatToDo,'MakePlot')
FilterStringList=cellstr(get(handles.TrialFilterVector,'string'));
      CurrentFilterString=FilterStringList{1};
%       if get(handles.UseFilters,'value')==0, CurrentFilterString='';end
       for TempVarA=1:handles.NumberOfAxes
 eval([ 'Axis' num2str(TempVarA) 'MarkerPointer=0;'...
 ]);
       end
       getCurrentParameters;
       NextCommandSetBaseRate=0;
if isempty(CurrentUnitNumber), CurrentUnitNumber=613; fprintf('%s\n','Using 613 as the Unit');end
if ~strcmp(CurrentDataFile,'LoadedFiles') & ~strcmp(CurrentPlottingFile,'PlottingFile')
for numFilters=1:length(FilterStringList)
      CurrentFilterString=FilterStringList{numFilters};
      if isempty(CurrentFilterString), CurrentFilterString='1';end
      %need a line here so that switchaxes is called at beginning and hten
      %for every newaxis line
      if numFilters==1, SwitchAxes; end
      PlotOK=1;       % Initializes to PlotOK, FInterpreter will cancel to No Plot if needed
      FInterpreter;  %This calls the filter interpreter !!!!
            if RunCode==1,
                    eval(['Trials=handles.' CurrentDataFile '.Trials;']);
          eval(['if ~isfield(handles.' CurrentDataFile ',''Analysis''), fprintf(''%s\n'',''Analyze your dataset first''); GoOn=0;else GoOn=1;end']);
          eval(['if GoOn==1, CurrentVariables=handles.' CurrentDataFile '.Analysis;end']);
                    if GoOn==1
CurrentVariables=ParamEval(XexParameters,CurrentVariables);
eval(['handles.' CurrentDataFile '.Analysis=CurrentVariables;']);
          end
% eval(XexParameters);
              fprintf('%s\n','Running:');
    fprintf('%s\n',XexParameters);
end
          if PlotOK==1,
              NoChangeAxesPointer=1;
                      getCurrentParameters;  % makes sure all finterpreter changes are loaded in
 %   try
eval(['Trials=handles.' CurrentDataFile '.Trials;']);
eval(['if ~isfield(handles.' CurrentDataFile ',''Analysis''), fprintf(''%s\n'',''Analyze your dataset first''); GoOn=0;else GoOn=1;end']);
eval(['if GoOn==1, CurrentVariables=handles.' CurrentDataFile '.Analysis;end']);
%  eval(['if GoOn==1, fprintf(''%s\n'',''Plotting Now'');' CurrentPlottingFile(1:(end-2)) ';end']);  %running the current plotting file
% if RunCode==1, eval(XexParameters);
%     fprintf('%s\n','Running:');
%     fprintf('%s\n',XexParameters);
% end
if NextCommandSetBaseRate==1
    SetBaseRate; NextCommandSetBaseRate=0;
else
 eval(['if GoOn==1, ' CurrentPlottingFile(1:(end-2)) ';end']);  %running the current plotting file
   %   catch, fprintf('%s\t','Error in PlottingFile:'); fprintf('%s\n',lasterr);
     %end
end
end
end
else TellMe('%s\n','Make sure you have selected a data file and a plotting file',handles.SpeakToMe);
end
else fprintf('%s\n','That button is inactive !!');
end
guidata(hObject,handles);  %routinely saving anything assigned to handles
% % --- Executes on button press in AddPlottingFile.
% function AddPlottingFile_Callback(hObject, eventdata, handles)
% % hObject    handle to AddPlottingFile (see GCBO)
% % eventdata  reserved - to be defined in a future version of MATLAB
% % handles    structure with handles and user data (see GUIDATA)
%
% Old_Dir=pwd;
% if ~exist('DataDirectory','var'), DataDirectory='c:\MATLAB\work\XeX\AnalysisFunctions';end
% cd(DataDirectory);
%
%    [input_filename, input_pathname] = uigetfile(...
%        {'*.m','M-files (*.m)';
%         '*.*',  'All Files (*.*)'}, ...
%         'Pick a Trials file', ...
%         'MultiSelect', 'on');
%
%     %%loading the files
%
%      if ~isnumeric(input_filename)
%      if ~iscell(input_filename) TemporaryStuff{1}=input_filename;
%      input_filename=TemporaryStuff;
%      end
%
% AnalysisFileNames=get(handles.PlottingFileList,'string');
%          if ~iscell(AnalysisFileNames)&~strcmp(AnalysisFileNames,'PlottingFile')
%              TemporaryStuff{1}=AnalysisFileNames;
%              AnalysisFileNames=TemporaryStuff;
%          end
%
%          if ~iscell(AnalysisFileNames)
%              set(handles.PlottingFileList,'string',sort(input_filename));
%          else
%              NewNames=setdiff(input_filename,AnalysisFileNames);
%              set(handles.PlottingFileList,'string',sort([NewNames AnalysisFileNames']'));
%          end
%
%          guidata(hObject,handles);
%
%      end
%
%         cd(Old_Dir);
% --- Executes on selection change in CodeBitMenu.
function CodeBitMenu_Callback(hObject, eventdata, handles)
% hObject    handle to CodeBitMenu (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: contents = get(hObject,'String') returns CodeBitMenu contents as cell array
%        contents{get(hObject,'Value')} returns selected item from CodeBitMenu
% --- Executes during object creation, after setting all properties.
function CodeBitMenu_CreateFcn(hObject, eventdata, handles)
% hObject    handle to CodeBitMenu (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: popupmenu controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
% --- Executes on button press in LoadFile.
function LoadFile_Callback(hObject, eventdata, handles)
% hObject    handle to LoadFile (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
LoadFileCallbackStuff;
% --------------------------------------------------------------------
function AxesContext_Callback(hObject, eventdata, handles)
% hObject    handle to AxesContext (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% --------------------------------------------------------------------
function FTPOptions_Callback(hObject, eventdata, handles)
% hObject    handle to FTPOptions (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
if ~isfield(handles,'FTP'), CurrentFTPPath='/annegret_data/'; CurrentFTPFile='';
else CurrentFTPPath=(handles.FTP.pathname);
    CurrentFTPFile=handles.FTP.filename;
end
   prompt={'Enter FTP path','Enter FTP file'};
   name='FTP Options ';
   numlines=1;
   defaultanswer={CurrentFTPPath CurrentFTPFile};
   Answer=inputdlg(prompt,name,numlines,defaultanswer);
   if ~isempty(Answer)
CurrentFTPPath=Answer{1};
CurrentFTPFile=Answer{2};
handles.FTP.pathname=CurrentFTPPath;
handles.FTP.filename=CurrentFTPFile;
   end
   guidata(hObject,handles);
% --- Executes on slider movement.
function BinWidth_Callback(hObject, eventdata, handles)
% hObject    handle to BinWidth (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'Value') returns position of slider
%        get(hObject,'Min') and get(hObject,'Max') to determine range of slider
CurrentValue=get(hObject,'Value');
set(handles.SliderValue,'String',['BW','=',num2str(CurrentValue)]);
ThingsToDo=get(handles.WhatToDo,'String');
WhatToDo=ThingsToDo{get(handles.WhatToDo,'value')};
if strcmp(WhatToDo,'ActiveUpdate'),
UpdateType='BW';
UpdateSlider;
end
guidata(hObject,handles);
% --- Executes during object creation, after setting all properties.
function BinWidth_CreateFcn(hObject, eventdata, handles)
% hObject    handle to BinWidth (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: slider controls usually have a light gray background.
if isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor',[.9 .9 .9]);
end
% --- Executes during object creation, after setting all properties.
function SliderValue_CreateFcn(hObject, eventdata, handles)
% hObject    handle to SliderValue (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% --------------------------------------------------------------------
function Utilities_Callback(hObject, eventdata, handles)
% hObject    handle to Utilities (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
function StimulusAlignedTimeVector_Callback(hObject, eventdata, handles)
% hObject    handle to StimulusAlignedTimeVector (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of StimulusAlignedTimeVector as text
%        str2double(get(hObject,'String')) returns contents of StimulusAlignedTimeVector as a double
ThingsToDo=get(handles.WhatToDo,'String');
WhatToDo=ThingsToDo{get(handles.WhatToDo,'value')};
if strcmp(WhatToDo,'ActiveUpdate'),
UpdateType='TimeWindow';
UpdateSlider;
end
guidata(hObject,handles);
% --- Executes during object creation, after setting all properties.
function StimulusAlignedTimeVector_CreateFcn(hObject, eventdata, handles)
% hObject    handle to StimulusAlignedTimeVector (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
% function SaccadeAlignedTimeVector_Callback(hObject, eventdata, handles)
% % hObject    handle to SaccadeAlignedTimeVector (see GCBO)
% % eventdata  reserved - to be defined in a future version of MATLAB
% % handles    structure with handles and user data (see GUIDATA)
%
% % Hints: get(hObject,'String') returns contents of SaccadeAlignedTimeVector as text
% %        str2double(get(hObject,'String')) returns contents of SaccadeAlignedTimeVector as a double
%
%
% % --- Executes during object creation, after setting all properties.
% function SaccadeAlignedTimeVector_CreateFcn(hObject, eventdata, handles)
% % hObject    handle to SaccadeAlignedTimeVector (see GCBO)
% % eventdata  reserved - to be defined in a future version of MATLAB
% % handles    empty - handles not created until after all CreateFcns called
%
% % Hint: edit controls usually have a white background on Windows.
% %       See ISPC and COMPUTER.
% if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
%     set(hObject,'BackgroundColor','white');
% end
function AxesToUpdate_Callback(hObject, eventdata, handles)
% hObject    handle to AxesToUpdate (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of AxesToUpdate as text
%        str2double(get(hObject,'String')) returns contents of AxesToUpdate as a double
% --- Executes during object creation, after setting all properties.
function AxesToUpdate_CreateFcn(hObject, eventdata, handles)
% hObject    handle to AxesToUpdate (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
%
% % --- Executes on button press in UpdateTheseAxes.
% function UpdateTheseAxes_Callback(hObject, eventdata, handles)
% % hObject    handle to UpdateTheseAxes (see GCBO)
% % eventdata  reserved - to be defined in a future version of MATLAB
% % handles    structure with handles and user data (see GUIDATA)
%
% BackupGraphs;
% UpdateGObjects;
% guidata(hObject,handles);  %routinely saving anything assigned to handles
% --- Executes when something happens in TrialFilterVector, I think.
function TrialFilterVector_Callback(hObject, eventdata, handles)
% hObject    handle to TrialFilterVector (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of TrialFilterVector as text
%        str2double(get(hObject,'String')) returns contents of TrialFilterVector as a double
ThingsToDo=get(handles.WhatToDo,'String');
WhatToDo=ThingsToDo{get(handles.WhatToDo,'value')};
if strcmp(WhatToDo,'ActiveUpdate'),
UpdateType='Filter';
UpdateSlider;
end
guidata(hObject,handles);
% --- Executes on selection change in PlottingFileList.
function PlottingFileList_Callback(hObject, eventdata, handles)
% hObject    handle to PlottingFileList (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: contents = get(hObject,'String') returns PlottingFileList contents as cell array
%        contents{get(hObject,'Value')} returns selected item from PlottingFileList
% ShowSlider;
contents=get(hObject,'String');
currentselection=contents{get(hObject,'value')};
switch(currentselection),
    case 'ImageMap.m', set(handles.StimulusAlignedTimeVector,'string','[50 150]'); if isempty(char(get(handles.TrialFilterVector,'string'))),set(handles.TrialFilterVector,'string','GoodTrial==1&PhotoBad~=1');end
        XAxisVariables=get(handles.XAxisVariable,'string');
        WhereisRFx=find(strcmp(XAxisVariables,'RFx'));
        if ~isempty(WhereisRFx), set(handles.XAxisVariable,'value',WhereisRFx(1)); set(handles.XAxisDiscretize,'value',1); set(handles.XAxisCenters,'string','-25:5:25');end
       X1AxisVariables=get(handles.X1AxisVariable,'string');
        WhereisRFy=find(strcmp(X1AxisVariables,'RFy'));
        if ~isempty(WhereisRFy), set(handles.X1AxisVariable,'value',WhereisRFy(1)); set(handles.X1AxisDiscretize,'value',1); set(handles.X1AxisCenters,'string','-25:5:25');end
       YAxisVariables=get(handles.YAxisVariable,'string');
        WhereisSpikeRate=find(strcmp(YAxisVariables,'SpikeRate'));
        if ~isempty(WhereisSpikeRate), set(handles.YAxisVariable,'value',WhereisSpikeRate(1)); end
    case 'CircleMap.m', set(handles.StimulusAlignedTimeVector,'string','[50 150]');if isempty(char(get(handles.TrialFilterVector,'string'))),set(handles.TrialFilterVector,'string','GoodTrial==1&PhotoBad~=1');end
    case 'SpikeDensity.m', set(handles.StimulusAlignedTimeVector,'string','[-400 400]');
    case 'DrawPSTH.m', set(handles.StimulusAlignedTimeVector,'string','[-400 400]');
end
        guidata(hObject,handles);
% --- Executes during object creation, after setting all properties.
function PlottingFileList_CreateFcn(hObject, eventdata, handles)
% hObject    handle to PlottingFileList (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: popupmenu controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
% --- Executes during object creation, after setting all properties.
function TrialFilterVector_CreateFcn(hObject, eventdata, handles)
% hObject    handle to TrialFilterVector (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
% set(hObject,'tooltipstring',sprintf(['This is a key area. Enter FilterValues like RFPat==28&GoodTrial==1 \nor RFx<0 & RFy>0 for upper left quadrant, etc. If empty, or set to ''TrialFilterVector'', it will be set to 1\nIf NA, then update axes will ignore it\n and use'...
%     'the saved filter string in the graphics object']));
guidata(hObject,handles);
% --- Executes on selection change in CurrentAxes.
function CurrentAxes_Callback(hObject, eventdata, handles)
% hObject    handle to CurrentAxes (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: contents = get(hObject,'String') returns CurrentAxes contents as cell array
%        contents{get(hObject,'Value')} returns selected item from CurrentAxes
% --- Executes during object creation, after setting all properties.
function CurrentAxes_CreateFcn(hObject, eventdata, handles)
% hObject    handle to CurrentAxes (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: listbox controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
% --- Executes on button press in UpdateCell.
function UpdateCell_Callback(hObject, eventdata, handles)
% hObject    handle to UpdateCell (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
%UpdateCell;
% BackupGraphs;
NextCommandSetBaseRate=0;
LoadGFXVar=0; UpdateCellOrLoadGFX;
guidata(hObject,handles);  %routinely saving anything assigned to handles
function Axis1Markers_Callback(hObject, eventdata, handles)
% hObject    handle to Axis1Markers (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of Axis1Markers as text
%        str2double(get(hObject,'String')) returns contents of Axis1Markers as a double
CurrentAxisMarkerNumber=1;
UpdateMarkers;
guidata(hObject,handles);
% --- Executes during object creation, after setting all properties.
function Axis1Markers_CreateFcn(hObject, eventdata, handles)
% hObject    handle to Axis1Markers (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function Axis2Markers_Callback(hObject, eventdata, handles)
% hObject    handle to Axis2Markers (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of Axis2Markers as text
%        str2double(get(hObject,'String')) returns contents of Axis2Markers as a double
CurrentAxisMarkerNumber=2;
UpdateMarkers;
guidata(hObject,handles);
% --- Executes during object creation, after setting all properties.
function Axis2Markers_CreateFcn(hObject, eventdata, handles)
% hObject    handle to Axis2Markers (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function Axis3Markers_Callback(hObject, eventdata, handles)
% hObject    handle to Axis3Markers (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of Axis3Markers as text
%        str2double(get(hObject,'String')) returns contents of Axis3Markers as a double
CurrentAxisMarkerNumber=3;
UpdateMarkers;
guidata(hObject,handles);
% --- Executes during object creation, after setting all properties.
function Axis3Markers_CreateFcn(hObject, eventdata, handles)
% hObject    handle to Axis3Markers (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function Axis4Markers_Callback(hObject, eventdata, handles)
% hObject    handle to Axis4Markers (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of Axis4Markers as text
%        str2double(get(hObject,'String')) returns contents of Axis4Markers as a double
CurrentAxisMarkerNumber=4;
UpdateMarkers;
guidata(hObject,handles);
% --- Executes during object creation, after setting all properties.
function Axis4Markers_CreateFcn(hObject, eventdata, handles)
% hObject    handle to Axis4Markers (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function Axis5Markers_Callback(hObject, eventdata, handles)
% hObject    handle to Axis5Markers (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of Axis5Markers as text
%        str2double(get(hObject,'String')) returns contents of Axis5Markers as a double
CurrentAxisMarkerNumber=5;
UpdateMarkers;
guidata(hObject,handles);
% --- Executes during object creation, after setting all properties.
function Axis5Markers_CreateFcn(hObject, eventdata, handles)
% hObject    handle to Axis5Markers (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function Axis6Markers_Callback(hObject, eventdata, handles)
% hObject    handle to Axis6Markers (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of Axis6Markers as text
%        str2double(get(hObject,'String')) returns contents of Axis6Markers as a double
CurrentAxisMarkerNumber=6;
UpdateMarkers;
guidata(hObject,handles);
% --- Executes during object creation, after setting all properties.
function Axis6Markers_CreateFcn(hObject, eventdata, handles)
% hObject    handle to Axis6Markers (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
1000 function Axis7Markers_Callback(hObject, eventdata, handles)
1001 % hObject    handle to Axis7Markers (see GCBO)
1002 % eventdata  reserved - to be defined in a future version of MATLAB
1003 % handles    structure with handles and user data (see GUIDATA)
1004
1005 % Hints: get(hObject,'String') returns contents of Axis7Markers as text
1006 %        str2double(get(hObject,'String')) returns contents of Axis7Markers as a double
1007
1008 CurrentAxisMarkerNumber=7;
1009 UpdateMarkers;
1010 guidata(hObject,handles);
1011
1012
1013 % --- Executes during object creation, after setting all properties.
1014 function Axis7Markers_CreateFcn(hObject, eventdata, handles)
1015 % hObject    handle to Axis7Markers (see GCBO)
1016 % eventdata  reserved - to be defined in a future version of MATLAB
1017 % handles    empty - handles not created until after all CreateFcns called
1018
1019 % Hint: edit controls usually have a white background on Windows.
1020 %       See ISPC and COMPUTER.
1021 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1022     set(hObject,'BackgroundColor','white');
1023 end
1024
1025
1026
1027 function Axis8Markers_Callback(hObject, eventdata, handles)
1028 % hObject    handle to Axis8Markers (see GCBO)
1029 % eventdata  reserved - to be defined in a future version of MATLAB
1030 % handles    structure with handles and user data (see GUIDATA)
1031
1032 % Hints: get(hObject,'String') returns contents of Axis8Markers as text
1033 %        str2double(get(hObject,'String')) returns contents of Axis8Markers as a double
1034
1035 CurrentAxisMarkerNumber=8;
1036 UpdateMarkers;
1037 guidata(hObject,handles);
1038
1039 % --- Executes during object creation, after setting all properties.
1040 function Axis8Markers_CreateFcn(hObject, eventdata, handles)
1041 % hObject    handle to Axis8Markers (see GCBO)
1042 % eventdata  reserved - to be defined in a future version of MATLAB
1043 % handles    empty - handles not created until after all CreateFcns called
1044
1045 % Hint: edit controls usually have a white background on Windows.
1046 %       See ISPC and COMPUTER.
1047 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1048     set(hObject,'BackgroundColor','white');
1049 end
1050
1051
1052
1053 function Axis9Markers_Callback(hObject, eventdata, handles)
1054 % hObject    handle to Axis9Markers (see GCBO)
1055 % eventdata  reserved - to be defined in a future version of MATLAB
1056 % handles    structure with handles and user data (see GUIDATA)
1057
1058 % Hints: get(hObject,'String') returns contents of Axis9Markers as text
1059 %        str2double(get(hObject,'String')) returns contents of Axis9Markers as a double
1060
1061 CurrentAxisMarkerNumber=9;
1062 UpdateMarkers;
1063 guidata(hObject,handles);
1064
1065
1066 % --- Executes during object creation, after setting all properties.
1067 function Axis9Markers_CreateFcn(hObject, eventdata, handles)
1068 % hObject    handle to Axis9Markers (see GCBO)
1069 % eventdata  reserved - to be defined in a future version of MATLAB
1070 % handles    empty - handles not created until after all CreateFcns called
1071
1072 % Hint: edit controls usually have a white background on Windows.
1073 %       See ISPC and COMPUTER.
1074 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1075     set(hObject,'BackgroundColor','white');
1076 end
1077
1078 % --- Executes on button press in ResetProps.
1079 function ResetProps_Callback(hObject, eventdata, handles)
1080 % hObject    handle to ResetProps (see GCBO)
1081 % eventdata  reserved - to be defined in a future version of MATLAB
1082 % handles    structure with handles and user data (see GUIDATA)
1083
1084 for TempVar=1:handles.NumberOfAxes
1085     eval(['set(handles.Axis' num2str(TempVar) 'Markers,''string'',''b-r-m-c-k-y-'');']);
1086 end
1087
1088 guidata(hObject,handles);
1089
1090
1091 % --- Executes on button press in UseProps.
1092 function UseProps_Callback(hObject, eventdata, handles)
1093 % hObject    handle to UseProps (see GCBO)
1094 % eventdata  reserved - to be defined in a future version of MATLAB
1095 % handles    structure with handles and user data (see GUIDATA)
1096
1097 % Hint: get(hObject,'Value') returns toggle state of UseProps
1098
1099 DoUseProps;
1100
1101 guidata(hObject,handles);
1102
1103 % --- Executes on button press in AddAnalysisFileButton.
1104 function AddAnalysisFileButton_Callback(hObject, eventdata, handles)
1105 % hObject    handle to AddAnalysisFileButton (see GCBO)
1106 % eventdata  reserved - to be defined in a future version of MATLAB
1107 % handles    structure with handles and user data (see GUIDATA)
1108
1109 Old_Dir=pwd;
1110 if ~exist('DataDirectory','var'), DataDirectory='c:\MATLAB\work\XeX\PreProcFunctions';end
1111 cd(DataDirectory);
1112
1113    [input_filename, input_pathname] = uigetfile(...
1114        {'*.m','M-files (*.m)';
1115         '*.*',  'All Files (*.*)'}, ...
1116         'Add an Analysis File', ...
1117         'MultiSelect', 'on');
1118
1119     %%loading the files
1120
1121      if ~isnumeric(input_filename)
1122      if ~iscell(input_filename) TemporaryStuff{1}=input_filename;
1123      input_filename=TemporaryStuff;
1124      end
1125
1126 AnalysisFileNames=get(handles.AnalysisFile,'string');
1127          if ~iscell(AnalysisFileNames)
1128              TemporaryStuff{1}=AnalysisFileNames;
1129              AnalysisFileNames=TemporaryStuff;
1130          end
1131
1132          if ~iscell(AnalysisFileNames)
1133              set(handles.AnalysisFile,'string',sort(input_filename));
1134          else
1135              NewNames=setdiff(input_filename,AnalysisFileNames);
1136              set(handles.AnalysisFile,'string',sort([NewNames AnalysisFileNames']'));
1137          end
1138
1139          guidata(hObject,handles);
1140
1141      end
1142
1143         cd(Old_Dir);
1144
1145
1146 % % --- Executes on button press in SaveGraphics.
1147 % function SaveGraphics_Callback(hObject, eventdata, handles)
1148 % % hObject    handle to SaveGraphics (see GCBO)
1149 % % eventdata  reserved - to be defined in a future version of MATLAB
1150 % % handles    structure with handles and user data (see GUIDATA)
1151 %
1152 % Old_Dir=pwd;
1153 % if isfield(handles,'GraphicsDirectory'), cd(handles.GraphicsDirectory); else try,cd('c:\MATLAB\work\physiology\GraphicsObjects');
1154 %     catch,fprintf('%s\n','Didnt find graphics directory');end
1155 % end
1156 %
1157 % TempGraphs=[];
1158 % for TempVar=1:(handles.NumberOfAxes)
1159 %     EvalString=[...
1160 %         'if isfield(handles,''A' num2str(TempVar) '''),TempGraphs.A' num2str(TempVar) '=handles.A' num2str(TempVar) ';end'...
1161 %         ];
1162 %     eval(EvalString);
1163 %         EvalString=[...
1164 %         'if isfield(handles,''A' num2str(TempVar) 'Annotations''),TempGraphs.A' num2str(TempVar) 'Annotations=handles.A' num2str(TempVar) 'Annotations;end'...
1165 %         ];
1166 %     eval(EvalString);
1167 % end
1168 % if ~isempty(TempGraphs)
1169 %
1170 %      [filename, pathname, filterindex] = uiputfile(...
1171 %        {'*_gfx.mat','GFX-files (*_gfx.mat)'; ...
1172 %         '*.*',  'All Files (*.*)'}, ...
1173 %         'Save Graphics Object as', 'Untitled_gfx.mat');
1174 %
1175 %     if filename~=0, save([pathname filename],'TempGraphs'),
1176 %     TellMe('%s\n',['Saved to    ' filename],handles.SpeakToMe);
1177 %     end
1178 % else fprintf('%s\n','TempGraphs is empty !!'); keyboard;
1179 % end
1180 %
1181 % cd(Old_Dir);
1182 %
1183 % guidata(hObject,handles);
1184
1185 % % --- Executes on button press in LoadGraphics.
1186 % function LoadGraphics_Callback(hObject, eventdata, handles)
1187 % % hObject    handle to LoadGraphics (see GCBO)
1188 % % eventdata  reserved - to be defined in a future version of MATLAB
1189 % % handles    structure with handles and user data (see GUIDATA)
1190 %
1191 % Old_Dir=pwd;
1192 % if isfield(handles,'GraphicsDirectory'), cd(handles.GraphicsDirectory); else try,cd('c:\MATLAB\work\physiology\GraphicsObjects');
1193 %     catch,fprintf('%s\n','Didnt find graphics directory');end
1194 % end
1195 %
1196 % CurrentHoldStatus=get(handles.HoldStatus,'Value');
1197 %
1198 %    [CurrentFile, input_pathname] = uigetfile(...
1199 %        {'*_gfx.mat','graphix_mat-files (*_gfx.mat)';...
1200 %         '*.*',  'All Files (*.*)'}, ...
1201 %         'Pick a Graphics Object file');
1202 %
1203 %     %%loading the files
1204 %
1205 %      if ~isnumeric(CurrentFile)
1206 %
1207 %      cd(input_pathname);
1208 %
1209 %          if ~isempty(strfind(CurrentFile,'.mat'))
1210 %              CurrentFile=CurrentFile(1:(end-4));
1211 %              eval([CurrentFile '= load(''' CurrentFile '.mat'');']);
1212 %              eval(['TempGraphs=' CurrentFile '.TempGraphs;']);
1213 %
1214 %              for TempVar=1:(handles.NumberOfAxes)
1215 %                  NStr=num2str(TempVar);
1216 %
1217 %                  LocalTempEvalString=['if isfield(TempGraphs,''A' NStr '''),'...
1218 %                      'TempLen=length(TempGraphs.A' NStr ');'...
1219 %                      'if isfield(handles,''A' NStr '''), OldLen=length(handles.A' NStr '); else OldLen=0;end,'...
1220 %                      'for indica=1:TempLen, TempGraphs.A' NStr '(indica).newgraph=1;end,'...
1221 %                      'if CurrentHoldStatus==1, handles.A' NStr '((OldLen+1):(OldLen+TempLen))=TempGraphs.A' NStr ';end,'...
1222 %                      'if CurrentHoldStatus~=1, handles.A' NStr '=TempGraphs.A' NStr ';end,'...
1223 %                      'if isfield(TempGraphs,''A' NStr 'Annotations''), handles.A' NStr 'Annotations=TempGraphs.A' NStr 'Annotations;end,'...
1224 %                  'end;'];
1225 %                  eval(LocalTempEvalString);
1226 %                  clear LocalTempEvalString;
1227 %              end
1228 %          end
1229 %
1230 % LoadGFXVar=1;
1231 % UpdateCellOrLoadGFX;
1232 % guidata(hObject,handles);
1233 %
1234 %      end
1235 %
1236
1237 % --- Executes on button press in pushbutton23.
1238 function pushbutton23_Callback(hObject, eventdata, handles)
1239 % hObject    handle to pushbutton23 (see GCBO)
1240 % eventdata  reserved - to be defined in a future version of MATLAB
1241 % handles    structure with handles and user data (see GUIDATA)
1242
1243
1244 % --- Executes on button press in pushbutton24.
1245 function pushbutton24_Callback(hObject, eventdata, handles)
1246 % hObject    handle to pushbutton24 (see GCBO)
1247 % eventdata  reserved - to be defined in a future version of MATLAB
1248 % handles    structure with handles and user data (see GUIDATA)
1249
1250
1251 % --- Executes on button press in pushbutton25.
1252 function pushbutton25_Callback(hObject, eventdata, handles)
1253 % hObject    handle to pushbutton25 (see GCBO)
1254 % eventdata  reserved - to be defined in a future version of MATLAB
1255 % handles    structure with handles and user data (see GUIDATA)
1256
1257
1258 % --- Executes during object creation, after setting all properties.
1259 function AnalyzeFile_CreateFcn(hObject, eventdata, handles)
1260 % hObject    handle to AnalyzeFile (see GCBO)
1261 % eventdata  reserved - to be defined in a future version of MATLAB
1262 % handles    empty - handles not created until after all CreateFcns called
1263
1264 set(hObject,'tooltipstring','Choose an Analysis File to run analyses on selected data file(s)');
1265 guidata(hObject,handles);
1266
1267 % --- Executes during object creation, after setting all properties.
1268 function LoadFile_CreateFcn(hObject, eventdata, handles)
1269 % hObject    handle to LoadFile (see GCBO)
1270 % eventdata  reserved - to be defined in a future version of MATLAB
1271 % handles    empty - handles not created until after all CreateFcns called
1272
1273 set(hObject,'tooltipstring','Load (Multiple) Data File(s) Here');
1274 guidata(hObject,handles);
1275
1276
1277 % --- Executes during object creation, after setting all properties.
1278 function AddAnalysisFileButton_CreateFcn(hObject, eventdata, handles)
1279 % hObject    handle to AddAnalysisFileButton (see GCBO)
1280 % eventdata  reserved - to be defined in a future version of MATLAB
1281 % handles    empty - handles not created until after all CreateFcns called
1282
1283 %set(hObject,'tooltipstring','Add Analysis Files to the Popup Menu');
1284 guidata(hObject,handles);
1285
1286 %
1287 % % --- Executes during object creation, after setting all properties.
1288 % function LoadGraphics_CreateFcn(hObject, eventdata, handles)
1289 % % hObject    handle to LoadGraphics (see GCBO)
1290 % % eventdata  reserved - to be defined in a future version of MATLAB
1291 % % handles    empty - handles not created until after all CreateFcns called
1292 %
1293 % set(hObject,'tooltipstring',sprintf('Click here to load saved graphics objects\nTitles will be loaded as well'));
1294 % guidata(hObject,handles);
1295
1296
1297 % --- Executes on button press in DeleteLoadedFiles.
1298 function DeleteLoadedFiles_Callback(hObject, eventdata, handles)
1299 % hObject    handle to DeleteLoadedFiles (see GCBO)
1300 % eventdata  reserved - to be defined in a future version of MATLAB
1301 % handles    structure with handles and user data (see GUIDATA)
1302
1303  LoadedFileList=get(handles.LoadedFiles,'string');
1304  if ~iscell(LoadedFileList) && strcmp(LoadedFileList,'LoadedFiles')
1305      TellMe('%s\n','Nothing to delete !!',handles.SpeakToMe);
1306  else
1307  if ~iscell(LoadedFileList), TempVar{1}=LoadedFileList; LoadedFileList=TempVar;end
1308  CurrentValue=get(handles.LoadedFiles,'value');
1309  FilesToDelete=LoadedFileList(CurrentValue);
1310
1311  set(handles.LoadedFiles,'listboxtop',1);
1312
1313  for TempVar=1:length(FilesToDelete)
1314      eval(['handles=rmfield(handles,''' FilesToDelete{TempVar} ''');']);
1315      fprintf('%s\n',['Deleted  ' FilesToDelete{TempVar}]);
1316          end
1317
1318  FilesToKeep=setdiff(1:length(LoadedFileList),CurrentValue);
1319  if isempty(FilesToKeep), LoadedFileList='LoadedFiles'; else LoadedFileList=LoadedFileList(FilesToKeep);end
1320 set(handles.LoadedFiles,'string',(LoadedFileList),'value',1);
1321
1322 fprintf('%s',sprintf('If there are graphics objects\n that depend on these files,\n then if you try to update axes, it will fail\n'));
1323 fprintf('%s\n','ALSO: this step takes time because a copy of handles is created and modified. May also screw up memory. WAIT for loaded files to appear, if you are deleting a LOT of files');
1324
1325 guidata(hObject,handles);
1326  end
1327
1328 % --- Executes during object creation, after setting all properties.
1329 function DeleteLoadedFiles_CreateFcn(hObject, eventdata, handles)
1330 % hObject    handle to DeleteLoadedFiles (see GCBO)
1331 % eventdata  reserved - to be defined in a future version of MATLAB
1332 % handles    empty - handles not created until after all CreateFcns called
1333
1334 set(hObject,'tooltipstring','Delete Loaded Data Files (Trials and Analysis)');
1335 guidata(hObject,handles);
1336
1337
1338
1339 % --- Executes during object creation, after setting all properties.
1340 function axes1_CreateFcn(hObject, eventdata, handles)
1341 % hObject    handle to axes1 (see GCBO)
1342 % eventdata  reserved - to be defined in a future version of MATLAB
1343 % handles    empty - handles not created until after all CreateFcns called
1344
1345 % Hint: place code in OpeningFcn to populate axes1
1346
1347 hold on;
1348
1349
1350 % --- Executes during object creation, after setting all properties.
1351 function axes2_CreateFcn(hObject, eventdata, handles)
1352 % hObject    handle to axes2 (see GCBO)
1353 % eventdata  reserved - to be defined in a future version of MATLAB
1354 % handles    empty - handles not created until after all CreateFcns called
1355
1356 % Hint: place code in OpeningFcn to populate axes2
1357
1358
1359 hold on;
1360
1361
1362 % --- Executes during object creation, after setting all properties.
1363 function axes3_CreateFcn(hObject, eventdata, handles)
1364 % hObject    handle to axes3 (see GCBO)
1365 % eventdata  reserved - to be defined in a future version of MATLAB
1366 % handles    empty - handles not created until after all CreateFcns called
1367
1368 % Hint: place code in OpeningFcn to populate axes3
1369
1370 hold on;
1371
1372
1373
1374 % --- Executes during object creation, after setting all properties.
1375 function axes4_CreateFcn(hObject, eventdata, handles)
1376 % hObject    handle to axes4 (see GCBO)
1377 % eventdata  reserved - to be defined in a future version of MATLAB
1378 % handles    empty - handles not created until after all CreateFcns called
1379
1380 % Hint: place code in OpeningFcn to populate axes4
1381 hold on;
1382
1383
1384
1385 % --- Executes during object creation, after setting all properties.
1386 function axes5_CreateFcn(hObject, eventdata, handles)
1387 % hObject    handle to axes5 (see GCBO)
1388 % eventdata  reserved - to be defined in a future version of MATLAB
1389 % handles    empty - handles not created until after all CreateFcns called
1390
1391 % Hint: place code in OpeningFcn to populate axes5
1392
1393 hold on;
1394
1395
1396 % --- Executes during object creation, after setting all properties.
1397 function axes6_CreateFcn(hObject, eventdata, handles)
1398 % hObject    handle to axes6 (see GCBO)
1399 % eventdata  reserved - to be defined in a future version of MATLAB
1400 % handles    empty - handles not created until after all CreateFcns called
1401
1402 % Hint: place code in OpeningFcn to populate axes6
1403
1404 hold on;
1405
1406
1407 % --- Executes during object creation, after setting all properties.
1408 function axes7_CreateFcn(hObject, eventdata, handles)
1409 % hObject    handle to axes7 (see GCBO)
1410 % eventdata  reserved - to be defined in a future version of MATLAB
1411 % handles    empty - handles not created until after all CreateFcns called
1412
1413 % Hint: place code in OpeningFcn to populate axes7
1414
1415 hold on;
1416 % zoom on;
1417
1418 % --- Executes during object creation, after setting all properties.
1419 function axes8_CreateFcn(hObject, eventdata, handles)
1420 % hObject    handle to axes8 (see GCBO)
1421 % eventdata  reserved - to be defined in a future version of MATLAB
1422 % handles    empty - handles not created until after all CreateFcns called
1423
1424 % Hint: place code in OpeningFcn to populate axes8
1425
1426 hold on;
1427
1428
1429 % --- Executes during object creation, after setting all properties.
1430 function axes9_CreateFcn(hObject, eventdata, handles)
1431 % hObject    handle to axes9 (see GCBO)
1432 % eventdata  reserved - to be defined in a future version of MATLAB
1433 % handles    empty - handles not created until after all CreateFcns called
1434
1435 % Hint: place code in OpeningFcn to populate axes9
1436
1437 hold on;
1438
1439 % --- Executes during object creation, after setting all properties.
1440 function text30_CreateFcn(hObject, eventdata, handles)
1441 % hObject    handle to text30 (see GCBO)
1442 % eventdata  reserved - to be defined in a future version of MATLAB
1443 % handles    empty - handles not created until after all CreateFcns called
1444
1445 set(hObject,'tooltipstring',sprintf('Enter the in-RF location here\n[x y]\nVariable is CurrentRF'));
1446 guidata(hObject,handles);
1447
1448
1449
1450 % --- Executes during object creation, after setting all properties.
1451 function SaveGraphics_CreateFcn(hObject, eventdata, handles)
1452 % hObject    handle to SaveGraphics (see GCBO)
1453 % eventdata  reserved - to be defined in a future version of MATLAB
1454 % handles    empty - handles not created until after all CreateFcns called
1455 % Only on because other buttons somehow have this as their "dud" create
1456 % function
1457
1458 guidata(hObject,handles);
1459
1460
1461
1462 % --- Executes during object creation, after setting all properties.
1463 function UpdateTheseAxes_CreateFcn(hObject, eventdata, handles)
1464 % hObject    handle to UpdateTheseAxes (see GCBO)
1465 % eventdata  reserved - to be defined in a future version of MATLAB
1466 % handles    empty - handles not created until after all CreateFcns called
1467
1468 set(hObject,'tooltipstring',sprintf('Remember: to keep current filter inactive\n,set it to empty. Easy to miss'));
1469 guidata(hObject,handles);
1470
1471
1472 % --- Executes on selection change in AlignCode.
1473 function AlignCode_Callback(hObject, eventdata, handles)
1474 % hObject    handle to AlignCode (see GCBO)
1475 % eventdata  reserved - to be defined in a future version of MATLAB
1476 % handles    structure with handles and user data (see GUIDATA)
1477
1478 % Hints: contents = get(hObject,'String') returns AlignCode contents as cell array
1479 %        contents{get(hObject,'Value')} returns selected item from AlignCode
1480
1481 ThingsToDo=get(handles.WhatToDo,'String');
1482 WhatToDo=ThingsToDo{get(handles.WhatToDo,'value')};
1483
1484 if strcmp(WhatToDo,'ActiveUpdate'),
1485 UpdateType='Align';
1486 UpdateSlider;
1487 end
1488
1489 guidata(hObject,handles);
1490
1491 % --- Executes during object creation, after setting all properties.
1492 function AlignCode_CreateFcn(hObject, eventdata, handles)
1493 % hObject    handle to AlignCode (see GCBO)
1494 % eventdata  reserved - to be defined in a future version of MATLAB
1495 % handles    empty - handles not created until after all CreateFcns called
1496
1497 % Hint: popupmenu controls usually have a white background on Windows.
1498 %       See ISPC and COMPUTER.
1499 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1500     set(hObject,'BackgroundColor','white');
1501 end
1502
1503
1504 % --------------------------------------------------------------------
1505 function ClearAxes_Callback(hObject, eventdata, handles)
1506 % hObject    handle to ClearAxes (see GCBO)
1507 % eventdata  reserved - to be defined in a future version of MATLAB
1508 % handles    structure with handles and user data (see GUIDATA)
1509
1510 hold off; cla;
1511 set(gca,'xlim',[-inf inf],'ylim',[-inf inf]);
1512 ClearGObjects;
1513
1514 AxesList=handles.HandlesList;
1515 AxisNum=find(gca==AxesList);
1516
1517 UnlinkTheseAxes;
1518 UndefineAxisVars;
1519
1520 guidata(hObject,handles);
1521
1522
1523
1524
1525 % --------------------------------------------------------------------
1526 function General_Callback(hObject, eventdata, handles)
1527 % hObject    handle to FTPFile (see GCBO)
1528 % eventdata  reserved - to be defined in a future version of MATLAB
1529 % handles    structure with handles and user data (see GUIDATA)
1530
1531
1532
1533 % --------------------------------------------------------------------
1534 function GetInsideMe_Callback(hObject, eventdata, handles)
1535 % hObject    handle to GetInsideMe (see GCBO)
1536 % eventdata  reserved - to be defined in a future version of MATLAB
1537 % handles    structure with handles and user data (see GUIDATA)
1538
1539 keyboard;
1540
1541
1542 % --------------------------------------------------------------------
1543 function FTPFile_Callback(hObject, eventdata, handles)
1544 % hObject    handle to FTPFile (see GCBO)
1545 % eventdata  reserved - to be defined in a future version of MATLAB
1546 % handles    structure with handles and user data (see GUIDATA)
1547
1548 if isfield(handles,'FTP')
1549
1550 FileToFTP=[handles.FTP.pathname handles.FTP.filename];
1551 FTPDir='c:\MATLAB\work\physiology';
1552
1553 if isfield(handles,'CurrentDataDirectory'), cd(handles.CurrentDataDirectory);end
1554
1555 eval(['!ncftpget -f ' handles.XeXDir '\assorted\pwf ', FTPDir,' ',FileToFTP 'A ' FileToFTP 'E']);
1556 fprintf('%s\n',['IF NCFTP REPORTED NO ERRORS, File downloaded to   ' pwd]);
1557
1558 FTPLoadFileStuff;
1559
1560 else
1561     TellMe('%s\n','Enter the FTP options first',handles.SpeakToMe);
1562 end
1563
1564 % --------------------------------------------------------------------
1565 function ClearAll_Callback(hObject, eventdata, handles)
1566 % hObject    handle to ClearAll (see GCBO)
1567 % eventdata  reserved - to be defined in a future version of MATLAB
1568 % handles    structure with handles and user data (see GUIDATA)
1569
1570
1571 for TempVar=1:(handles.NumberOfAxes)
1572     eval(['axes(handles.axes' num2str(TempVar) ');']);
1573     cla; hold off; set(gca,'xlim',[-inf inf],'ylim',[-inf inf]);
1574 eval(['if isfield(handles,''A' num2str(TempVar) '''), handles=rmfield(handles,''A' num2str(TempVar) ''');end']);
1575 end
1576
1577 AxisNum=1:12;
1578 UnlinkTheseAxes;
1579 UndefineAxisVars;
1580
1581 guidata(hObject,handles);
1582
1583 % --------------------------------------------------------------------
1584 function PlotEdit_Callback(hObject, eventdata, handles)
1585 % hObject    handle to PlotEdit (see GCBO)
1586 % eventdata  reserved - to be defined in a future version of MATLAB
1587 % handles    structure with handles and user data (see GUIDATA)
1588
1589
1590 if strcmp(get(hObject,'Checked'),'off') set(hObject,'checked','on'); plotedit('on');
1591 else set(hObject,'Checked','off'); plotedit('off');
1592 end
1593 guidata(hObject,handles);
1594
1595
1596 % --------------------------------------------------------------------
1597 function AnnotateAxis_Callback(hObject, eventdata, handles)
1598 % hObject    handle to AnnotateAxis (see GCBO)
1599 % eventdata  reserved - to be defined in a future version of MATLAB
1600 % handles    structure with handles and user data (see GUIDATA)
1601
1602
1603 AxesHandles=nan*ones(1,handles.NumberOfAxes);
1604
1605 for TempVar=1:(handles.NumberOfAxes)
1606    eval([' AxesHandles(TempVar)=handles.axes' num2str(TempVar) ';']);
1607 end
1608
1609 CurrentAxisHandle=gca;
1610
1611 WhichAxis=find(AxesHandles==CurrentAxisHandle);
1612
1613 estring=(['if isfield(handles,''A' num2str(WhichAxis) 'Annotations''), danswer=handles.A' num2str(WhichAxis) 'Annotations; else danswer={'''','''',''''};end']);
1614 %     else danswer={''Axis' num2str(WhichAxis) ''',''X Label'',''Y Label'' };end']);
1615 %    keyboard;
1616    eval(estring);
1617     danswer{4}=num2str(get(gca,'xlim'));
1618     danswer{5}=num2str(get(gca,'ylim'));
1619
1620    prompt={'Enter axis title','Enter X label' 'Enter Y label','Enter X Lim', 'Enter Y Lim'};
1621    name=['Annotate Axis ' num2str(WhichAxis)];
1622    numlines=1;
1623    defaultanswer=danswer;
1624
1625    answer=inputdlg(prompt,name,numlines,defaultanswer);
1626
1627
1628    if ~isempty(answer)
1629    title(answer{1});
1630    xlabel(answer{2});
1631    ylabel(answer{3});
1632    set(gca,'xlim',str2num(answer{4}));
1633    set(gca,'ylim',str2num(answer{5}));
1634
1635    eval(['handles.A' num2str(WhichAxis) 'Annotations=answer;']);
1636
1637    end
1638
1639    guidata(hObject,handles);
1640
1641 function UnitNumber_Callback(hObject, eventdata, handles)
1642 % hObject    handle to UnitNumber (see GCBO)
1643 % eventdata  reserved - to be defined in a future version of MATLAB
1644 % handles    structure with handles and user data (see GUIDATA)
1645
1646 % Hints: get(hObject,'String') returns contents of UnitNumber as text
1647 %        str2double(get(hObject,'String')) returns contents of UnitNumber as a double
1648
1649
1650 % --- Executes during object creation, after setting all properties.
1651 function UnitNumber_CreateFcn(hObject, eventdata, handles)
1652 % hObject    handle to UnitNumber (see GCBO)
1653 % eventdata  reserved - to be defined in a future version of MATLAB
1654 % handles    empty - handles not created until after all CreateFcns called
1655
1656 % Hint: edit controls usually have a white background on Windows.
1657 %       See ISPC and COMPUTER.
1658 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1659     set(hObject,'BackgroundColor','white');
1660 end
1661
1662
1663
1664
1665 % --------------------------------------------------------------------
1666 function SetDataDirectory_Callback(hObject, eventdata, handles)
1667 % hObject    handle to SetDataDirectory (see GCBO)
1668 % eventdata  reserved - to be defined in a future version of MATLAB
1669 % handles    structure with handles and user data (see GUIDATA)
1670
1671 TempDir=uigetdir(handles.CurrentDataDirectory,'Set Data Directory');
1672 if ~isequal(TempDir,0)
1673     handles.CurrentDataDirectory=TempDir;
1674 end
1675
1676 guidata(hObject,handles);
1677
1678 % --- Executes on button press in GetVariables.
1679 function GetVariables_Callback(hObject, eventdata, handles)
1680 % hObject    handle to GetVariables (see GCBO)
1681 % eventdata  reserved - to be defined in a future version of MATLAB
1682 % handles    structure with handles and user data (see GUIDATA)
1683
1684
1685  LoadedFileList=get(handles.LoadedFiles,'string');
1686  if ~iscell(LoadedFileList), TempVar{1}=LoadedFileList; LoadedFileList=TempVar;end
1687  CurrentValue=get(handles.LoadedFiles,'value'); CurrentValue=CurrentValue(1);
1688  CurrentDataFile=LoadedFileList{CurrentValue};
1689
1690 if ~strcmp(CurrentDataFile,'LoadedFiles')
1691
1692 eval(['Trials=handles.' CurrentDataFile '.Trials;']);
1693 eval(['if ~isfield(handles.' CurrentDataFile ',''Analysis''), fprintf(''%s\n'',''Analyze your dataset first''); GoOn=0;else GoOn=1;end']);
1694 %eval(['if GoOn==1, CurrentVariables=handles.' CurrentDataFile '.Analysis;end']);
1695 eval(['if GoOn==1, MyVariableList=handles.' CurrentDataFile '.Analysis.MyVariableList;end']);
1696 % eval(['if GoOn==1, MyResponseVariableList=handles.' CurrentDataFile '.Analysis.MyResponseVariableList;end']);
1697
1698 %detachvars;
1699
1700 msgbox(MyVariableList,'Variable List','help');
1701 set(gcf,'CloseRequestFcn','TellMe(''%s\n'',''Hit OK. You cannot close this box like that.'',handles.SpeakToMe)');
1702
1703
1704 else TellMe('%s\n','Make sure you have selected a data file and a plotting file',handles.SpeakToMe);
1705 end
1706
1707 % --- Executes on button press in LaunchViewer.
1708 function LaunchViewer_Callback(hObject, eventdata, handles)
1709 % hObject    handle to LaunchViewer (see GCBO)
1710 % eventdata  reserved - to be defined in a future version of MATLAB
1711 % handles    structure with handles and user data (see GUIDATA)
1712
1713 LoadedFileList=get(handles.LoadedFiles,'string');
1714 CurrentValues=get(handles.LoadedFiles,'value');
1715 if length(CurrentValues)>0 & iscell(LoadedFileList)
1716 CurrentFile=LoadedFileList{CurrentValues(1)};
1717 else
1718     CurrentFile=LoadedFileList;
1719 end
1720
1721 if ~strcmp(CurrentFile,'LoadedFiles')
1722         eval(['Trials=handles.' CurrentFile '.Trials;']);
1723         setappdata(0,'SaccadeOptions',handles.SaccadeOptions);
1724         setappdata(0,'ViewTrials',Trials);
1725 %         CellToPass=cell(1,4);
1726 %         CellToPass{1}=handles.SaccadeOptions.CorrectCode;
1727 %         CellToPass{2}=handles.SaccadeOptions.ISICut;
1728 %         CellToPass{3}=handles.SaccadeOptions.MinLat;
1729 %         CellToPass{4}=handles.SaccadeOptions.Threshold;
1730 %         TrialViewer(Trials,CellToPass);
1731         TrialViewer;
1732 else
1733     TellMe('%s\n','Choose a data file first',handles.SpeakToMe);
1734
1735 end
1736
1737
1738 % --------------------------------------------------------------------
1739 function BrowseFTP_Callback(hObject, eventdata, handles)
1740 % hObject    handle to BrowseFTP (see GCBO)
1741 % eventdata  reserved - to be defined in a future version of MATLAB
1742 % handles    structure with handles and user data (see GUIDATA)
1743
1744 ftpsurf;
1745
1746 % % --- Executes on button press in SetAxisVariables.
1747 % function SetAxisVariables_Callback(hObject, eventdata, handles)
1748 % % hObject    handle to SetAxisVariables (see GCBO)
1749 % % eventdata  reserved - to be defined in a future version of MATLAB
1750 % % handles    structure with handles and user data (see GUIDATA)
1751 %
1752 %  LoadedFileList=get(handles.LoadedFiles,'string');
1753 %  if ~iscell(LoadedFileList), TempVar{1}=LoadedFileList; LoadedFileList=TempVar;end
1754 %  CurrentValue=get(handles.LoadedFiles,'value'); CurrentValue=CurrentValue(1);
1755 %  CurrentDataFile=LoadedFileList{CurrentValue};
1756 %
1757 % if ~strcmp(CurrentDataFile,'LoadedFiles')
1758 %
1759 % eval(['Trials=handles.' CurrentDataFile '.Trials;']);
1760 % eval(['if ~isfield(handles.' CurrentDataFile ',''Analysis''), fprintf(''%s\n'',''Analyze your dataset first''); GoOn=0;else GoOn=1;end']);
1761 % %eval(['if GoOn==1, CurrentVariables=handles.' CurrentDataFile '.Analysis;end']);
1762 % eval(['if GoOn==1, MyVariableList=handles.' CurrentDataFile '.Analysis.MyVariableList; MyResponseVariableList=handles.' CurrentDataFile '.Analysis.MyResponseVariableList;end']);
1763 %
1764 % if ~iscell(MyVariableList), TemporaryVariable{1}=MyVariableList; MyVariableList=TemporaryVariable; clear TemporaryVariable; end
1765 % if ~iscell(MyResponseVariableList), MyResponseVariableList=cellstr(MyResponseVariableList);end
1766 %
1767 % MyVariableChoices=EnterAxisVariables(MyVariableList,MyResponseVariableList,handles.MyVariableChoices);
1768 % if MyVariableChoices.OK==1
1769 %     handles.MyVariableChoices=MyVariableChoices;
1770 % end
1771 %
1772 % % [TwoDX,TempOK]=listdlg('PromptString','Select X variable for 2D map','SelectionMode','single','ListString',MyVariableList);
1773 % % if TempOK==1, handles.TwoDXVar=MyVariableList{TwoDX}; end
1774 % %
1775 % %
1776 % % [TwoDY,TempOK]=listdlg('PromptString','Select Y variable for 2D map','SelectionMode','single','ListString',MyVariableList);
1777 % % if TempOK==1, handles.TwoDYVar=MyVariableList{TwoDY}; end
1778 %
1779 % else TellMe('%s\n','Make sure you have selected a data file and a plotting file',handles.SpeakToMe);
1780 % end
1781 %
1782 % guidata(hObject,handles);
1783
1784
1785 % --- Executes during object creation, after setting all properties.
1786 function edit27_CreateFcn(hObject, eventdata, handles)
1787 % hObject    handle to edit27 (see GCBO)
1788 % eventdata  reserved - to be defined in a future version of MATLAB
1789 % handles    empty - handles not created until after all CreateFcns called
1790
1791 % Hint: edit controls usually have a white background on Windows.
1792 %       See ISPC and COMPUTER.
1793 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1794     set(hObject,'BackgroundColor','white');
1795 end
1796
1797
1798 % --- Executes on button press in ExportGraphics.
1799 function ExportGraphics_Callback(hObject, eventdata, handles)
1800 % hObject    handle to ExportGraphics (see GCBO)
1801 % eventdata  reserved - to be defined in a future version of MATLAB
1802 % handles    structure with handles and user data (see GUIDATA)
1803
1804 ExportGFX;
1805
1806
1807 % --- Executes on button press in ExploreVariables.
1808 function ExploreVariables_Callback(hObject, eventdata, handles)
1809 % hObject    handle to ExploreVariables (see GCBO)
1810 % eventdata  reserved - to be defined in a future version of MATLAB
1811 % handles    structure with handles and user data (see GUIDATA)
1812
1813
1814  LoadedFileList=get(handles.LoadedFiles,'string');
1815  if ~iscell(LoadedFileList), TempVar{1}=LoadedFileList; LoadedFileList=TempVar;end
1816  CurrentValue=get(handles.LoadedFiles,'value'); CurrentValue=CurrentValue(1);
1817  CurrentDataFile=LoadedFileList{CurrentValue};
1818
1819 if ~strcmp(CurrentDataFile,'LoadedFiles')
1820
1821 eval(['Trials=handles.' CurrentDataFile '.Trials;']);
1822 eval(['if ~isfield(handles.' CurrentDataFile ',''Analysis''), fprintf(''%s\n'',''Analyze your dataset first''); GoOn=0;else GoOn=1;end']);
1823 eval(['if GoOn==1, MyVariableList=handles.' CurrentDataFile '.Analysis.MyVariableList;end']);
1824 eval(['if GoOn==1, MyResponseVariableList=handles.' CurrentDataFile '.Analysis.MyResponseVariableList;end']);
1825 %
1826 % msgbox(MyVariableList,'Variable List','help');
1827
1828 eval(['if GoOn==1, CurrentVariables=handles.' CurrentDataFile '.Analysis;end']);
1829 detachvars;
1830 if exist('CurrentVariables','var'), clear CurrentVariables;end  %***newly added to clear off possible big structure from workspace.
1831 keyboard;
1832 % clearvars;  %**************************** removed this as well as it is
1833                       %% superfluous, i think
1834
1835 else TellMe('%s\n','Make sure you have selected a data file and a plotting file',handles.SpeakToMe);
1836 end
1837
1838 % --- Executes on button press in UseAxisVars.
1839 function UseAxisVars_Callback(hObject, eventdata, handles)
1840 % hObject    handle to UseAxisVars (see GCBO)
1841 % eventdata  reserved - to be defined in a future version of MATLAB
1842 % handles    structure with handles and user data (see GUIDATA)
1843
1844 % Hint: get(hObject,'Value') returns toggle state of UseAxisVars
1845
1846
1847 % --- Executes on button press in AddVariable.
1848 function AddVariable_Callback(hObject, eventdata, handles)
1849 % hObject    handle to AddVariable (see GCBO)
1850 % eventdata  reserved - to be defined in a future version of MATLAB
1851 % handles    structure with handles and user data (see GUIDATA)
1852
1853
1854 LoadedFileList=get(handles.LoadedFiles,'string');
1855  if ~iscell(LoadedFileList), TempVar{1}=LoadedFileList; LoadedFileList=TempVar;end
1856  CurrentValue=get(handles.LoadedFiles,'value'); CurrentValue=CurrentValue(1);
1857  CurrentDataFile=LoadedFileList{CurrentValue};
1858
1859 if ~strcmp(CurrentDataFile,'LoadedFiles')
1860
1861 eval(['Trials=handles.' CurrentDataFile '.Trials;']);
1862 eval(['if ~isfield(handles.' CurrentDataFile ',''Analysis''), fprintf(''%s\n'',''Analyze your dataset first''); GoOn=0;else GoOn=1;end']);
1863 eval(['if GoOn==1, MyVariableList=handles.' CurrentDataFile '.Analysis.MyVariableList;end']);
1864 eval(['if GoOn==1, MyResponseVariableList=handles.' CurrentDataFile '.Analysis.MyResponseVariableList;end']);
1865 eval(['if GoOn==1, CurrentVariables=handles.' CurrentDataFile '.Analysis;end']);
1866 detachvars;
1867
1868 if(GoOn==1),
1869   prompt={'Enter Expression for New Variable. If you want to modify a variable: trick is <varname=statement>; <other statements acting on varname>; varname will be saved !!'};
1870    name='Add New Variable ';
1871    numlines=1;
1872    defaultanswer={''};
1873
1874    Answer=inputdlg(prompt,name,numlines,defaultanswer);
1875
1876    if ~isempty(Answer)
1877 try,
1878 if iscell(Answer),    Answer=Answer{1};end
1879     eval(Answer);
1880     CutoffMark=strfind(Answer,'=');
1881     if ~isempty(CutoffMark),
1882         AddedVariableString=Answer(1:(CutoffMark-1));
1883         TellMe('%s\n',['Just calculated   ' AddedVariableString],handles.SpeakToMe);
1884     end
1885
1886   eval(['CurrentVariables.' AddedVariableString '=' AddedVariableString '; CurrentVariables.MyVariableList{length(CurrentVariables.MyVariableList)+1}=''' AddedVariableString ''';handles.' CurrentDataFile '.Analysis=CurrentVariables;']);
1887 %     eval(['CurrentVariables.' AddedVariableString '=' AddedVariableString '; CurrentVariables.MyVariableList{length(CurrentVariables.MyVariableList)+1}=''' AddedVariableString ''';CurrentVariables.MyResponseVariableList{length(CurrentVariables.MyResponseVariableList)+1}=''' AddedVariableString ''';handles.' CurrentDataFile '.Analysis=CurrentVariables;']);
1888
1889 catch,
1890     fprintf('%s\n','That expression is wrong, for some reason; check again');
1891 end  % closes the try
1892    else fprintf('%s\n','OK, cancelled !');
1893    end % closes the ~isempty(answer) loop
1894 clearvars;
1895 % ShowSlider;
1896 guidata(hObject,handles);
1897    end
1898
1899 else TellMe('%s\n','Make sure you have selected a data file and a plotting file',handles.SpeakToMe);
1900 end
1901
1902
1903
1904 % --------------------------------------------------------------------
1905 function SpikeTruncate_Callback(hObject, eventdata, handles)
1906 % hObject    handle to SpikeTruncate (see GCBO)
1907 % eventdata  reserved - to be defined in a future version of MATLAB
1908 % handles    structure with handles and user data (see GUIDATA)
1909
1910 if strcmp(get(hObject,'Checked'),'off') set(hObject,'checked','on');
1911 else set(hObject,'Checked','off');
1912 end
1913 guidata(hObject,handles);
1914
1915
1916
1917 % --------------------------------------------------------------------
1918 function ClearPolar_Callback(hObject, eventdata, handles)
1919 % hObject    handle to ClearPolar (see GCBO)
1920 % eventdata  reserved - to be defined in a future version of MATLAB
1921 % handles    structure with handles and user data (see GUIDATA)
1922
1923   prompt={'Enter Polar Axis'};
1924    name='Clear Polar ';
1925    numlines=1;
1926    defaultanswer={''};
1927
1928    Answer=inputdlg(prompt,name,numlines,defaultanswer);
1929
1930    if ~isempty(Answer)
1931
1932 if iscell(Answer),    Answer=Answer{1};end
1933
1934 AxisNum=str2num(Answer);
1935
1936 for index=1:length(AxisNum)
1937     CurAx=num2str(AxisNum(index));
1938     eval(['Pos=get(handles.axes' CurAx ',''position'');']);
1939     eval(['CurContext=get(handles.axes' CurAx ',''uicontextmenu'');']);
1940     eval(['delete(handles.axes' CurAx ');']);
1941     eval(['handles.axes' CurAx '=axes;']);
1942     eval(['set(handles.axes' CurAx,',''units'',''normalized'',''position'',Pos,''uicontextmenu'',CurContext);']);
1943 end
1944
1945 UnlinkTheseAxes;
1946 UndefineAxisVars;
1947 guidata(hObject,handles);
1948    end
1949
1950
1951 % % --- Executes on slider movement.
1952 % function UpdateSlider_Callback(hObject, eventdata, handles)
1953 % % hObject    handle to UpdateSlider (see GCBO)
1954 % % eventdata  reserved - to be defined in a future version of MATLAB
1955 % % handles    structure with handles and user data (see GUIDATA)
1956 %
1957 % % Hints: get(hObject,'Value') returns position of slider
1958 % %        get(hObject,'Min') and get(hObject,'Max') to determine range of slider
1959 %
1960 % % BackupGraphs;
1961 %
1962 % CurrentValue=get(hObject,'Value');
1963 % set(handles.SliderText,'String',['SV =',num2str(CurrentValue)]);
1964 % ThingsToDo=get(handles.WhatToDo,'String');
1965 % WhatToDo=ThingsToDo{get(handles.WhatToDo,'value')};
1966 %
1967 % if strcmp(WhatToDo,'ActiveUpdate'),
1968 % UpdateType='slider';
1969 % UpdateSlider;
1970 % end
1971 %
1972 % guidata(hObject,handles);
1973 %
1974 % % --- Executes during object creation, after setting all properties.
1975 % function UpdateSlider_CreateFcn(hObject, eventdata, handles)
1976 % % hObject    handle to UpdateSlider (see GCBO)
1977 % % eventdata  reserved - to be defined in a future version of MATLAB
1978 % % handles    empty - handles not created until after all CreateFcns called
1979 %
1980 % % Hint: slider controls usually have a light gray background.
1981 % if isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1982 %     set(hObject,'BackgroundColor',[.9 .9 .9]);
1983 % end
1984
1985
1986 % --------------------------------------------------------------------
1987 function GetObjectAxes_Callback(hObject, eventdata, handles)
1988 % hObject    handle to GetObjectAxes (see GCBO)
1989 % eventdata  reserved - to be defined in a future version of MATLAB
1990 % handles    structure with handles and user data (see GUIDATA)
1991
1992 % Hints: get(hObject,'String') returns contents of GetObjectAxes as text
1993 %        str2double(get(hObject,'String')) returns contents of GetObjectAxes as a double
1994
1995
1996 % --- Executes during object creation, after setting all properties.
1997 function GetObjectAxes_CreateFcn(hObject, eventdata, handles)
1998 % hObject    handle to GetObjectAxes (see GCBO)
1999 % eventdata  reserved - to be defined in a future version of MATLAB
2000 % handles    empty - handles not created until after all CreateFcns called
2001
2002 % Hint: edit controls usually have a white background on Windows.
2003 %       See ISPC and COMPUTER.
2004 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
2005     set(hObject,'BackgroundColor','white');
2006 end
2007
2008 % --------------------------------------------------------------------
2009 function ObjectNumber_Callback(hObject, eventdata, handles)
2010 % hObject    handle to ObjectNumber (see GCBO)
2011 % eventdata  reserved - to be defined in a future version of MATLAB
2012 % handles    structure with handles and user data (see GUIDATA)
2013
2014 % Hints: get(hObject,'String') returns contents of ObjectNumber as text
2015 %        str2double(get(hObject,'String')) returns contents of ObjectNumber as a double
2016
2017
2018 % --- Executes during object creation, after setting all properties.
2019 function ObjectNumber_CreateFcn(hObject, eventdata, handles)
2020 % hObject    handle to ObjectNumber (see GCBO)
2021 % eventdata  reserved - to be defined in a future version of MATLAB
2022 % handles    empty - handles not created until after all CreateFcns called
2023
2024 % Hint: edit controls usually have a white background on Windows.
2025 %       See ISPC and COMPUTER.
2026 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
2027     set(hObject,'BackgroundColor','white');
2028 end
2029
2030 % --------------------------------------------------------------------
2031 function OldAxis_Callback(hObject, eventdata, handles)
2032 % hObject    handle to OldAxis (see GCBO)
2033 % eventdata  reserved - to be defined in a future version of MATLAB
2034 % handles    structure with handles and user data (see GUIDATA)
2035
2036 % Hints: get(hObject,'String') returns contents of OldAxis as text
2037 %        str2double(get(hObject,'String')) returns contents of OldAxis as a double
2038
2039
2040 % --- Executes during object creation, after setting all properties.
2041 function OldAxis_CreateFcn(hObject, eventdata, handles)
2042 % hObject    handle to OldAxis (see GCBO)
2043 % eventdata  reserved - to be defined in a future version of MATLAB
2044 % handles    empty - handles not created until after all CreateFcns called
2045
2046 % Hint: edit controls usually have a white background on Windows.
2047 %       See ISPC and COMPUTER.
2048 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
2049     set(hObject,'BackgroundColor','white');
2050 end
2051
2052 % --------------------------------------------------------------------
2053 function NewAxis_Callback(hObject, eventdata, handles)
2054 % hObject    handle to NewAxis (see GCBO)
2055 % eventdata  reserved - to be defined in a future version of MATLAB
2056 % handles    structure with handles and user data (see GUIDATA)
2057
2058 % Hints: get(hObject,'String') returns contents of NewAxis as text
2059 %        str2double(get(hObject,'String')) returns contents of NewAxis as a double
2060
2061
2062 % --- Executes during object creation, after setting all properties.
2063 function NewAxis_CreateFcn(hObject, eventdata, handles)
2064 % hObject    handle to NewAxis (see GCBO)
2065 % eventdata  reserved - to be defined in a future version of MATLAB
2066 % handles    empty - handles not created until after all CreateFcns called
2067
2068 % Hint: edit controls usually have a white background on Windows.
2069 %       See ISPC and COMPUTER.
2070 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
2071     set(hObject,'BackgroundColor','white');
2072 end
2073
2074
2075 % --- Executes on button press in DeleteObjects.
2076 function DeleteObjects_Callback(hObject, eventdata, handles)
2077 % hObject    handle to DeleteObjects (see GCBO)
2078 % eventdata  reserved - to be defined in a future version of MATLAB
2079 % handles    structure with handles and user data (see GUIDATA)
2080
2081
2082 CurrentAxis=str2num(get(handles.OldAxis,'string'));
2083 if isnumeric(CurrentAxis) && length(CurrentAxis)==1
2084
2085     eval(['if isfield(handles,''A' num2str(CurrentAxis) '''),CurrentObjects=handles.A' num2str(CurrentAxis) ';end,']);
2086 if exist('CurrentObjects','var')    && length(CurrentObjects)>=1
2087     ObjectsToDelete=str2num(get(handles.ObjectNumber, 'string'));
2088
2089     if max(ObjectsToDelete)<=length(CurrentObjects),
2090
2091     for Looper=1:length(ObjectsToDelete)
2092         delete(CurrentObjects(ObjectsToDelete(Looper)).handle);
2093         fprintf('%s\n',['Deleted 1 ' CurrentObjects(ObjectsToDelete(Looper)).plottype ' object from axis ' num2str(CurrentAxis)]);
2094     end
2095
2096     CurrentObjects(ObjectsToDelete)=[];
2097     eval(['handles.A' num2str(CurrentAxis) '=CurrentObjects;']);
2098
2099     else
2100         TellMe('%s\n','Cannot delete non existent objects',handles.SpeakToMe);
2101     end
2102
2103     else TellMe('%s\n','No objects to delete !!',handles.SpeakToMe);
2104     end
2105
2106 else TellMe('%s\n','Enter only 1 Axis',handles.SpeakToMe);
2107 end
2108
2109 guidata(hObject,handles);
2110
2111
2112 % --- Executes on button press in MoveObj.
2113 function MoveObj_Callback(hObject, eventdata, handles)
2114 % hObject    handle to MoveObj (see GCBO)
2115 % eventdata  reserved - to be defined in a future version of MATLAB
2116 % handles    structure with handles and user data (see GUIDATA)
2117
2118 CurrentAxis=str2num(get(handles.OldAxis,'string'));
2119 NewAxis=str2num(get(handles.NewAxis,'string'));
2120
2121 if isnumeric(CurrentAxis) && length(CurrentAxis)==1 && length(NewAxis)==1
2122
2123     if CurrentAxis~=NewAxis
2124
2125     eval(['if isfield(handles,''A' num2str(CurrentAxis) '''),CurrentObjects=handles.A' num2str(CurrentAxis) ';end,']);
2126     eval(['if isfield(handles,''A' num2str(NewAxis) '''),NewObjects=handles.A' num2str(NewAxis) ';end,']);
2127
2128     if exist('CurrentObjects','var') && length(CurrentObjects)>=1
2129     ObjectsToCopy=str2num(get(handles.ObjectNumber, 'string'));
2130
2131     if max(ObjectsToCopy)<=length(CurrentObjects),
2132
2133    TempObjects=CurrentObjects;
2134
2135     for Looper=1:length(ObjectsToCopy)
2136         eval(['Newhandle=copyobj(CurrentObjects(ObjectsToCopy(Looper)).handle,handles.axes' num2str(NewAxis) ');']);
2137         TempObjects(ObjectsToCopy(Looper)).handle=Newhandle;
2138         delete(CurrentObjects(ObjectsToCopy(Looper)).handle);  %main difference 1 from copy objects
2139         fprintf('%s\n',['Moved 1 ' CurrentObjects(ObjectsToCopy(Looper)).plottype ' object from axis ' num2str(CurrentAxis) ' to axis ' num2str(NewAxis)]);
2140     end
2141
2142     if exist('NewObjects','var'), NewObjects=[NewObjects TempObjects(ObjectsToCopy)]; else NewObjects=TempObjects(ObjectsToCopy);end
2143     eval(['handles.A' num2str(NewAxis) '=NewObjects;']);
2144
2145      CurrentObjects(ObjectsToCopy)=[];
2146 %      keyboard;
2147      if length(CurrentObjects)==0,
2148          eval(['handles=rmfield(handles,''A' num2str(CurrentAxis) ''');']);
2149      else
2150      eval(['handles.A' num2str(CurrentAxis) '=CurrentObjects;']);  %these two lines are main difference number 2 from copy objects
2151      end
2152
2153     else
2154         TellMe('%s\n','Cannot move non existent objects',handles.SpeakToMe);
2155     end
2156
2157     else TellMe('%s\n','No objects to move !!',handles.SpeakToMe);
2158     end
2159
2160     else TellMe('%s\n','Moving an object from an axis to itself is fun; I dont have to do anything',handles.SpeakToMe);
2161     end
2162
2163 else TellMe('%s\n','Enter only 1 Axis',handles.SpeakToMe);
2164 end
2165
2166 guidata(hObject,handles);
2167
2168 % --- Executes on button press in GetObjectPropsButton.
2169 function GetObjectPropsButton_Callback(hObject, eventdata, handles)
2170 % hObject    handle to GetObjectPropsButton (see GCBO)
2171 % eventdata  reserved - to be defined in a future version of MATLAB
2172 % handles    structure with handles and user data (see GUIDATA)
2173
2174 AxesToGet=str2num(get(handles.GetObjectAxes,'string'));
2175 OutputString={};
2176
2177 if isnumeric(AxesToGet) && length(AxesToGet)==1,
2178
2179     eval(['if isfield(handles,''A' num2str(AxesToGet) '''),CurrentObjects=handles.A' num2str(AxesToGet) ';end,']);
2180
2181     if exist('CurrentObjects','var')
2182         for Looper=1:length(CurrentObjects)
2183     OutputString={OutputString{:} [num2str(Looper) ':   ' CurrentObjects(Looper).plottype '   ' CurrentObjects(Looper).markerstring '   ' CurrentObjects(Looper).trialfilter]};
2184         end
2185     end
2186
2187     if isempty(OutputString), OutputString={'Nothing. Nada. Zilch. No objects here in this axis'};end
2188   msgbox(OutputString,'Objects','help');
2189     set(gcf,'CloseRequestFcn','disp(''Hit OK. You cannot close this Message Box like that.'')');
2190
2191     fprintf('%s\n','*******************************************');
2192     for TempVar=1:length(OutputString)
2193         fprintf('%s\n',OutputString{TempVar});
2194     end
2195     fprintf('%s\n','*******************************************');
2196
2197 else TellMe('%s\n','Enter only 1 axis',handles.SpeakToMe);
2198 end
2199
2200 guidata(hObject,handles);
2201
2202
2203 % --- Executes on button press in CopyObj.
2204 function CopyObj_Callback(hObject, eventdata, handles)
2205 % hObject    handle to CopyObj (see GCBO)
2206 % eventdata  reserved - to be defined in a future version of MATLAB
2207 % handles    structure with handles and user data (see GUIDATA)
2208
2209 CurrentAxis=str2num(get(handles.OldAxis,'string'));
2210 NewAxis=str2num(get(handles.NewAxis,'string'));
2211
2212 if isnumeric(CurrentAxis) && length(CurrentAxis)==1 && length(NewAxis)==1
2213
2214     eval(['if isfield(handles,''A' num2str(CurrentAxis) '''),CurrentObjects=handles.A' num2str(CurrentAxis) ';end,']);
2215     eval(['if isfield(handles,''A' num2str(NewAxis) '''),NewObjects=handles.A' num2str(NewAxis) ';end,']);
2216
2217     if exist('CurrentObjects','var') && length(CurrentObjects)>=1
2218     ObjectsToCopy=str2num(get(handles.ObjectNumber, 'string'));
2219
2220     if max(ObjectsToCopy)<=length(CurrentObjects),
2221
2222    TempObjects=CurrentObjects;
2223
2224     for Looper=1:length(ObjectsToCopy)
2225         eval(['Newhandle=copyobj(CurrentObjects(ObjectsToCopy(Looper)).handle,handles.axes' num2str(NewAxis) ');']);
2226         TempObjects(ObjectsToCopy(Looper)).handle=Newhandle;
2227         fprintf('%s\n',['Copied 1 ' CurrentObjects(ObjectsToCopy(Looper)).plottype ' object from axis ' num2str(CurrentAxis) ' to axis ' num2str(NewAxis)]);
2228     end
2229
2230     if exist('NewObjects','var'), NewObjects=[NewObjects TempObjects(ObjectsToCopy)]; else NewObjects=TempObjects(ObjectsToCopy);end
2231     eval(['handles.A' num2str(NewAxis) '=NewObjects;']);
2232
2233 %     CurrentObjects(ObjectsToDelete)=[];
2234 %     eval(['handles.A' num2str(CurrentAxis) '=CurrentObjects;']);
2235
2236     else
2237         TellMe('%s\n','Cannot copy non existent objects',handles.SpeakToMe);
2238     end
2239
2240     else TellMe('%s\n','No objects to copy !!',handles.SpeakToMe);
2241     end
2242
2243 else TellMe('%s\n','Enter only 1 Axis',handles.SpeakToMe);
2244 end
2245
2246 guidata(hObject,handles);
2247
2248
2249 % --------------------------------------------------------------------
2250 function PlotSig_Callback(hObject, eventdata, handles)
2251 % hObject    handle to PlotSig (see GCBO)
2252 % eventdata  reserved - to be defined in a future version of MATLAB
2253 % handles    structure with handles and user data (see GUIDATA)
2254
2255
2256 if strcmp(get(hObject,'Checked'),'off') set(hObject,'checked','on');
2257     else set(hObject,'Checked','off');
2258 end
2259 guidata(hObject,handles);
2260
2261 %
2262 % % --- Executes on button press in DefaultSlide.
2263 % function DefaultSlide_Callback(hObject, eventdata, handles)
2264 % % hObject    handle to DefaultSlide (see GCBO)
2265 % % eventdata  reserved - to be defined in a future version of MATLAB
2266 % % handles    structure with handles and user data (see GUIDATA)
2267 %
2268 % CurrentValue=0.04;
2269 % set(handles.UpdateSlider,'value',CurrentValue);
2270 % set(handles.SliderText,'String',['SV =',num2str(CurrentValue,'%2.2f')]);
2271 %
2272 % UpdateSlider;
2273 %
2274 % guidata(hObject,handles);
2275
2276 %
2277 % % --- Executes on button press in UndoButton.
2278 % function UndoButton_Callback(hObject, eventdata, handles)
2279 % % hObject    handle to UndoButton (see GCBO)
2280 % % eventdata  reserved - to be defined in a future version of MATLAB
2281 % % handles    structure with handles and user data (see GUIDATA)
2282 %
2283 % if isfield(handles,'OldGraphs'), TempGraphs=handles.OldGraphs; else TempGraphs=[];end
2284 %
2285 % if ~isempty(TempGraphs),
2286 %
2287 %              for TempVar=1:(handles.NumberOfAxes)
2288 %                  NStr=num2str(TempVar);
2289 %
2290 %                  LocalTempEvalString=['if isfield(TempGraphs,''A' NStr '''),'...
2291 %                      'TempLen=length(TempGraphs.A' NStr ');'...
2292 %                      'for indica=1:TempLen, TempGraphs.A' NStr '(indica).newgraph=1;end,'...
2293 %                      'handles.A' NStr '=TempGraphs.A' NStr ';end,'...
2294 %                  ];
2295 %                  eval(LocalTempEvalString);
2296 %                  clear LocalTempEvalString;
2297 %              end
2298 %
2299 % LoadGFXVar=1;
2300 % UpdateCellOrLoadGFX;
2301 % guidata(hObject,handles);
2302 %
2303 % else TellMe('%s\n','Nothing to undo. Sorry',handles.SpeakToMe);
2304 % end
2305
2306 % % --- Executes on button press in BackupButton.
2307 % function BackupButton_Callback(hObject, eventdata, handles)
2308 % % hObject    handle to BackupButton (see GCBO)
2309 % % eventdata  reserved - to be defined in a future version of MATLAB
2310 % % handles    structure with handles and user data (see GUIDATA)
2311 %
2312 % BackupGraphs;
2313 % guidata(hObject,handles);
2314
2315
2316 % --------------------------------------------------------------------
2317 function SpeakToMeMenu_Callback(hObject, eventdata, handles)
2318 % hObject    handle to SpeakToMeMenu (see GCBO)
2319 % eventdata  reserved - to be defined in a future version of MATLAB
2320 % handles    structure with handles and user data (see GUIDATA)
2321
2322
2323 if strcmp(get(hObject,'Checked'),'off') set(hObject,'checked','on'); handles.SpeakToMe=1;
2324 else set(hObject,'Checked','off'); handles.SpeakToMe=0;
2325 end
2326
2327 guidata(hObject,handles);
2328
2329
2330 % --------------------------------------------------------------------
2331 function MainStuff_Callback(hObject, eventdata, handles)
2332 % hObject    handle to MainStuff (see GCBO)
2333 % eventdata  reserved - to be defined in a future version of MATLAB
2334 % handles    structure with handles and user data (see GUIDATA)
2335
2336
2337 % --------------------------------------------------------------------
2338 function QuitXeX_Callback(hObject, eventdata, handles)
2339 % hObject    handle to QuitXeX (see GCBO)
2340 % eventdata  reserved - to be defined in a future version of MATLAB
2341 % handles    structure with handles and user data (see GUIDATA)
2342
2343 endR;
2344 delete(handles.figure1);
2345
2346
2347 % --------------------------------------------------------------------
2348 function AnalysisOptions_Callback(hObject, eventdata, handles)
2349 % hObject    handle to AnalysisOptions (see GCBO)
2350 % eventdata  reserved - to be defined in a future version of MATLAB
2351 % handles    structure with handles and user data (see GUIDATA)
2352
2353
2354 % --------------------------------------------------------------------
2355 function PlotLatency_Callback(hObject, eventdata, handles)
2356 % hObject    handle to PlotLatency (see GCBO)
2357 % eventdata  reserved - to be defined in a future version of MATLAB
2358 % handles    structure with handles and user data (see GUIDATA)
2359
2360 if strcmp(get(hObject,'Checked'),'off') set(hObject,'checked','on');
2361 else set(hObject,'Checked','off');
2362 end
2363
2364 guidata(hObject,handles);
2365
2366 % --------------------------------------------------------------------
2367 function SetBaselineWindow_Callback(hObject, eventdata, handles)
2368 % hObject    handle to SetBaselineWindow (see GCBO)
2369 % eventdata  reserved - to be defined in a future version of MATLAB
2370 % handles    structure with handles and user data (see GUIDATA)
2371
2372
2373 defaultanswer={'[-50 0]'};
2374
2375        prompt={'Enter baseline window'};
2376    name=['Baseline Window'];
2377    numlines=1;
2378
2379     answer=inputdlg(prompt,name,numlines,defaultanswer);
2380
2381    if ~isempty(answer)
2382
2383        BaselineWindow=str2num(answer{1});
2384        if isnumeric(BaselineWindow),
2385            handles.BaselineWindow=BaselineWindow;
2386            fprintf('%s\n',['Baseline Window set to [' num2str(BaselineWindow) ' ]']);
2387        end
2388
2389    end
2390
2391 guidata(hObject,handles);
2392
2393
2394
2395 % --------------------------------------------------------------------
2396 function PlottingContext_Callback(hObject, eventdata, handles)
2397 % hObject    handle to PlottingContext (see GCBO)
2398 % eventdata  reserved - to be defined in a future version of MATLAB
2399 % handles    structure with handles and user data (see GUIDATA)
2400
2401
2402 % --- Executes on button press in TalkToMe.
2403 function TalkToMe_Callback(hObject, eventdata, handles)
2404 % hObject    handle to TalkToMe (see GCBO)
2405 % eventdata  reserved - to be defined in a future version of MATLAB
2406 % handles    structure with handles and user data (see GUIDATA)
2407
2408 XeXUtters;
2409
2410
2411 % --------------------------------------------------------------------
2412 function ErrorBarType_Callback(hObject, eventdata, handles)
2413 % hObject    handle to ErrorBarType (see GCBO)
2414 % eventdata  reserved - to be defined in a future version of MATLAB
2415 % handles    structure with handles and user data (see GUIDATA)
2416
2417 if strcmp(get(hObject,'label'),'ChangeErrorToBootstrap'), set(hObject,'label','ChangeErrorToPoisson'); fprintf('%s\n','Confidence bands now Bootstrap');
2418 else set(hObject,'label','ChangeErrorToBootstrap'); fprintf('%s\n','Confidence bands now Poisson');
2419 end
2420
2421 guidata(hObject,handles);
2422
2423
2424 % % --------------------------------------------------------------------
2425 % function FTPTimer_Callback(hObject, eventdata, handles)
2426 % % hObject    handle to FTPTimer (see GCBO)
2427 % % eventdata  reserved - to be defined in a future version of MATLAB
2428 % % handles    structure with handles and user data (see GUIDATA)
2429 %
2430 % if isfield(handles,'FTP')
2431 %
2432 %     if strcmp(get(hObject,'Checked'),'off'),
2433 %
2434 % defaultanswer={'5'};
2435 %
2436 %    prompt={'FTPTimer every so many minutes'};
2437 %    name=['How often to FTPTimer ?'];
2438 %    numlines=1;
2439 % %    defaultanswer=danswer;
2440 %
2441 %    answer=inputdlg(prompt,name,numlines,defaultanswer);
2442 %
2443 %    if ~isempty(answer)
2444 % handles.FTPDelay=str2num(answer{1});
2445 % set(hObject,'Checked','on'), fprintf('%s\n','Turning timer on!!');
2446 %
2447 %
2448 % FileToFTP=[handles.FTP.pathname handles.FTP.filename];
2449 % FTPDir='c:\MATLAB\work\physiology';
2450 %
2451 %     AnalysisFiles=get(handles.AnalysisFile,'string');
2452 %     AnalysisFileValue=get(handles.AnalysisFile,'value');
2453 %     if iscell(AnalysisFiles)
2454 %     CurrentAnalysisFile=AnalysisFiles{AnalysisFileValue};
2455 %     else
2456 %         CurrentAnalysisFile=AnalysisFiles;
2457 %     end
2458 %     CurrentAnalysisFile=CurrentAnalysisFile(1:(end-2));
2459 %
2460 % if isfield(handles,'CurrentDataDirectory'), cd(handles.CurrentDataDirectory);end
2461 %
2462 % if isfield(handles,'timerhandle') && ~isempty(handles.timerhandle),
2463 %     stop(handles.timer);
2464 % delete(handles.timerhandle); handles.timerhandle=[];
2465 % fprintf('%s\n','Just stopped an unexpected running timer');
2466 % end
2467 %
2468 %    handles.timerhandle=timer('TimerFcn', {'LittleTimerFunction' {handles.XeXDir,FTPDir,FileToFTP,handles.UseStimAxes,handles.FTP.filename,CurrentAnalysisFile,handles.SaccadeOptions} },'Period', handles.FTPDelay*60,'ExecutionMode','fixedDelay','busymode','drop');
2469 % start(handles.timerhandle);
2470 % fprintf('%s\n','Started FTP timer !!');
2471 %
2472 %    else fprintf('%s\n','Not starting timer... then.'); set(hObject,'Checked','off');
2473 %    end
2474 %
2475 % else
2476 %
2477 %     if isfield(handles,'timerhandle') && ~isempty(handles.timerhandle),
2478 %     stop(handles.timerhandle);
2479 % delete(handles.timerhandle); handles.timerhandle=[];
2480 % fprintf('%s\n','Turning timer off');
2481 %     else fprintf('%s\n','Weird, where is the timer ?');    handles.timerhandle=[];
2482 %     end
2483 %     set(hObject,'Checked','off');
2484 %
2485 %   end
2486 %
2487 % else
2488 %     TellMe('%s\n','Enter the FTPTimer options first',handles.SpeakToMe);
2489 % end
2490 %
2491 % guidata(hObject,handles);
2492
2493
2494
2495 % --------------------------------------------------------------------
2496 function PlotCB_Callback(hObject, eventdata, handles)
2497 % hObject    handle to PlotCB (see GCBO)
2498 % eventdata  reserved - to be defined in a future version of MATLAB
2499 % handles    structure with handles and user data (see GUIDATA)
2500
2501
2502 if strcmp(get(hObject,'Checked'),'off') set(hObject,'checked','on');
2503 else set(hObject,'Checked','off');
2504 end
2505
2506 guidata(hObject,handles);
2507
2508
2509 % --- Executes on button press in FiltersList.
2510 function FiltersList_Callback(hObject, eventdata, handles)
2511 % hObject    handle to FiltersList (see GCBO)
2512 % eventdata  reserved - to be defined in a future version of MATLAB
2513 % handles    structure with handles and user data (see GUIDATA)
2514
2515 if ~isappdata(0,'TrialFilterHandle'), setappdata(0,'TrialFilterHandle',handles.TrialFilterVector);end
2516 % if ~isappdata(0,'UseFilterHandle'), setappdata(0,'UseFilterHandle',handles.UseFilters);end
2517 if ~isappdata(0,'FilterGUIHandle'), FilterManagerGUI;
2518
2519 if ~isappdata(0,'UsePlottingHandle'),    setappdata(0,'UsePlottingHandle',handles.UseProps); end
2520 if ~isappdata(0,'HoldFilterHandle'), setappdata(0,'HoldFilterHandle',handles.HoldStatus); end
2521
2522 else figure(getappdata(0,'FilterGUIHandle'));
2523 end
2524 guidata(hObject,handles);
2525
2526
2527 % --------------------------------------------------------------------
2528 function GainGraph_Callback(hObject, eventdata, handles)
2529 % hObject    handle to GainGraph (see GCBO)
2530 % eventdata  reserved - to be defined in a future version of MATLAB
2531 % handles    structure with handles and user data (see GUIDATA)
2532
2533 % if strcmp(get(hObject,'Checked'),'off') set(hObject,'checked','on');
2534 % %     keyboard;
2535 %     if strcmp(get(handles.SixGraph,'Checked'),'on'),
2536 %            set(handles.SixGraph,'checked','off');
2537 % %    makeVisible([handles.axes7 handles.axes8 handles.axes9]);
2538 %     end
2539
2540     gset;
2541
2542 % %        set_gainposits;
2543 % else set(hObject,'Checked','off');
2544 % %     reset_gainposits;
2545 % twelveset;
2546 % %     makeVisible([handles.Axis7Indicator handles.Axis8Indicator handles.Axis9Indicator]);
2547 % end
2548
2549 % handles.NumberOfAxes=9;
2550
2551 guidata(hObject,handles);
2552
2553 % --- Executes on selection change in WhatToDo.
2554 function WhatToDo_Callback(hObject, eventdata, handles)
2555 % hObject    handle to WhatToDo (see GCBO)
2556 % eventdata  reserved - to be defined in a future version of MATLAB
2557 % handles    structure with handles and user data (see GUIDATA)
2558
2559 % Hints: contents = get(hObject,'String') returns WhatToDo contents as cell array
2560 %        contents{get(hObject,'Value')} returns selected item from WhatToDo
2561
2562 WhatToDoStuff;
2563 DoUseProps;
2564
2565 ThingsToDo=get(handles.WhatToDo,'string');
2566 WhatToDo=ThingsToDo{get(handles.WhatToDo,'value')};
2567 if strcmp(WhatToDo,'MakeHist')
2568 % set(handles.UpdateSlider,'value',5);
2569 % set(handles.SliderText,'string','SV=5');
2570 set(handles.BinWidth,'value',100);
2571 set(handles.SliderValue,'string','BW=100');
2572 end
2573
2574 % ShowSlider;
2575
2576 % contents=get(handles.PlottingFileList,'String');
2577 % currentselection=contents{get(handles.PlottingFileList,'value')};
2578 %
2579 % switch(currentselection),
2580 %     case 'ImageMap.m', set(handles.StimulusAlignedTimeVector,'string','[50 150]');
2581 %     case 'CircleMap.m', set(handles.StimulusAlignedTimeVector,'string','[50 150]');
2582 %     case 'SpikeDensity.m', set(handles.StimulusAlignedTimeVector,'string','[-400 400]');
2583 %     case 'DrawPSTH.m', set(handles.StimulusAlignedTimeVector,'string','[-400 400]');
2584 % end
2585
2586 guidata(hObject,handles);
2587
2588
2589 % --- Executes during object creation, after setting all properties.
2590 function WhatToDo_CreateFcn(hObject, eventdata, handles)
2591 % hObject    handle to WhatToDo (see GCBO)
2592 % eventdata  reserved - to be defined in a future version of MATLAB
2593 % handles    empty - handles not created until after all CreateFcns called
2594
2595 % Hint: popupmenu controls usually have a white background on Windows.
2596 %       See ISPC and COMPUTER.
2597 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
2598     set(hObject,'BackgroundColor','white');
2599 end
2600
2601
2602
2603 % --------------------------------------------------------------------
2604
2605 function UseTheseAxes_Callback(hObject, eventdata, handles)
2606 % hObject    handle to UseTheseAxes (see GCBO)
2607 % eventdata  reserved - to be defined in a future version of MATLAB
2608 % handles    structure with handles and user data (see GUIDATA)
2609
2610 % Hints: get(hObject,'String') returns contents of UseTheseAxes as text
2611 %        str2double(get(hObject,'String')) returns contents of UseTheseAxes as a double
2612
2613
2614 % --- Executes during object creation, after setting all properties.
2615 function UseTheseAxes_CreateFcn(hObject, eventdata, handles)
2616 % hObject    handle to UseTheseAxes (see GCBO)
2617 % eventdata  reserved - to be defined in a future version of MATLAB
2618 % handles    empty - handles not created until after all CreateFcns called
2619
2620 % Hint: edit controls usually have a white background on Windows.
2621 %       See ISPC and COMPUTER.
2622 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
2623     set(hObject,'BackgroundColor','white');
2624 end
2625
2626
2627
2628
2629 % % --- Executes on button press in UseFilters.
2630 % function UseFilters_Callback(hObject, eventdata, handles)
2631 % % hObject    handle to UseFilters (see GCBO)
2632 % % eventdata  reserved - to be defined in a future version of MATLAB
2633 % % handles    structure with handles and user data (see GUIDATA)
2634 %
2635 % % Hint: get(hObject,'Value') returns toggle state of UseFilters
2636 %
2637 % if get(hObject,'value')==0
2638 % %     set(handles.TrialFilterVector,'string','');
2639 % end
2640 % guidata(hObject,handles);
2641
2642
2643 % --------------------------------------------------------------------
2644 function LatencyAfter_Callback(hObject, eventdata, handles)
2645 % hObject    handle to LatencyAfter (see GCBO)
2646 % eventdata  reserved - to be defined in a future version of MATLAB
2647 % handles    structure with handles and user data (see GUIDATA)
2648
2649 defaultanswer={'0'};
2650
2651        prompt={'Calculate latency after'};
2652    name=['Latency after'];
2653    numlines=1;
2654
2655     answer=inputdlg(prompt,name,numlines,defaultanswer);
2656
2657    if ~isempty(answer)
2658
2659        LatInitTime=str2num(answer{1});
2660        if isnumeric(LatInitTime),
2661            handles.LatInitTime=LatInitTime;
2662            fprintf('%s\n',['Latency after ' num2str(LatInitTime) ' ms']);
2663        end
2664
2665    end
2666
2667 guidata(hObject,handles);
2668
2669
2670
2671 % --------------------------------------------------------------------
2672 function SetCellProps_Callback(hObject, eventdata, handles)
2673 % hObject    handle to SetCellProps (see GCBO)
2674 % eventdata  reserved - to be defined in a future version of MATLAB
2675 % handles    structure with handles and user data (see GUIDATA)
2676
2677 %    prompt={'Enter Unit Number','Enter RF location'};
2678    prompt={'Enter RF location'};
2679    name='RF Location ';
2680    numlines=1;
2681    defaultanswer={num2str(handles.RFLocation)};
2682
2683    Answer=inputdlg(prompt,name,numlines,defaultanswer);
2684
2685    if ~isempty(Answer)
2686 % handles.UnitNumber=str2num(Answer{1});
2687 handles.RFLocation=str2num(Answer{1});
2688    end
2689
2690    setappdata(0,'RFLocation',handles.RFLocation);
2691    guidata(hObject,handles);
2692
2693
2694
2695 % --- Executes on selection change in VariablesList.
2696 function VariablesList_Callback(hObject, eventdata, handles)
2697 % hObject    handle to VariablesList (see GCBO)
2698 % eventdata  reserved - to be defined in a future version of MATLAB
2699 % handles    structure with handles and user data (see GUIDATA)
2700
2701 % Hints: contents = get(hObject,'String') returns VariablesList contents as cell array
2702 %        contents{get(hObject,'Value')} returns selected item from VariablesList
2703
2704
2705 % --- Executes during object creation, after setting all properties.
2706 function VariablesList_CreateFcn(hObject, eventdata, handles)
2707 % hObject    handle to VariablesList (see GCBO)
2708 % eventdata  reserved - to be defined in a future version of MATLAB
2709 % handles    empty - handles not created until after all CreateFcns called
2710
2711 % Hint: popupmenu controls usually have a white background on Windows.
2712 %       See ISPC and COMPUTER.
2713 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
2714     set(hObject,'BackgroundColor','white');
2715 end
2716
2717
2718
2719
2720 % --------------------------------------------------------------------
2721 function Layouts_Callback(hObject, eventdata, handles)
2722 % hObject    handle to Layouts (see GCBO)
2723 % eventdata  reserved - to be defined in a future version of MATLAB
2724 % handles    structure with handles and user data (see GUIDATA)
2725
2726
2727 % --------------------------------------------------------------------
2728 function SixGraph_Callback(hObject, eventdata, handles)
2729 % hObject    handle to SixGraph (see GCBO)
2730 % eventdata  reserved - to be defined in a future version of MATLAB
2731 % handles    structure with handles and user data (see GUIDATA)
2732
2733 %
2734 % if strcmp(get(hObject,'Checked'),'off') set(hObject,'checked','on');
2735 %    if strcmp(get(handles.GainGraph,'Checked'),'on'),
2736 % %        reset_gainposits;
2737 %        set(handles.GainGraph,'Checked','off');
2738 %    end
2739       nineset;
2740 makeInvisible([handles.axes7 handles.axes8 handles.axes9 handles.Axis7Indicator handles.Axis8Indicator handles.Axis9Indicator]);
2741 handles.NumberOfAxes=6;
2742 % else
2743 %    set(hObject,'checked','off');
2744 % %    makeVisible([handles.axes7 handles.axes8 handles.axes9 handles.Axis7Indicator handles.Axis8Indicator handles.Axis9Indicator]);
2745 % twelveset;
2746 % end
2747
2748  FullString=[];
2749     for tempind=7:12
2750         FullString=[FullString 'handles.AxisObj' num2str(tempind) ','];
2751     end
2752
2753     eval(['makeInvisible([' FullString '])']);
2754
2755 guidata(hObject,handles);
2756
2757
2758 % --- Executes on button press in ManageObjects.
2759 function ManageObjects_Callback(hObject, eventdata, handles)
2760 % hObject    handle to ManageObjects (see GCBO)
2761 % eventdata  reserved - to be defined in a future version of MATLAB
2762 % handles    structure with handles and user data (see GUIDATA)
2763
2764 Objs=[handles.GetObjectPropsButton, handles.GetObjectAxes, handles.DeleteObjects, handles.MoveObj, handles.CopyObj, handles.text64, handles.text65, handles.text66, handles.ObjectNumber, handles.OldAxis,handles.NewAxis];
2765
2766 VarObjs=[handles.text88, handles.text89, handles.text90, handles.UnBut, handles.XAxisVariable, handles.X1AxisVariable, handles.YAxisVariable, handles.XAxisCenters, handles.X1AxisCenters, handles.XAxisDiscretize, handles.X1AxisDiscretize, handles.ReverseXY];
2767
2768 if strcmp(get(hObject,'string'), 'ManageObjects'), set(hObject,'string','BackToVars');
2769     makeVisible(Objs);
2770     makeInvisible(VarObjs);
2771 else set(hObject,'string','ManageObjects');
2772     makeInvisible(Objs);
2773     makeVisible(VarObjs);
2774 end
2775
2776 guidata(hObject,handles);
2777
2778
2779
2780 % --- Executes during object creation, after setting all properties.
2781 function ManageObjects_CreateFcn(hObject, eventdata, handles)
2782 % hObject    handle to ManageObjects (see GCBO)
2783 % eventdata  reserved - to be defined in a future version of MATLAB
2784 % handles    empty - handles not created until after all CreateFcns called
2785
2786
2787
2788
2789 % --- Executes on button press in UnBut -> DOES THE UNIQUE(CURRENTVARIABLE)
2790 function UnBut_Callback(hObject, eventdata, handles)
2791 % hObject    handle to UnBut (see GCBO)
2792 % eventdata  reserved - to be defined in a future version of MATLAB
2793 % handles    structure with handles and user data (see GUIDATA)
2794
2795 VarList=cellstr(get(handles.XAxisVariable,'string'));
2796 CurVar=VarList{get(handles.XAxisVariable,'value')};
2797
2798   LoadedFileList=get(handles.LoadedFiles,'string');
2799  if ~iscell(LoadedFileList), TempVar{1}=LoadedFileList; LoadedFileList=TempVar;end
2800  CurrentValue=get(handles.LoadedFiles,'value'); CurrentValue=CurrentValue(1);
2801  CurrentDataFile=LoadedFileList{CurrentValue};
2802
2803 if ~strcmp(CurrentDataFile,'LoadedFiles')
2804
2805 eval(['Trials=handles.' CurrentDataFile '.Trials;']);
2806 eval(['if ~isfield(handles.' CurrentDataFile ',''Analysis''), fprintf(''%s\n'',''Analyze your dataset first''); GoOn=0;else GoOn=1;end']);
2807 eval(['if GoOn==1, MyVariableList=handles.' CurrentDataFile '.Analysis.MyVariableList;end']);
2808 %
2809 % msgbox(MyVariableList,'Variable List','help');
2810
2811 eval(['if GoOn==1, CurrentVariables=handles.' CurrentDataFile '.Analysis;end']);
2812 detachvars;
2813
2814 if exist(CurVar,'var')
2815 eval(['UnVar=un(' CurVar ');']);
2816
2817 if length(UnVar)<50, fprintf('%6.2f\n',UnVar); else fprintf('There are %d unique variables\n',length(UnVar));end
2818
2819 clearvars;
2820
2821 else fprintf('%s\n','That variable doesnt exist ??');
2822 end
2823
2824 end
2825
2826 % keyboard;
2827
2828 % --- Executes during object creation, after setting all properties.
2829 function UnBut_CreateFcn(hObject, eventdata, handles)
2830 % hObject    handle to ManageObjects (see GCBO)
2831 % eventdata  reserved - to be defined in a future version of MATLAB
2832 % handles    empty - handles not created until after all CreateFcns called
2833
2834
2835
2836
2837 % --- Executes on selection change in GraphCommandFiles.
2838 function GraphCommandFiles_Callback(hObject, eventdata, handles)
2839 % hObject    handle to GraphCommandFiles (see GCBO)
2840 % eventdata  reserved - to be defined in a future version of MATLAB
2841 % handles    structure with handles and user data (see GUIDATA)
2842
2843 % Hints: contents = get(hObject,'String') returns GraphCommandFiles contents as cell array
2844 %        contents{get(hObject,'Value')} returns selected item from GraphCommandFiles
2845
2846 % contents=cellstr(get(hObject,'String'));
2847 % CurrentCommandFile=contents{get(hObject,'value')}; %string contains current command filename
2848 %
2849 % if strcmp(CurrentCommandFile,'CmdEditor')
2850 %
2851 %     if ~isappdata(0,'TrialFilterHandle'), setappdata(0,'TrialFilterHandle',handles.TrialFilterVector);end
2852 % % if ~isappdata(0,'UseFilterHandle'), setappdata(0,'UseFilterHandle',handles.UseFilters);end
2853 % if ~isappdata(0,'UsePlottingHandle'),    setappdata(0,'UsePlottingHandle',handles.UseProps); end
2854 % if ~isappdata(0,'HoldFilterHandle'), setappdata(0,'HoldFilterHandle',handles.HoldStatus);end
2855 %
2856 % if ~isappdata(0,'GraphCmdGUIHandle'), GraphCommandEditor;
2857 %    else figure(getappdata(0,'GraphCmdGUIHandle'));
2858 % end
2859 %
2860 % end
2861
2862 % guidata(hObject,handles);
2863
2864 % --- Executes during object creation, after setting all properties.
2865 function GraphCommandFiles_CreateFcn(hObject, eventdata, handles)
2866 % hObject    handle to GraphCommandFiles (see GCBO)
2867 % eventdata  reserved - to be defined in a future version of MATLAB
2868 % handles    empty - handles not created until after all CreateFcns called
2869
2870 % Hint: popupmenu controls usually have a white background on Windows.
2871 %       See ISPC and COMPUTER.
2872 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
2873     set(hObject,'BackgroundColor','white');
2874 end
2875
2876
2877 % --- Executes on button press in AddGrapher.
2878 function AddGrapher_Callback(hObject, eventdata, handles)
2879 % hObject    handle to AddGrapher (see GCBO)
2880 % eventdata  reserved - to be defined in a future version of MATLAB
2881 % handles    structure with handles and user data (see GUIDATA)
2882
2883
2884 Old_Dir=pwd;
2885 if ~exist('GraphCommandsDirectory','var'), GraphCommandsDirectory='c:\MATLAB\work\XeX\MyGraphs';end
2886 cd(GraphCommandsDirectory);
2887
2888    [input_filename, input_pathname] = uigetfile(...
2889        {'*_gfx.m','Graph-files (*_gfx.m)';
2890         '*.*',  'All Files (*.*)'}, ...
2891         'Add Graph Command File(s)', ...
2892         'MultiSelect', 'on');
2893
2894     %%loading the files
2895
2896      if ~isnumeric(input_filename)
2897      if ~iscell(input_filename) TemporaryStuff{1}=input_filename;
2898      input_filename=TemporaryStuff;
2899      end
2900
2901 GraphFileNames=get(handles.GraphCommandFiles,'string');
2902          if ~iscell(GraphFileNames)&&~strcmp(GraphFileNames,'CmdFiles')
2903              TemporaryStuff{1}=GraphFileNames;
2904              GraphFileNames=TemporaryStuff;
2905          end
2906
2907          if ~iscell(GraphFileNames)
2908              set(handles.GraphCommandFiles,'string',sort(input_filename));
2909          else
2910              NewNames=setdiff(input_filename,GraphFileNames);
2911              set(handles.GraphCommandFiles,'string',sort([NewNames GraphFileNames']'));
2912          end
2913
2914          guidata(hObject,handles);
2915
2916      end
2917
2918         cd(Old_Dir);
2919
2920
2921 % --- Executes on button press in RunGraph.
2922 function RunGraph_Callback(hObject, eventdata, handles)
2923 % hObject    handle to RunGraph (see GCBO)
2924 % eventdata  reserved - to be defined in a future version of MATLAB
2925 % handles    structure with handles and user data (see GUIDATA)
2926
2927
2928 GraphCommandProcessor;
2929
2930 guidata(hObject,handles);  %routinely saving anything assigned to handles
2931
2932
2933 % --- Executes on button press in SetGraphicDir.
2934 function SetGraphicDir_Callback(hObject, eventdata, handles)
2935 % hObject    handle to SetGraphicDir (see GCBO)
2936 % eventdata  reserved - to be defined in a future version of MATLAB
2937 % handles    structure with handles and user data (see GUIDATA)
2938
2939 TempDir=uigetdir(handles.GraphCommandsDirectory,'Set Graph Commands Directory');
2940 if ~isequal(TempDir,0)
2941     handles.GraphCommandsDirectory=TempDir;
2942 end
2943
2944 guidata(hObject,handles);
2945
2946
2947 % --- Executes on selection change in UnitNumberPop.
2948 function UnitNumberPop_Callback(hObject, eventdata, handles)
2949 % hObject    handle to UnitNumberPop (see GCBO)
2950 % eventdata  reserved - to be defined in a future version of MATLAB
2951 % handles    structure with handles and user data (see GUIDATA)
2952
2953 % Hints: contents = get(hObject,'String') returns UnitNumberPop contents as cell array
2954 %        contents{get(hObject,'Value')} returns selected item from UnitNumberPop
2955
2956 contents=cellstr(get(hObject,'string'));
2957 handles.UnitNumber=str2num(contents{get(hObject,'value')});
2958 fprintf('%s\n',['Unit Number is now ' num2str(handles.UnitNumber) ' ']);
2959
2960 ThingsToDo=get(handles.WhatToDo,'String');
2961 WhatToDo=ThingsToDo{get(handles.WhatToDo,'value')};
2962
2963 if strcmp(WhatToDo,'ActiveUpdate'),
2964 UpdateType='UnitNumber';
2965 UpdateSlider;
2966 end
2967
2968 guidata(hObject,handles);
2969
2970 % --- Executes during object creation, after setting all properties.
2971 function UnitNumberPop_CreateFcn(hObject, eventdata, handles)
2972 % hObject    handle to UnitNumberPop (see GCBO)
2973 % eventdata  reserved - to be defined in a future version of MATLAB
2974 % handles    empty - handles not created until after all CreateFcns called
2975
2976 % Hint: popupmenu controls usually have a white background on Windows.
2977 %       See ISPC and COMPUTER.
2978 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
2979     set(hObject,'BackgroundColor','white');
2980 end
2981
2982
2983
2984
2985 % --- Executes on button press in DelTrials.
2986 function DelTrials_Callback(hObject, eventdata, handles)
2987 % hObject    handle to DelTrials (see GCBO)
2988 % eventdata  reserved - to be defined in a future version of MATLAB
2989 % handles    structure with handles and user data (see GUIDATA)
2990
2991
2992 LoadedFileList=get(handles.LoadedFiles,'string');
2993 CurrentValues=get(handles.LoadedFiles,'value');
2994 if ~iscell(LoadedFileList), LoadedFileList={LoadedFileList};end
2995
2996 CurrentlyLoadedFiles=LoadedFileList(CurrentValues);
2997
2998
2999 if ~strcmp(CurrentlyLoadedFiles{1},'LoadedFiles')
3000 for FileIndex=1:length(CurrentlyLoadedFiles)
3001     CurrentFile=CurrentlyLoadedFiles{FileIndex};
3002     eval(['handles.' CurrentFile '.Trials= NaN;']);
3003     fprintf('%s\n',['Removed trials from ' CurrentFile]);
3004
3005 end
3006 else TellMe('%s\n','Load a file first !',handles.SpeakToMe);
3007 end
3008
3009 guidata(hObject,handles);
3010
3011
3012
3013
3014 % --------------------------------------------------------------------
3015 function RmIndicators_Callback(hObject, eventdata, handles)
3016 % hObject    handle to RmIndicators (see GCBO)
3017 % eventdata  reserved - to be defined in a future version of MATLAB
3018 % handles    structure with handles and user data (see GUIDATA)
3019
3020 if strcmp(get(hObject,'checked'),'on')
3021     set(hObject,'checked','off');
3022     for i=1:handles.NumberOfAxes
3023     eval(['makeVisible(handles.Axis' num2str(i) 'Indicator);']);
3024     end
3025 else
3026     set(hObject,'checked','on');
3027       for i=1:handles.NumberOfAxes
3028     eval(['makeInvisible(handles.Axis' num2str(i) 'Indicator);']);
3029       end
3030 end
3031
3032 guidata(hObject,handles);
3033
3034
3035 % --------------------------------------------------------------------
3036 function ResetLayout_Callback(hObject, eventdata, handles)
3037 % hObject    handle to ResetLayout (see GCBO)
3038 % eventdata  reserved - to be defined in a future version of MATLAB
3039 % handles    structure with handles and user data (see GUIDATA)
3040
3041 twelveset;
3042 guidata(hObject,handles);
3043
3044
3045 % --------------------------------------------------------------------
3046 function ClearTitle_Callback(hObject, eventdata, handles)
3047 % hObject    handle to ClearTitle (see GCBO)
3048 % eventdata  reserved - to be defined in a future version of MATLAB
3049 % handles    structure with handles and user data (see GUIDATA)
3050
3051 for Temp=1:handles.NumberOfAxes
3052     eval(['axes(handles.axes' num2str(Temp) ');']);
3053     title(''); xlabel(''); ylabel('');
3054     eval(['handles.A' num2str(Temp) 'Annotations={'''','''',''''};']);
3055 end
3056
3057 guidata(hObject,handles);
3058
3059
3060 % --------------------------------------------------------------------
3061 function Axis10Markers_Callback(hObject, eventdata, handles)
3062 % hObject    handle to Axis10Markers (see GCBO)
3063 % eventdata  reserved - to be defined in a future version of MATLAB
3064 % handles    structure with handles and user data (see GUIDATA)
3065
3066 % Hints: get(hObject,'String') returns contents of Axis10Markers as text
3067 %        str2double(get(hObject,'String')) returns contents of Axis10Markers as a double
3068
3069 CurrentAxisMarkerNumber=10;
3070 UpdateMarkers;
3071 guidata(hObject,handles);
3072
3073
3074 % --- Executes during object creation, after setting all properties.
3075 function Axis10Markers_CreateFcn(hObject, eventdata, handles)
3076 % hObject    handle to Axis10Markers (see GCBO)
3077 % eventdata  reserved - to be defined in a future version of MATLAB
3078 % handles    empty - handles not created until after all CreateFcns called
3079
3080 % Hint: edit controls usually have a white background on Windows.
3081 %       See ISPC and COMPUTER.
3082 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
3083     set(hObject,'BackgroundColor','white');
3084 end
3085
3086 % --------------------------------------------------------------------
3087 function Axis11Markers_Callback(hObject, eventdata, handles)
3088 % hObject    handle to Axis11Markers (see GCBO)
3089 % eventdata  reserved - to be defined in a future version of MATLAB
3090 % handles    structure with handles and user data (see GUIDATA)
3091
3092 % Hints: get(hObject,'String') returns contents of Axis11Markers as text
3093 %        str2double(get(hObject,'String')) returns contents of Axis11Markers as a double
3094
3095 CurrentAxisMarkerNumber=11;
3096 UpdateMarkers;
3097 guidata(hObject,handles);
3098
3099 % --- Executes during object creation, after setting all properties.
3100 function Axis11Markers_CreateFcn(hObject, eventdata, handles)
3101 % hObject    handle to Axis11Markers (see GCBO)
3102 % eventdata  reserved - to be defined in a future version of MATLAB
3103 % handles    empty - handles not created until after all CreateFcns called
3104
3105 % Hint: edit controls usually have a white background on Windows.
3106 %       See ISPC and COMPUTER.
3107 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
3108     set(hObject,'BackgroundColor','white');
3109 end
3110
3111
3112 % --------------------------------------------------------------------
3113 function Axis12Markers_Callback(hObject, eventdata, handles)
3114 % hObject    handle to Axis12Markers (see GCBO)
3115 % eventdata  reserved - to be defined in a future version of MATLAB
3116 % handles    structure with handles and user data (see GUIDATA)
3117
3118 % Hints: get(hObject,'String') returns contents of Axis12Markers as text
3119 %        str2double(get(hObject,'String')) returns contents of Axis12Markers as a double
3120
3121 CurrentAxisMarkerNumber=12;
3122 UpdateMarkers;
3123 guidata(hObject,handles);
3124
3125 % --- Executes during object creation, after setting all properties.
3126 function Axis12Markers_CreateFcn(hObject, eventdata, handles)
3127 % hObject    handle to Axis12Markers (see GCBO)
3128 % eventdata  reserved - to be defined in a future version of MATLAB
3129 % handles    empty - handles not created until after all CreateFcns called
3130
3131 % Hint: edit controls usually have a white background on Windows.
3132 %       See ISPC and COMPUTER.
3133 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
3134     set(hObject,'BackgroundColor','white');
3135 end
3136
3137
3138 % --------------------------------------------------------------------
3139 function NineGraphs_Callback(hObject, eventdata, handles)
3140 % hObject    handle to NineGraphs (see GCBO)
3141 % eventdata  reserved - to be defined in a future version of MATLAB
3142 % handles    structure with handles and user data (see GUIDATA)
3143
3144 nineset;
3145
3146 guidata(hObject,handles);
3147
3148 % --- Executes on button press in EditCmdFile.
3149 function EditCmdFile_Callback(hObject, eventdata, handles)
3150 % hObject    handle to EditCmdFile (see GCBO)
3151 % eventdata  reserved - to be defined in a future version of MATLAB
3152 % handles    structure with handles and user data (see GUIDATA)
3153
3154 TempG=cellstr(get(handles.GraphCommandFiles,'string'));
3155 CurrentGFile=TempG{get(handles.GraphCommandFiles,'value')};
3156 if ~strcmp(CurrentGFile,'CmdFiles')
3157 edit(CurrentGFile);
3158 else fprintf('%s\n','Add a file first');
3159 end
3160
3161 guidata(hObject,handles);
3162
3163
3164 % --------------------------------------------------------------------
3165 function SigLevel_Callback(hObject, eventdata, handles)
3166 % hObject    handle to SigLevel (see GCBO)
3167 % eventdata  reserved - to be defined in a future version of MATLAB
3168 % handles    structure with handles and user data (see GUIDATA)
3169
3170 defaultanswer={num2str(handles.SignificanceCutoff)};
3171
3172        prompt={'Enter alpha'};
3173    name=['Significance alpha'];
3174    numlines=1;
3175
3176     answer=inputdlg(prompt,name,numlines,defaultanswer);
3177
3178    if ~isempty(answer)
3179
3180        sigalpha=str2num(answer{1});
3181        if isnumeric(sigalpha),
3182            handles.SignificanceCutoff=sigalpha;
3183            fprintf('%s\n',['Alpha set to [' answer{1} ' ]']);
3184        end
3185
3186    end
3187
3188 guidata(hObject,handles);
3189
3190
3191
3192 %---
3193
3194 function FTPFileName_Callback(hObject, eventdata, handles)
3195 % hObject    handle to FTPFileName (see GCBO)
3196 % eventdata  reserved - to be defined in a future version of MATLAB
3197 % handles    structure with handles and user data (see GUIDATA)
3198
3199 % Hints: get(hObject,'String') returns contents of FTPFileName as text
3200 %        str2double(get(hObject,'String')) returns contents of FTPFileName as a double
3201
3202 if isfield(handles,'FTP')
3203 handles.FTP.filename=get(hObject,'string');
3204 guidata(hObject,handles);
3205 else
3206     fprintf('%s\n','Enter FTP Pathname from Menu: FTP Options first');
3207 end
3208
3209 % --- Executes during object creation, after setting all properties.
3210 function FTPFileName_CreateFcn(hObject, eventdata, handles)
3211 % hObject    handle to FTPFileName (see GCBO)
3212 % eventdata  reserved - to be defined in a future version of MATLAB
3213 % handles    empty - handles not created until after all CreateFcns called
3214
3215 % Hint: edit controls usually have a white background on Windows.
3216 %       See ISPC and COMPUTER.
3217 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
3218     set(hObject,'BackgroundColor','white');
3219 end
3220
3221
3222 % --- Executes on button press in FTPMe.
3223 function FTPMe_Callback(hObject, eventdata, handles)
3224 % hObject    handle to FTPMe (see GCBO)
3225 % eventdata  reserved - to be defined in a future version of MATLAB
3226 % handles    structure with handles and user data (see GUIDATA)
3227
3228
3229 FTPScript;
3230 guidata(hObject,handles);
3231
3232
3233 % --------------------------------------------------------------------
3234 function FTPRelated_Callback(hObject, eventdata, handles)
3235 % hObject    handle to FTPRelated (see GCBO)
3236 % eventdata  reserved - to be defined in a future version of MATLAB
3237 % handles    structure with handles and user data (see GUIDATA)
3238
3239
3240 % --------------------------------------------------------------------
3241 function FTPMode_Callback(hObject, eventdata, handles)
3242 % hObject    handle to FTPMode (see GCBO)
3243 % eventdata  reserved - to be defined in a future version of MATLAB
3244 % handles    structure with handles and user data (see GUIDATA)
3245
3246 if strcmp(get(hObject,'checked'),'on')
3247     set(hObject,'checked','off');
3248     makeInvisible([handles.FTPMe handles.FTPFileName handles.FTPUpdate]);
3249 else
3250     set(hObject,'checked','on');
3251     makeVisible([handles.FTPMe handles.FTPFileName handles.FTPUpdate]);
3252 end
3253
3254 guidata(hObject,handles);
3255
3256 % --------------------------------------------------------------------
3257 function HelpTips_Callback(hObject, eventdata, handles)
3258 % hObject    handle to HelpTips (see GCBO)
3259 % eventdata  reserved - to be defined in a future version of MATLAB
3260 % handles    structure with handles and user data (see GUIDATA)
3261 % helpstring={'pwf is a file in the "Assorted" subdirectory of the root xex directory. It contains the information that ncftpget uses'};
3262 % helpdlg(helpstring,'FTP information');
3263
3264 web('help.html');
3265
3266 % --------------------------------------------------------------------
3267 function Help_Callback(hObject, eventdata, handles)
3268 % hObject    handle to Help (see GCBO)
3269 % eventdata  reserved - to be defined in a future version of MATLAB
3270 % handles    structure with handles and user data (see GUIDATA)
3271
3272
3273
3274 % --------------------------------------------------------------------
3275 function ResetAxisProps_Callback(hObject, eventdata, handles)
3276 % hObject    handle to ResetAxisProps (see GCBO)
3277 % eventdata  reserved - to be defined in a future version of MATLAB
3278 % handles    structure with handles and user data (see GUIDATA)
3279
3280 for TempVar=1:handles.NumberOfAxes
3281     eval(['set(handles.Axis' num2str(TempVar) 'Markers,''string'',''b-r-m-c-k-y-'');']);
3282 end
3283
3284 guidata(hObject,handles);
3285
3286
3287 % --- Executes on selection change in XAxisVariable.
3288 function XAxisVariable_Callback(hObject, eventdata, handles)
3289 % hObject    handle to XAxisVariable (see GCBO)
3290 % eventdata  reserved - to be defined in a future version of MATLAB
3291 % handles    structure with handles and user data (see GUIDATA)
3292
3293 % Hints: contents = get(hObject,'String') returns XAxisVariable contents as cell array
3294 %        contents{get(hObject,'Value')} returns selected item from XAxisVariable
3295
3296 ThingsToDo=get(handles.WhatToDo,'String');
3297 WhatToDo=ThingsToDo{get(handles.WhatToDo,'value')};
3298
3299 if strcmp(WhatToDo,'ActiveUpdate'),
3300 UpdateType='XAxisVar';
3301 UpdateSlider;
3302 end
3303
3304 guidata(hObject,handles);
3305
3306 % --- Executes during object creation, after setting all properties.
3307 function XAxisVariable_CreateFcn(hObject, eventdata, handles)
3308 % hObject    handle to XAxisVariable (see GCBO)
3309 % eventdata  reserved - to be defined in a future version of MATLAB
3310 % handles    empty - handles not created until after all CreateFcns called
3311
3312 % Hint: popupmenu controls usually have a white background on Windows.
3313 %       See ISPC and COMPUTER.
3314 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
3315     set(hObject,'BackgroundColor','white');
3316 end
3317
3318
3319 % --- Executes on selection change in X1AxisVariable.
3320 function X1AxisVariable_Callback(hObject, eventdata, handles)
3321 % hObject    handle to X1AxisVariable (see GCBO)
3322 % eventdata  reserved - to be defined in a future version of MATLAB
3323 % handles    structure with handles and user data (see GUIDATA)
3324
3325 % Hints: contents = get(hObject,'String') returns X1AxisVariable contents as cell array
3326 %        contents{get(hObject,'Value')} returns selected item from X1AxisVariable
3327
3328 ThingsToDo=get(handles.WhatToDo,'String');
3329 WhatToDo=ThingsToDo{get(handles.WhatToDo,'value')};
3330
3331 if strcmp(WhatToDo,'ActiveUpdate'),
3332 UpdateType='X1AxisVar';
3333 UpdateSlider;
3334 end
3335
3336 guidata(hObject,handles);
3337
3338 % --- Executes during object creation, after setting all properties.
3339 function X1AxisVariable_CreateFcn(hObject, eventdata, handles)
3340 % hObject    handle to X1AxisVariable (see GCBO)
3341 % eventdata  reserved - to be defined in a future version of MATLAB
3342 % handles    empty - handles not created until after all CreateFcns called
3343
3344 % Hint: popupmenu controls usually have a white background on Windows.
3345 %       See ISPC and COMPUTER.
3346 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
3347     set(hObject,'BackgroundColor','white');
3348 end
3349
3350
3351 % --- Executes on button press in XAxisDiscretize.
3352 function XAxisDiscretize_Callback(hObject, eventdata, handles)
3353 % hObject    handle to XAxisDiscretize (see GCBO)
3354 % eventdata  reserved - to be defined in a future version of MATLAB
3355 % handles    structure with handles and user data (see GUIDATA)
3356
3357 % Hint: get(hObject,'Value') returns toggle state of XAxisDiscretize
3358
3359
3360 % --- Executes on button press in X1AxisDiscretize.
3361 function X1AxisDiscretize_Callback(hObject, eventdata, handles)
3362 % hObject    handle to X1AxisDiscretize (see GCBO)
3363 % eventdata  reserved - to be defined in a future version of MATLAB
3364 % handles    structure with handles and user data (see GUIDATA)
3365
3366 % Hint: get(hObject,'Value') returns toggle state of X1AxisDiscretize
3367
3368
3369
3370 function XAxisCenters_Callback(hObject, eventdata, handles)
3371 % hObject    handle to XAxisCenters (see GCBO)
3372 % eventdata  reserved - to be defined in a future version of MATLAB
3373 % handles    structure with handles and user data (see GUIDATA)
3374
3375 % Hints: get(hObject,'String') returns contents of XAxisCenters as text
3376 %        str2double(get(hObject,'String')) returns contents of XAxisCenters as a double
3377
3378 ThingsToDo=get(handles.WhatToDo,'String');
3379 WhatToDo=ThingsToDo{get(handles.WhatToDo,'value')};
3380
3381 if strcmp(WhatToDo,'ActiveUpdate'),
3382 UpdateType='XAxisDiscreteVals';
3383 UpdateSlider;
3384 end
3385
3386 guidata(hObject,handles);
3387
3388
3389 % --- Executes during object creation, after setting all properties.
3390 function XAxisCenters_CreateFcn(hObject, eventdata, handles)
3391 % hObject    handle to XAxisCenters (see GCBO)
3392 % eventdata  reserved - to be defined in a future version of MATLAB
3393 % handles    empty - handles not created until after all CreateFcns called
3394
3395 % Hint: edit controls usually have a white background on Windows.
3396 %       See ISPC and COMPUTER.
3397 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
3398     set(hObject,'BackgroundColor','white');
3399 end
3400
3401
3402 %--------------------------------------------------------------------------
3403 function X1AxisCenters_Callback(hObject, eventdata, handles)
3404 % hObject    handle to X1AxisCenters (see GCBO)
3405 % eventdata  reserved - to be defined in a future version of MATLAB
3406 % handles    structure with handles and user data (see GUIDATA)
3407
3408 % Hints: get(hObject,'String') returns contents of X1AxisCenters as text
3409 %        str2double(get(hObject,'String')) returns contents of X1AxisCenters as a double
3410
3411
3412 ThingsToDo=get(handles.WhatToDo,'String');
3413 WhatToDo=ThingsToDo{get(handles.WhatToDo,'value')};
3414
3415 if strcmp(WhatToDo,'ActiveUpdate'),
3416 UpdateType='YAxisDiscreteVals';
3417 UpdateSlider;
3418 end
3419
3420 guidata(hObject,handles);
3421
3422 % --- Executes during object creation, after setting all properties.
3423 function X1AxisCenters_CreateFcn(hObject, eventdata, handles)
3424 % hObject    handle to X1AxisCenters (see GCBO)
3425 % eventdata  reserved - to be defined in a future version of MATLAB
3426 % handles    empty - handles not created until after all CreateFcns called
3427
3428 % Hint: edit controls usually have a white background on Windows.
3429 %       See ISPC and COMPUTER.
3430 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
3431     set(hObject,'BackgroundColor','white');
3432 end
3433
3434
3435 % --- Executes on selection change in YAxisVariable.
3436 function YAxisVariable_Callback(hObject, eventdata, handles)
3437 % hObject    handle to YAxisVariable (see GCBO)
3438 % eventdata  reserved - to be defined in a future version of MATLAB
3439 % handles    structure with handles and user data (see GUIDATA)
3440
3441 % Hints: contents = get(hObject,'String') returns YAxisVariable contents as cell array
3442 %        contents{get(hObject,'Value')} returns selected item from YAxisVariable
3443
3444 ThingsToDo=get(handles.WhatToDo,'String');
3445 WhatToDo=ThingsToDo{get(handles.WhatToDo,'value')};
3446
3447 if strcmp(WhatToDo,'ActiveUpdate'),
3448 UpdateType='YAxisVar';
3449 UpdateSlider;
3450 end
3451
3452 guidata(hObject,handles);
3453
3454 % --- Executes during object creation, after setting all properties.
3455 function YAxisVariable_CreateFcn(hObject, eventdata, handles)
3456 % hObject    handle to YAxisVariable (see GCBO)
3457 % eventdata  reserved - to be defined in a future version of MATLAB
3458 % handles    empty - handles not created until after all CreateFcns called
3459
3460 % Hint: popupmenu controls usually have a white background on Windows.
3461 %       See ISPC and COMPUTER.
3462 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
3463     set(hObject,'BackgroundColor','white');
3464 end
3465
3466
3467
3468
3469 % --- Executes on button press in FTPUpdate.
3470 function FTPUpdate_Callback(hObject, eventdata, handles)
3471 % hObject    handle to FTPUpdate (see GCBO)
3472 % eventdata  reserved - to be defined in a future version of MATLAB
3473 % handles    structure with handles and user data (see GUIDATA)
3474
3475 FTPScript;
3476 NextCommandSetBaseRate=0;
3477 LoadGFXVar=0; UpdateCellOrLoadGFX;
3478 fprintf('%s\n','Selected graphs updated');
3479 guidata(hObject,handles);
3480
3481
3482 % --------------------------------------------------------------------
3483 function ShowObjWin_Callback(hObject, eventdata, handles)
3484 % hObject    handle to ShowObjWin (see GCBO)
3485 % eventdata  reserved - to be defined in a future version of MATLAB
3486 % handles    structure with handles and user data (see GUIDATA)
3487
3488 CurrentAxisHandle=gca;
3489 CurrentAxisNumber=find(CurrentAxisHandle==handles.HandlesList);
3490 CurrentEditWindow=handles.EditWindows(CurrentAxisNumber);
3491
3492 if strcmp(get(CurrentEditWindow,'visible'),'on')
3493     makeInvisible(CurrentEditWindow);
3494 else makeVisible(CurrentEditWindow);
3495 end
3496
3497 guidata(hObject,handles);
3498
3499 % --------------------------------------------------------------------
3500 function AxisObj1_Callback(hObject, eventdata, handles)
3501 % hObject    handle to AxisObj1 (see GCBO)
3502 % eventdata  reserved - to be defined in a future version of MATLAB
3503 % handles    structure with handles and user data (see GUIDATA)
3504
3505 % Hints: get(hObject,'String') returns contents of AxisObj1 as text
3506 %        str2double(get(hObject,'String')) returns contents of AxisObj1 as a double
3507
3508
3509 % --- Executes during object creation, after setting all properties.
3510 function AxisObj1_CreateFcn(hObject, eventdata, handles)
3511 % hObject    handle to AxisObj1 (see GCBO)
3512 % eventdata  reserved - to be defined in a future version of MATLAB
3513 % handles    empty - handles not created until after all CreateFcns called
3514
3515 % Hint: edit controls usually have a white background on Windows.
3516 %       See ISPC and COMPUTER.
3517 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
3518     set(hObject,'BackgroundColor','white');
3519 end
3520
3521
3522
3523 function AxisObj4_Callback(hObject, eventdata, handles)
3524 % hObject    handle to AxisObj4 (see GCBO)
3525 % eventdata  reserved - to be defined in a future version of MATLAB
3526 % handles    structure with handles and user data (see GUIDATA)
3527
3528 % Hints: get(hObject,'String') returns contents of AxisObj4 as text
3529 %        str2double(get(hObject,'String')) returns contents of AxisObj4 as a double
3530
3531
3532 % --- Executes during object creation, after setting all properties.
3533 function AxisObj4_CreateFcn(hObject, eventdata, handles)
3534 % hObject    handle to AxisObj4 (see GCBO)
3535 % eventdata  reserved - to be defined in a future version of MATLAB
3536 % handles    empty - handles not created until after all CreateFcns called
3537
3538 % Hint: edit controls usually have a white background on Windows.
3539 %       See ISPC and COMPUTER.
3540 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
3541     set(hObject,'BackgroundColor','white');
3542 end
3543
3544
3545
3546 function AxisObj9_Callback(hObject, eventdata, handles)
3547 % hObject    handle to AxisObj9 (see GCBO)
3548 % eventdata  reserved - to be defined in a future version of MATLAB
3549 % handles    structure with handles and user data (see GUIDATA)
3550
3551 % Hints: get(hObject,'String') returns contents of AxisObj9 as text
3552 %        str2double(get(hObject,'String')) returns contents of AxisObj9 as a double
3553
3554
3555 % --- Executes during object creation, after setting all properties.
3556 function AxisObj9_CreateFcn(hObject, eventdata, handles)
3557 % hObject    handle to AxisObj9 (see GCBO)
3558 % eventdata  reserved - to be defined in a future version of MATLAB
3559 % handles    empty - handles not created until after all CreateFcns called
3560
3561 % Hint: edit controls usually have a white background on Windows.
3562 %       See ISPC and COMPUTER.
3563 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
3564     set(hObject,'BackgroundColor','white');
3565 end
3566
3567
3568
3569 function AxisObj2_Callback(hObject, eventdata, handles)
3570 % hObject    handle to AxisObj2 (see GCBO)
3571 % eventdata  reserved - to be defined in a future version of MATLAB
3572 % handles    structure with handles and user data (see GUIDATA)
3573
3574 % Hints: get(hObject,'String') returns contents of AxisObj2 as text
3575 %        str2double(get(hObject,'String')) returns contents of AxisObj2 as a double
3576
3577
3578 % --- Executes during object creation, after setting all properties.
3579 function AxisObj2_CreateFcn(hObject, eventdata, handles)
3580 % hObject    handle to AxisObj2 (see GCBO)
3581 % eventdata  reserved - to be defined in a future version of MATLAB
3582 % handles    empty - handles not created until after all CreateFcns called
3583
3584 % Hint: edit controls usually have a white background on Windows.
3585 %       See ISPC and COMPUTER.
3586 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
3587     set(hObject,'BackgroundColor','white');
3588 end
3589
3590
3591
3592 function AxisObj6_Callback(hObject, eventdata, handles)
3593 % hObject    handle to AxisObj6 (see GCBO)
3594 % eventdata  reserved - to be defined in a future version of MATLAB
3595 % handles    structure with handles and user data (see GUIDATA)
3596
3597 % Hints: get(hObject,'String') returns contents of AxisObj6 as text
3598 %        str2double(get(hObject,'String')) returns contents of AxisObj6 as a double
3599
3600
3601 % --- Executes during object creation, after setting all properties.
3602 function AxisObj6_CreateFcn(hObject, eventdata, handles)
3603 % hObject    handle to AxisObj6 (see GCBO)
3604 % eventdata  reserved - to be defined in a future version of MATLAB
3605 % handles    empty - handles not created until after all CreateFcns called
3606
3607 % Hint: edit controls usually have a white background on Windows.
3608 %       See ISPC and COMPUTER.
3609 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
3610     set(hObject,'BackgroundColor','white');
3611 end
3612
3613
3614
3615 function AxisObj10_Callback(hObject, eventdata, handles)
3616 % hObject    handle to AxisObj10 (see GCBO)
3617 % eventdata  reserved - to be defined in a future version of MATLAB
3618 % handles    structure with handles and user data (see GUIDATA)
3619
3620 % Hints: get(hObject,'String') returns contents of AxisObj10 as text
3621 %        str2double(get(hObject,'String')) returns contents of AxisObj10 as a double
3622
3623
3624 % --- Executes during object creation, after setting all properties.
3625 function AxisObj10_CreateFcn(hObject, eventdata, handles)
3626 % hObject    handle to AxisObj10 (see GCBO)
3627 % eventdata  reserved - to be defined in a future version of MATLAB
3628 % handles    empty - handles not created until after all CreateFcns called
3629
3630 % Hint: edit controls usually have a white background on Windows.
3631 %       See ISPC and COMPUTER.
3632 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
3633     set(hObject,'BackgroundColor','white');
3634 end
3635
3636
3637
3638 function AxisObj3_Callback(hObject, eventdata, handles)
3639 % hObject    handle to AxisObj3 (see GCBO)
3640 % eventdata  reserved - to be defined in a future version of MATLAB
3641 % handles    structure with handles and user data (see GUIDATA)
3642
3643 % Hints: get(hObject,'String') returns contents of AxisObj3 as text
3644 %        str2double(get(hObject,'String')) returns contents of AxisObj3 as a double
3645
3646
3647 % --- Executes during object creation, after setting all properties.
3648 function AxisObj3_CreateFcn(hObject, eventdata, handles)
3649 % hObject    handle to AxisObj3 (see GCBO)
3650 % eventdata  reserved - to be defined in a future version of MATLAB
3651 % handles    empty - handles not created until after all CreateFcns called
3652
3653 % Hint: edit controls usually have a white background on Windows.
3654 %       See ISPC and COMPUTER.
3655 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
3656     set(hObject,'BackgroundColor','white');
3657 end
3658
3659
3660
3661 function AxisObj7_Callback(hObject, eventdata, handles)
3662 % hObject    handle to AxisObj7 (see GCBO)
3663 % eventdata  reserved - to be defined in a future version of MATLAB
3664 % handles    structure with handles and user data (see GUIDATA)
3665
3666 % Hints: get(hObject,'String') returns contents of AxisObj7 as text
3667 %        str2double(get(hObject,'String')) returns contents of AxisObj7 as a double
3668
3669
3670 % --- Executes during object creation, after setting all properties.
3671 function AxisObj7_CreateFcn(hObject, eventdata, handles)
3672 % hObject    handle to AxisObj7 (see GCBO)
3673 % eventdata  reserved - to be defined in a future version of MATLAB
3674 % handles    empty - handles not created until after all CreateFcns called
3675
3676 % Hint: edit controls usually have a white background on Windows.
3677 %       See ISPC and COMPUTER.
3678 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
3679     set(hObject,'BackgroundColor','white');
3680 end
3681
3682
3683
3684 function AxisObj11_Callback(hObject, eventdata, handles)
3685 % hObject    handle to AxisObj11 (see GCBO)
3686 % eventdata  reserved - to be defined in a future version of MATLAB
3687 % handles    structure with handles and user data (see GUIDATA)
3688
3689 % Hints: get(hObject,'String') returns contents of AxisObj11 as text
3690 %        str2double(get(hObject,'String')) returns contents of AxisObj11 as a double
3691
3692
3693 % --- Executes during object creation, after setting all properties.
3694 function AxisObj11_CreateFcn(hObject, eventdata, handles)
3695 % hObject    handle to AxisObj11 (see GCBO)
3696 % eventdata  reserved - to be defined in a future version of MATLAB
3697 % handles    empty - handles not created until after all CreateFcns called
3698
3699 % Hint: edit controls usually have a white background on Windows.
3700 %       See ISPC and COMPUTER.
3701 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
3702     set(hObject,'BackgroundColor','white');
3703 end
3704
3705
3706
3707 function edit59_Callback(hObject, eventdata, handles)
3708 % hObject    handle to edit59 (see GCBO)
3709 % eventdata  reserved - to be defined in a future version of MATLAB
3710 % handles    structure with handles and user data (see GUIDATA)
3711
3712 % Hints: get(hObject,'String') returns contents of edit59 as text
3713 %        str2double(get(hObject,'String')) returns contents of edit59 as a double
3714
3715
3716 % --- Executes during object creation, after setting all properties.
3717 function edit59_CreateFcn(hObject, eventdata, handles)
3718 % hObject    handle to edit59 (see GCBO)
3719 % eventdata  reserved - to be defined in a future version of MATLAB
3720 % handles    empty - handles not created until after all CreateFcns called
3721
3722 % Hint: edit controls usually have a white background on Windows.
3723 %       See ISPC and COMPUTER.
3724 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
3725     set(hObject,'BackgroundColor','white');
3726 end
3727
3728
3729
3730 function AxisObj8_Callback(hObject, eventdata, handles)
3731 % hObject    handle to AxisObj8 (see GCBO)
3732 % eventdata  reserved - to be defined in a future version of MATLAB
3733 % handles    structure with handles and user data (see GUIDATA)
3734
3735 % Hints: get(hObject,'String') returns contents of AxisObj8 as text
3736 %        str2double(get(hObject,'String')) returns contents of AxisObj8 as a double
3737
3738
3739 % --- Executes during object creation, after setting all properties.
3740 function AxisObj8_CreateFcn(hObject, eventdata, handles)
3741 % hObject    handle to AxisObj8 (see GCBO)
3742 % eventdata  reserved - to be defined in a future version of MATLAB
3743 % handles    empty - handles not created until after all CreateFcns called
3744
3745 % Hint: edit controls usually have a white background on Windows.
3746 %       See ISPC and COMPUTER.
3747 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
3748     set(hObject,'BackgroundColor','white');
3749 end
3750
3751
3752
3753 function AxisObj12_Callback(hObject, eventdata, handles)
3754 % hObject    handle to AxisObj12 (see GCBO)
3755 % eventdata  reserved - to be defined in a future version of MATLAB
3756 % handles    structure with handles and user data (see GUIDATA)
3757
3758 % Hints: get(hObject,'String') returns contents of AxisObj12 as text
3759 %        str2double(get(hObject,'String')) returns contents of AxisObj12 as a double
3760
3761
3762 % --- Executes during object creation, after setting all properties.
3763 function AxisObj12_CreateFcn(hObject, eventdata, handles)
3764 % hObject    handle to AxisObj12 (see GCBO)
3765 % eventdata  reserved - to be defined in a future version of MATLAB
3766 % handles    empty - handles not created until after all CreateFcns called
3767
3768 % Hint: edit controls usually have a white background on Windows.
3769 %       See ISPC and COMPUTER.
3770 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
3771     set(hObject,'BackgroundColor','white');
3772 end
3773
3774
3775
3776 function AxisObj5_Callback(hObject, eventdata, handles)
3777 % hObject    handle to AxisObj5 (see GCBO)
3778 % eventdata  reserved - to be defined in a future version of MATLAB
3779 % handles    structure with handles and user data (see GUIDATA)
3780
3781 % Hints: get(hObject,'String') returns contents of AxisObj5 as text
3782 %        str2double(get(hObject,'String')) returns contents of AxisObj5 as a double
3783
3784
3785 % --- Executes during object creation, after setting all properties.
3786 function AxisObj5_CreateFcn(hObject, eventdata, handles)
3787 % hObject    handle to AxisObj5 (see GCBO)
3788 % eventdata  reserved - to be defined in a future version of MATLAB
3789 % handles    empty - handles not created until after all CreateFcns called
3790
3791 % Hint: edit controls usually have a white background on Windows.
3792 %       See ISPC and COMPUTER.
3793 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
3794     set(hObject,'BackgroundColor','white');
3795 end
3796
3797
3798 % --------------------------------------------------------------------
3799 function ShowAllObjWin_Callback(hObject, eventdata, handles)
3800 % hObject    handle to ShowAllObjWin (see GCBO)
3801 % eventdata  reserved - to be defined in a future version of MATLAB
3802 % handles    structure with handles and user data (see GUIDATA)
3803
3804 CurrentEditWindows=handles.EditWindows;
3805
3806 if strcmp(get(hObject,'checked'),'off')
3807     set(hObject,'checked','on');
3808     for TemporaryVariable=1:handles.NumberOfAxes
3809     makeVisible(CurrentEditWindows(TemporaryVariable));
3810     end
3811
3812 else set(hObject,'checked','off');
3813     for TemporaryVariable=1:handles.NumberOfAxes
3814     makeInvisible(CurrentEditWindows(TemporaryVariable));
3815     end
3816
3817 end
3818
3819 guidata(hObject,handles);
3820
3821
3822
3823 % --------------------------------------------------------------------
3824 function MakeLinkable_Callback(hObject, eventdata, handles)
3825 % hObject    handle to MakeLinkable (see GCBO)
3826 % eventdata  reserved - to be defined in a future version of MATLAB
3827 % handles    structure with handles and user data (see GUIDATA)
3828
3829
3830 % --------------------------------------------------------------------
3831 function LinkAxis_Callback(hObject, eventdata, handles)
3832 % hObject    handle to LinkAxis (see GCBO)
3833 % eventdata  reserved - to be defined in a future version of MATLAB
3834 % handles    structure with handles and user data (see GUIDATA)
3835
3836 AxesList=handles.HandlesList;
3837 AxisNum=find(gca==AxesList);
3838
3839 eval(['CurrentLinkState=get(handles.AxisLinkText' num2str(AxisNum) ',''visible'');']);
3840
3841 if strcmp(CurrentLinkState,'off')
3842
3843 setappdata(gca,'NumClicks',1);
3844 set(gca,'buttondownfcn','LinkHandle');
3845 hold on;
3846 set(gca,'xgrid','on','ygrid','on');
3847 eval(['makeVisible(handles.AxisLinkText' num2str(AxisNum) ');']);
3848
3849 else
3850
3851     ToDel=getappdata(handles.HandlesList(AxisNum),'CurrentPointPlots');
3852 delete(ToDel);
3853 ToDel=getappdata(handles.HandlesList(AxisNum),'CurrentRect');
3854 delete(ToDel);
3855
3856 UnlinkTheseAxes;
3857
3858 end
3859
3860 % % --------------------------------------------------------------------
3861 % function UnlinkAxis_Callback(hObject, eventdata, handles)
3862 % % hObject    handle to UnlinkAxis (see GCBO)
3863 % % eventdata  reserved - to be defined in a future version of MATLAB
3864 % % handles    structure with handles and user data (see GUIDATA)
3865 %
3866 % AxesList=handles.HandlesList;
3867 % AxisNum=find(gca==AxesList);
3868 %
3869 % ToDel=getappdata(handles.HandlesList(AxisNum),'CurrentPointPlots');
3870 % delete(ToDel);
3871 % ToDel=getappdata(handles.HandlesList(AxisNum),'CurrentRect');
3872 % delete(ToDel);
3873 %
3874 % UnlinkTheseAxes;
3875 %
3876 % % set(gca,'buttondownfcn','');
3877 % % setappdata(gca,'NumClicks',1);
3878 %
3879
3880
3881 % --- Executes on button press in ReverseXY.
3882 function ReverseXY_Callback(hObject, eventdata, handles)
3883 % hObject    handle to ReverseXY (see GCBO)
3884 % eventdata  reserved - to be defined in a future version of MATLAB
3885 % handles    structure with handles and user data (see GUIDATA)
3886
3887 % Hint: get(hObject,'Value') returns toggle state of ReverseXY
3888
3889
3890
3891
3892 % --------------------------------------------------------------------
3893 function Documentation_Callback(hObject, eventdata, handles)
3894 % hObject    handle to Documentation (see GCBO)
3895 % eventdata  reserved - to be defined in a future version of MATLAB
3896 % handles    structure with handles and user data (see GUIDATA)
3897
3898 web('C:/MATLAB/work/XeX/XeXDocumentation/index.html');
3899
3900
3901 % --- Executes during object creation, after setting all properties.
3902 function DelTrials_CreateFcn(hObject, eventdata, handles)
3903 % hObject    handle to DelTrials (see GCBO)
3904 % eventdata  reserved - to be defined in a future version of MATLAB
3905 % handles    empty - handles not created until after all CreateFcns called
3906
3907