Description of mrdr
mrdr
PURPOSE
mrdr: MATLAB REX data reader.
SYNOPSIS
This is a script file.
DESCRIPTION
mrdr: MATLAB REX data reader.
data = mrdr(['-a',] ['-s start_code',] ['-p pre_time',] ['-f max_samp_rate',] '-d filename' [,'-d filename',...])
arguments in square brackets are optional
   -a                  use absolute times, the default is to use make times relative to the start of the trial
   -s start_code       The code used to mark the beginning of a trial, default is 1001
   -p pre_time         The amount of analog pre time used, default is 0
   -f max_samp_rate    The maximum analog sampling rate in Hz, default is 1000
   -d filename         The base file name without the A or E suffix
For arguments that take a value (-s, -p, -f, -d), there must be a space the argument and its value: i.e. -s 1001,
NOT -s1001.
This function reads the A and E files generated by REX
and returns the result in a struct array.
You can contatenate up to 20 Rex files
The events and units will be split into separate struct arrays
Each element of the array represents one trial and includes the following fields:
    trialNumber:    the number of the trial
   tStartTime:     the start time of the trial.
                   if the -a flag is used, this time relative to the beginning of the experiment
                   otherwise this time is 0
   aStartTime:     the start of the analog data in the trial.
                   if the -a flag is used, this time relative to the beginning of the experiment
                   otherwise this time is relative to the trial start time
   aEndTime:       the start of the analog data in the trial.
                   if the -a flag is used, this time relative to the beginning of the experiment
                   otherwise this time is relative to the trial start time
   tEndTime:       the end time of the trial.
                   if the -a flag is used, this time relative to the beginning of the experiment
                   otherwise this time is relative to the trial start time
   a2dRate:        the maximum sampling rate for analog data
    Signals:        a struct array containing the analog signals from the trial
    Events:         a struct array containing the events from the trial
    Units:          a struct array containing the units from the trial
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
doMrdd
FTPLoadFileStuff This script handles file-loadign after FTP
LoadFileCallbackStuff This file handles file loading, from GUI.
TimerFTPLoadFileStuff This is for the ill-fated FTP timer
XeX XEX M-file for XeX.fig
SOURCE CODE
%mrdr: MATLAB REX data reader.
%data = mrdr(['-a',] ['-s start_code',] ['-p pre_time',] ['-f max_samp_rate',] '-d filename' [,'-d filename',...])
%arguments in square brackets are optional
%   -a                  use absolute times, the default is to use make times relative to the start of the trial
%   -s start_code       The code used to mark the beginning of a trial, default is 1001
%   -p pre_time         The amount of analog pre time used, default is 0
%   -f max_samp_rate    The maximum analog sampling rate in Hz, default is 1000
%   -d filename         The base file name without the A or E suffix
%For arguments that take a value (-s, -p, -f, -d), there must be a space the argument and its value: i.e. -s 1001,
%NOT -s1001.
%
%This function reads the A and E files generated by REX
%and returns the result in a struct array.
%You can contatenate up to 20 Rex files
%The events and units will be split into separate struct arrays
%
%Each element of the array represents one trial and includes the following fields:
%
%    trialNumber:    the number of the trial
%   tStartTime:     the start time of the trial.
%                   if the -a flag is used, this time relative to the beginning of the experiment
%                   otherwise this time is 0
%   aStartTime:     the start of the analog data in the trial.
%                   if the -a flag is used, this time relative to the beginning of the experiment
%                   otherwise this time is relative to the trial start time
%   aEndTime:       the start of the analog data in the trial.
%                   if the -a flag is used, this time relative to the beginning of the experiment
%                   otherwise this time is relative to the trial start time
%   tEndTime:       the end time of the trial.
%                   if the -a flag is used, this time relative to the beginning of the experiment
%                   otherwise this time is relative to the trial start time
%   a2dRate:        the maximum sampling rate for analog data
%    Signals:        a struct array containing the analog signals from the trial
%    Events:         a struct array containing the events from the trial
%    Units:          a struct array containing the units from the trial