Description of doMrdd
doMrdd
PURPOSE
SYNOPSIS
function Trials=doMrdd(FileName,NoSave);
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
mrdr mrdr: MATLAB REX data reader.
This function is called by:
SampleSession
saveResults go to the directory of itnerest (cd)
SOURCE CODE
function Trials=doMrdd(FileName,NoSave);
if(FileName(end)=='A'|FileName(end)=='E')
    FileName=FileName(1:(end-1));
end
Trials = mrdr('-s','800','-d',FileName);
if exist('NoSave','var') & NoSave==0
    % DONT SAVE
else
    save(FileName,'Trials');  %SAVE
end