Description of SampleSession
SampleSession
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
MakeAnalysisStruct This makes AnalysisStruct
Preproc function CurrentVariables=Preproc(Trials,SaccadeOptions,ProcType)
RemoveAnalVariables
doAnalysis This is a script so that it can be run in any format anywhere
doMrdd
LineMotion This function analyzes files from the line motion paradigm
detachvars This script detaches all the variables from a structure and assigns them
This function is called by:
SOURCE CODE
Trials=doMrdd('z051125c11lm1',0);
CurrentVariables=Preproc(Trials,'LineMotion');
detachvars
MakeAnalysisStruct
AnalysisStruct.XVector=[50 150];
AnalysisStruct.XAxisVariable='ISI';
AnalysisStruct.XAxisCenters=-400:100:0;
%AnalysisStruct.WhichAnalysis='PSTH';
%AnalysisStruct.WhichAnalysis='SpikeDensity';
doAnalysis
figure
plot(PlotX,PlotY,'b-');
hold on;
errorbar(PlotX,PlotY,2*PlotStd);
who
RemoveAnalVariables;
clear Trials;  % if necessary