Description of CircleRFMap
CircleRFMap
PURPOSE
This script does the Circle RF Map
SYNOPSIS
This is a script file.
DESCRIPTION
    This script does the Circle RF Map
CROSS-REFERENCE INFORMATION
This function calls:
discretizeXes
BaseCorrect This script does baseline correction for RFMap, for instance.
CountSpikes returns total spike counts for each Trial in a matrix
This function is called by:
CircleMap Script to produce an RFMap. Uses ImageRFMap and CircleRFMap to do the hard work
PlotRFMap Script to produce an RFMap. Uses ImageRFMap and CircleRFMap to do the hard work
SOURCE CODE
%    This script does the Circle RF Map
FilterHere=1;
TotalFilter=1&CurrentFilterVector;
% UniqueX=unique(RFx(~isnan(RFx)));
% UniqueY=(unique(RFy(~isnan(RFy))));
discretizeXes;
eval(['UniqueX=unique(' CurrentXAxisVariableStr '(~isnan(' CurrentXAxisVariableStr ')));']);
eval(['UniqueY=unique(' CurrentX1AxisVariableStr '(~isnan(' CurrentX1AxisVariableStr ')));']);
AngleVector=linspace(0,2*pi,100);
HandleNumber=1;
NormFactor=10.^(-1*CurrentSliderValue);
BaseCorrect;
for ind=1:length(UniqueX)
    for ind1=1:length(UniqueY)
        eval(['FindResult=find(' CurrentXAxisVariableStr '==UniqueX(ind) & ' CurrentX1AxisVariableStr '== UniqueY(ind1) &TotalFilter);']);
        eval(['SpikeMat=CountSpikes(Trials,RFTrialIndex(FindResult),' CurrentAlignString '(FindResult),TimeWindowVector,CurrentUnitNumber, CurrentAnalogCorrect);']);
        SpikeCount=nanmean(SpikeMat)*1000/(TimeWindowVector(2)-TimeWindowVector(1));
% if handles.BaselineCorrectVar==1,    SpikeCount=(SpikeCount-BaseRate)/BaseRate;end
        TemporaryHandle(HandleNumber)=plot(UniqueX(ind)+(SpikeCount/NormFactor)*cos(AngleVector),UniqueY(ind1)+(SpikeCount/NormFactor)*sin(AngleVector),'k-');
        HandleNumber=HandleNumber+1; hold on;
end
end
% keyboard;
 set(gca,'box','off','tickdir','out','xlim',[-30 30],'ylim',[-30 30]);
CurrentPlotType='CircleRF';
%putting in the xaxis variable name tag for this axis
CurrentAxisHandle=gca;
CurrentAxisNumber=find(CurrentAxisHandle==handles.HandlesList);
if ~isempty(strfind(CurrentXAxisVariableStr,'Discretized')), XAxisVar=CurrentXAxisVariableStr(12:end);else XAxisVar=CurrentXAxisVariableStr;end
if ~isempty(strfind(CurrentX1AxisVariableStr,'Discretized')), X1AxisVar=CurrentX1AxisVariableStr(12:end);else X1AxisVar=CurrentX1AxisVariableStr;end
handles.AxisVariable(CurrentAxisNumber).XAxis=XAxisVar;
handles.AxisVariable(CurrentAxisNumber).YAxis=X1AxisVar;