
%	This scriptlet assembles the TempGraphix structure for saving

TempGraphix=struct('handle',TemporaryHandle,'dataset',CurrentDataFile,'evalstring',EvalString,'markerstring',LocalMarkerString,'binwidth',CurrentBinWidth,'timevector',...
    CurrentStimVector,'trialfilter',CurrentFilterString,'rf',CurrentRF,'alignstring',CurrentAlignString,'currentvariable',CurrentSelectedVariable,'timewindowvector',...
    TimeWindowVector,'xaxisvariablestr',CurrentXAxisVariableStr,'x1axisvariablestr',CurrentX1AxisVariableStr,'yaxisvariablestr',CurrentYAxisVariableStr,...
'discretizex',CurrentXAxisDiscretize,'discretizex1',CurrentX1AxisDiscretize,'xaxiscenters',CurrentXAxisCentersStr,'x1axiscenters',CurrentX1AxisCentersStr,'unitnumber',CurrentUnitNumber,'slidervalue',CurrentSliderValue,'plottype',CurrentPlotType,'errorbartype',CurrentErrorBarType,'pvalue',CurrentPValue,'displayfilter',CurrentDisplayFilterString);  %last field added april 23 2006

