Description of AnalCountSpikes
AnalCountSpikes
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
discretizeXes
CountSpikes returns total spike counts for each Trial in a matrix
This function is called by:
doAnalysis This is a script so that it can be run in any format anywhere
SOURCE CODE
    FilterHere=1;
TotalFilter=1&CurrentFilterVector;
CurrentSet=find(TotalFilter);
discretizeXes;
SpikeCounts=CountSpikes(Trials,RFTrialIndex(CurrentSet),RFOnTime(CurrentSet),TimeWindowVector,CurrentUnitNumber, CurrentAnalogCorrect); %keyboard;