Description of DoUseProps
DoUseProps
PURPOSE
This function makes the UseProps graphics objects visible or invisible based on handles.UseProps
SYNOPSIS
This is a script file.
DESCRIPTION
    This function makes the UseProps graphics objects visible or invisible based on handles.UseProps
    To be called from within XeX
    DoUseProps SCRIPT
CROSS-REFERENCE INFORMATION
This function calls:
makeInvisible To make objects supplied invisible
makeVisible To make objects supplied visible
This function is called by:
FInterpreter This script does the filter interpretation; will grow
XeX XEX M-file for XeX.fig
SOURCE CODE
%    This function makes the UseProps graphics objects visible or invisible based on handles.UseProps
%    To be called from within XeX
%    DoUseProps SCRIPT
if get(handles.UseProps,'value')==1
%        FullString=['handles.ResetProps,'];
        FullString=[];
    for tempind=1:handles.NumberOfAxes
        FullString=[FullString 'handles.Axis' num2str(tempind) 'Markers, handles.A' num2str(tempind) 'PropertiesTxt,'];
    end
%     FullString(end)=[];
    eval(['makeVisible([' FullString '])']);
else
%        FullString=['handles.ResetProps,'];
            FullString=[];
    for tempind=1:handles.NumberOfAxes
         FullString=[FullString 'handles.Axis' num2str(tempind) 'Markers, handles.A' num2str(tempind) 'PropertiesTxt,'];
    end
%     FullString(end)=[];
    eval(['makeInvisible([' FullString '])']);
end