Description of makeInvisible
makeInvisible
PURPOSE
To make objects supplied invisible
SYNOPSIS
function makeInvisible(handleObjects)
DESCRIPTION
     To make objects supplied invisible
    makeInvisible(handleObjects)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
FilterManagerGUI FILTERMANAGERGUI M-file for FilterManagerGUI.fig
gset sets the gain graph layout
nineset
tempset
DoUseProps This function makes the UseProps graphics objects visible or invisible based on handles.UseProps
UnlinkTheseAxes
XeX XEX M-file for XeX.fig
SOURCE CODE
function makeInvisible(handleObjects)
%     To make objects supplied invisible
%    makeInvisible(handleObjects)
set(handleObjects,'visible','off');
set(handleObjects,'hittest','off');