Description of SwitchAxes
SwitchAxes
PURPOSE
This script switches axes based on axis list in GUI
SYNOPSIS
This is a script file.
DESCRIPTION
    This script switches axes based on axis list in GUI
CROSS-REFERENCE INFORMATION
This function calls:
ClearGObjects This script is used to remove graphix objects properties when clear axes is called
This function is called by:
FInterpreter This script does the filter interpretation; will grow
GraphCommandProcessor Basically does what Plot data does, but reads in commands from a gfx
XeX XEX M-file for XeX.fig
SOURCE CODE
%    This script switches axes based on axis list in GUI
AxesPointer=AxesPointer+1;
if AxesPointer==0 | AxesPointer>length(CurrentAxesVector), AxesPointer=1;end
eval(['axes(handles.axes' num2str(CurrentAxesVector(AxesPointer)) ');']);
CurrentAxis=CurrentAxesVector(AxesPointer);
if AxesPointer>=length(CurrentAxesVector) AxesPointer=0;end
if CurrentHoldStatus ~=1, cla; hold off;
ClearGObjects;
else hold on; end