Description of FTPScript
FTPScript
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
TellMe This function uses tts to speak out the stringvar if speaktovar is set, else fprintfs it to cmd window
FTPLoadFileStuff This script handles file-loadign after FTP
This function is called by:
XeX XEX M-file for XeX.fig
SOURCE CODE
if isfield(handles,'FTP')
FileToFTP=[handles.FTP.pathname handles.FTP.filename];
FTPDir='c:\matlab\work\physiology';
if isfield(handles,'CurrentDataDirectory'), cd(handles.CurrentDataDirectory);end
eval(['!ncftpget -f ' handles.XeXDir '\assorted\pwf ', FTPDir,' ',FileToFTP 'A ' FileToFTP 'E']);
fprintf('%s\n',['IF NCFTP REPORTED NO ERRORS, File downloaded to   ' pwd]);
FTPLoadFileStuff;
else
    TellMe('%s\n','Enter the FTP options first',handles.SpeakToMe);
end