Description of discretizeXes
discretizeXes
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
DiscretizeMe this function takes in a vector and discretizes it, by finding the closest
This function is called by:
AnalCountSpikes
AnalImageMap
AnalImageMapBAKALF Analtuningcurve is trying to do the population analysis in imagemap form
AnalTuningCurve Analtuningcurve does the analysis for the tuning curve
CircleRFMap This script does the Circle RF Map
ImageRFMap This script does the ImageRFMap
SOURCE CODE
if CurrentXAxisDiscretize==1 &&isempty(strfind(CurrentXAxisVariableStr,'Discretized'))
    NewXAxisVariableString=['Discretized' CurrentXAxisVariableStr];
    eval([NewXAxisVariableString '=DiscretizeMe(' CurrentXAxisVariableStr ',' num2str(CurrentXAxisCentersStr) ');']); %these num2strs are silly, i think they are being supplied strings to start with
    CurrentXAxisVariableStr=NewXAxisVariableString;
elseif CurrentXAxisDiscretize==1 && ~isempty(strfind(CurrentXAxisVariableStr,'Discretized'))
    eval([CurrentXAxisVariableStr '=DiscretizeMe(' CurrentXAxisVariableStr(12:end) ',[' num2str(CurrentXAxisCentersStr) ']);']);
    end
if CurrentX1AxisDiscretize==1&&isempty(strfind(CurrentX1AxisVariableStr,'Discretized'))
    NewX1AxisVariableString=['Discretized' CurrentX1AxisVariableStr];
    eval([NewX1AxisVariableString '=DiscretizeMe(' CurrentX1AxisVariableStr ',' num2str(CurrentX1AxisCentersStr) ');']);
    CurrentX1AxisVariableStr=NewX1AxisVariableString;
elseif CurrentX1AxisDiscretize==1 && ~isempty(strfind(CurrentX1AxisVariableStr,'Discretized'))
    eval([CurrentX1AxisVariableStr '=DiscretizeMe(' CurrentX1AxisVariableStr(12:end) ',' num2str(CurrentX1AxisCentersStr) ');']);
    end