Description of MakeTempGraphix
MakeTempGraphix
PURPOSE
This scriptlet assembles the TempGraphix structure for saving
SYNOPSIS
This is a script file.
DESCRIPTION
    This scriptlet assembles the TempGraphix structure for saving
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
SetGObjectProperties This script is used for setting GraphicsObjectProperties. Mainly calls MakeTempGraphix
UpdateCellOrLoadGFX this script does all the hard work for updating a cell or loading
UpdateGObjects this script does the hard work for updateaxis
UpdateSlider this is the major update graphic objects file. poorly called
SOURCE CODE
%    This scriptlet assembles the TempGraphix structure for saving
TempGraphix=struct('handle',TemporaryHandle,'dataset',CurrentDataFile,'evalstring',EvalString,'markerstring',LocalMarkerString,'binwidth',CurrentBinWidth,'timevector',...
    CurrentStimVector,'trialfilter',CurrentFilterString,'rf',CurrentRF,'alignstring',CurrentAlignString,'currentvariable',CurrentSelectedVariable,'timewindowvector',...
    TimeWindowVector,'xaxisvariablestr',CurrentXAxisVariableStr,'x1axisvariablestr',CurrentX1AxisVariableStr,'yaxisvariablestr',CurrentYAxisVariableStr,...
'discretizex',CurrentXAxisDiscretize,'discretizex1',CurrentX1AxisDiscretize,'xaxiscenters',CurrentXAxisCentersStr,'x1axiscenters',CurrentX1AxisCentersStr,'unitnumber',CurrentUnitNumber,'slidervalue',CurrentSliderValue,'plottype',CurrentPlotType,'errorbartype',CurrentErrorBarType,'pvalue',CurrentPValue,'displayfilter',CurrentDisplayFilterString);  %last field added april 23 2006