Description of NextMarkerSet
NextMarkerSet
PURPOSE
This script sets NextMarker and NextMarkerEvalString
SYNOPSIS
This is a script file.
DESCRIPTION
     This script sets NextMarker and NextMarkerEvalString
     Also sets the LocalEvalString, which is then appended in the calling script to the EvalString for future use
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
AngularTuningCurve Script to produce an angular tuning curve. Uses PlotTuningCurve to do the hard work
DiscHist Script to produce an histogram. Uses PlotHist to do the hard work
DrawKDE Script to produce an kernel density estimate. Uses PlotKDE to do the hard work
DrawPSTH Script to produce a PSTH. Uses PlotPSTH to do the hard work
DrawRasters Script to produce a rasterplot. Does the hard work by itself
DrawTuningCurve Script to produce a tuning curve. Uses PlotTuningCurve to do the hard work
ISIH Script to produce an ISI histogram. Uses PlotISI to do the hard work
MakeHist Script to produce an histogram. Uses PlotHist to do the hard work
PlotScatter Script to produce a scatter plot. Uses ScatterPlotter to do the hard work
SpikeDensity Script to produce a spike-density. Uses PlotPSTD to do the hard work
UpdateSlider this is the major update graphic objects file. poorly called
SOURCE CODE
%     This script sets NextMarker and NextMarkerEvalString
%     Also sets the LocalEvalString, which is then appended in the calling script to the EvalString for future use
if CurrentUseProps==1,
NStr=num2str(CurrentAxis);
LocalEvalString=[...
    'NextMarker=Axis' NStr 'Markers((2*Axis' NStr 'MarkerPointer+1):(2*Axis' NStr 'MarkerPointer+2));'...
    'Axis' NStr 'MarkerPointer=Axis' NStr 'MarkerPointer+1;'...
    'if Axis' NStr 'MarkerPointer>(length(Axis' NStr 'Markers)/2 - 1), Axis' NStr 'MarkerPointer=0;end'...
    ];
    eval(LocalEvalString);
else
 NextMarker='';
end
 NextMarkerEvalString=[...
     'set(TemporaryHandle,''color'',NextMarker(1),''linestyle'',NextMarker(2));'...
    ];