Description of setAlignTime
setAlignTime
PURPOSE
This script sets CurrentAlignString to the correct value, based on the AlignCode obtained from the GUI
SYNOPSIS
This is a script file.
DESCRIPTION
    This script sets CurrentAlignString to the correct value, based on the AlignCode obtained from the GUI
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
AngularTuningCurve Script to produce an angular tuning curve. Uses PlotTuningCurve to do the hard work
CircleMap Script to produce an RFMap. Uses ImageRFMap and CircleRFMap to do the hard work
DrawPSTH Script to produce a PSTH. Uses PlotPSTH to do the hard work
DrawRasters Script to produce a rasterplot. Does the hard work by itself
DrawTuningCurve Script to produce a tuning curve. Uses PlotTuningCurve to do the hard work
ISIH Script to produce an ISI histogram. Uses PlotISI to do the hard work
ImageMap Script to produce an RFMap. Uses ImageRFMap and CircleRFMap to do the hard work
PlotRFMap Script to produce an RFMap. Uses ImageRFMap and CircleRFMap to do the hard work
PlotScatter Script to produce a scatter plot. Uses ScatterPlotter to do the hard work
SpikeDensity Script to produce a spike-density. Uses PlotPSTD to do the hard work
SetBaseRate
getCurrentParameters This script collects parameters from the GUI.
UpdateGObjects this script does the hard work for updateaxis
SOURCE CODE
%    This script sets CurrentAlignString to the correct value, based on the AlignCode obtained from the GUI
    AlignCodeList=get(handles.AlignCode,'string');
CurrentAlign=get(handles.AlignCode,'value');
switch(AlignCodeList{CurrentAlign})
    case 'RF1', CurrentAlignString='RFOnTime';
    case 'RF2', CurrentAlignString='RF2OnTime';
    case 'Gap', CurrentAlignString='GapTime';
    case 'RT', CurrentAlignString='ReactionTime';
    case 'FP', CurrentAlignString='FPOnTime';
    case 'SacTime1', CurrentAlignString='SacAlignTime1';
    case 'SacTime2', CurrentAlignString='SacAlignTime2';
    case 'SacTime3', CurrentAlignString='SacAlignTime3';
    case 'UseOld', if exist('SavedAlignString','var'), CurrentAlignString=SavedAlignString; else CurrentAlignString='FPOnTime'; fprintf('%s\n','Cannot use Old Align if it doesnt exist, using FP!!');end
    otherwise, fprintf('%s\n','Not yet programmed align code. May crash');
end