Description of SetBaseRate
SetBaseRate
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
detachvars This script detaches all the variables from a structure and assigns them
evalAlignTime
setAlignTime This script sets CurrentAlignString to the correct value, based on the AlignCode obtained from the GUI
BaseCorrect This script does baseline correction for RFMap, for instance.
This function is called by:
XeX XEX M-file for XeX.fig
SOURCE CODE
detachvars;
eval(['CurrentFilterVector=' CurrentFilterString ';']); %this does the current logical filter vector
setAlignTime;
evalAlignTime;
FilterHere=1;
TotalFilter=1&CurrentFilterVector;
BaseCorrect; %This outputs something called Baserate, which contains the necessary value
handles.BaselineFiringRate=BaseRate;
fprintf('BFR= %6.2f Hz\n',BaseRate);