Description of SetGObjectProperties
SetGObjectProperties
PURPOSE
This script is used for setting GraphicsObjectProperties. Mainly calls MakeTempGraphix
SYNOPSIS
This is a script file.
DESCRIPTION
 This script is used for setting GraphicsObjectProperties. Mainly calls MakeTempGraphix
CROSS-REFERENCE INFORMATION
This function calls:
MakeTempGraphix This scriptlet assembles the TempGraphix structure for saving
This function is called by:
AngularTuningCurve Script to produce an angular tuning curve. Uses PlotTuningCurve to do the hard work
CircleMap Script to produce an RFMap. Uses ImageRFMap and CircleRFMap to do the hard work
DiscHist Script to produce an histogram. Uses PlotHist to do the hard work
DrawKDE Script to produce an kernel density estimate. Uses PlotKDE to do the hard work
DrawPSTH Script to produce a PSTH. Uses PlotPSTH to do the hard work
DrawRasters Script to produce a rasterplot. Does the hard work by itself
DrawTuningCurve Script to produce a tuning curve. Uses PlotTuningCurve to do the hard work
ISIH Script to produce an ISI histogram. Uses PlotISI to do the hard work
ImageMap Script to produce an RFMap. Uses ImageRFMap and CircleRFMap to do the hard work
MakeHist Script to produce an histogram. Uses PlotHist to do the hard work
PlotRFMap Script to produce an RFMap. Uses ImageRFMap and CircleRFMap to do the hard work
PlotScatter Script to produce a scatter plot. Uses ScatterPlotter to do the hard work
SpikeDensity Script to produce a spike-density. Uses PlotPSTD to do the hard work
SOURCE CODE
% This script is used for setting GraphicsObjectProperties. Mainly calls MakeTempGraphix
NStr=num2str(CurrentAxis);
CurrentDisplayFilterString=CurrentFilterString;
MakeTempGraphix;
LocalEvalString=[...
    'if ~isfield(handles,''A' NStr '''), handles.A' NStr '(1)=TempGraphix;'...
    'else handles.A' NStr '(length(handles.A' NStr ')+1)=TempGraphix;end'...
    ];
    eval(LocalEvalString);