Description of KlugeTheTrials
KlugeTheTrials
PURPOSE
Script where kluge fixes for analysis can be implemented.
SYNOPSIS
This is a script file.
DESCRIPTION
   Script where kluge fixes for analysis can be implemented.
   KlugeTheTrials
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
FTPLoadFileStuff This script handles file-loadign after FTP
LoadFileCallbackStuff This file handles file loading, from GUI.
TimerFTPLoadFileStuff This is for the ill-fated FTP timer
SOURCE CODE
%   Script where kluge fixes for analysis can be implemented.
%   KlugeTheTrials
if strcmp(CurrentFile,'z050822c1vm')
    eval(['handles.' CurrentFile '.Trials=handles.' CurrentFile '.Trials(28:end);']);
    fprintf('%s\n',['Kluged    ' CurrentFile '   for vm;']);
end