Description of DiscHist
DiscHist
PURPOSE
Script to produce an histogram. Uses PlotHist to do the hard work
SYNOPSIS
This is a script file.
DESCRIPTION
      Script to produce an histogram. Uses PlotHist to do the hard work
      See also: DrawKDE
      MakeHist
CROSS-REFERENCE INFORMATION
This function calls:
clearvars This function clears all the variables that were recently detached
detachvars This script detaches all the variables from a structure and assigns them
NextMarkerSet This script sets NextMarker and NextMarkerEvalString
SetGObjectProperties This script is used for setting GraphicsObjectProperties. Mainly calls MakeTempGraphix
PlotDiscHist Plots histograms
This function is called by:
SOURCE CODE
%      Script to produce an histogram. Uses PlotHist to do the hard work
%      See also: DrawKDE
%      MakeHist
detachvars;
% SwitchAxes;
eval(['CurrentFilterVector=' CurrentFilterString ';']); %this does the current logical filter vector
CurrentAlignTime=nan;
EvalString='PlotDiscHist;';
NextMarkerSet;
if isempty(NextMarker), NextMarker='k-';end
% EvalString=[EvalString NextMarkerEvalString];  %this makes sure the
% marker is attached. DONT NEED THIS FOR BARPLOT
LocalMarkerString=NextMarker;
eval(EvalString);
CurrentPlotType='DiscHistogram';
SetGObjectProperties;
clearvars;