Description of DrawKDE
DrawKDE
PURPOSE
Script to produce an kernel density estimate. Uses PlotKDE to do the hard work
SYNOPSIS
This is a script file.
DESCRIPTION
      Script to produce an kernel density estimate. Uses PlotKDE to do the hard work
      See also: MakeHist
      DrawKDE;
CROSS-REFERENCE INFORMATION
This function calls:
clearvars This function clears all the variables that were recently detached
detachvars This script detaches all the variables from a structure and assigns them
NextMarkerSet This script sets NextMarker and NextMarkerEvalString
SetGObjectProperties This script is used for setting GraphicsObjectProperties. Mainly calls MakeTempGraphix
PlotKDE Script that plots kernel density estimates
This function is called by:
SOURCE CODE
%      Script to produce an kernel density estimate. Uses PlotKDE to do the hard work
%      See also: MakeHist
%      DrawKDE;
detachvars;
% SwitchAxes;
eval(['CurrentFilterVector=' CurrentFilterString ';']); %this does the current logical filter vector
CurrentAlignTime=nan;
EvalString='PlotKDE;';
NextMarkerSet;
if isempty(NextMarker), NextMarker='k-';end
EvalString=[EvalString NextMarkerEvalString];  %this makes sure the marker is attached
LocalMarkerString=NextMarker;
eval(EvalString);
CurrentPlotType='KDE';
SetGObjectProperties;
clearvars;