Description of DrawTuningCurve
DrawTuningCurve
PURPOSE
Script to produce a tuning curve. Uses PlotTuningCurve to do the hard work
SYNOPSIS
This is a script file.
DESCRIPTION
      Script to produce a tuning curve. Uses PlotTuningCurve to do the hard work
      See also: AngularTuningCurve
      DrawTuningCurve
CROSS-REFERENCE INFORMATION
This function calls:
clearvars This function clears all the variables that were recently detached
detachvars This script detaches all the variables from a structure and assigns them
NextMarkerSet This script sets NextMarker and NextMarkerEvalString
SetGObjectProperties This script is used for setting GraphicsObjectProperties. Mainly calls MakeTempGraphix
evalAlignTime
setAlignTime This script sets CurrentAlignString to the correct value, based on the AlignCode obtained from the GUI
PlotTuningCurve Script to plot tuning curves
This function is called by:
SOURCE CODE
%      Script to produce a tuning curve. Uses PlotTuningCurve to do the hard work
%      See also: AngularTuningCurve
%      DrawTuningCurve
detachvars;
eval(['CurrentFilterVector=' CurrentFilterString ';']); %this does the current logical filter vector
setAlignTime;
evalAlignTime;
% SwitchAxes;
EvalString='IsAngular=0;PlotTuningCurve;';  %This focuses on the Visual On-response.. so basically plot measure over some timewindow as a function of RF time relative to  saccade
NextMarkerSet;
if isempty(NextMarker), NextMarker='k-';end
EvalString=[EvalString NextMarkerEvalString];  %this makes sure the marker is attached
LocalMarkerString=NextMarker;
eval(EvalString);
SetGObjectProperties;
clearvars;