Description of PlotRFMap
PlotRFMap
PURPOSE
Script to produce an RFMap. Uses ImageRFMap and CircleRFMap to do the hard work
SYNOPSIS
This is a script file.
DESCRIPTION
      Script to produce an RFMap. Uses ImageRFMap and CircleRFMap to do the hard work
      Has been superseded by ImageMap and CircleMap. Outdated function
      See also:
      PlotRFMap
CROSS-REFERENCE INFORMATION
This function calls:
clearvars This function clears all the variables that were recently detached
detachvars This script detaches all the variables from a structure and assigns them
SetGObjectProperties This script is used for setting GraphicsObjectProperties. Mainly calls MakeTempGraphix
evalAlignTime
setAlignTime This script sets CurrentAlignString to the correct value, based on the AlignCode obtained from the GUI
CircleRFMap This script does the Circle RF Map
ImageRFMap This script does the ImageRFMap
This function is called by:
SOURCE CODE
%      Script to produce an RFMap. Uses ImageRFMap and CircleRFMap to do the hard work
%      Has been superseded by ImageMap and CircleMap. Outdated function
%      See also:
%      PlotRFMap
detachvars;
eval(['CurrentFilterVector=' CurrentFilterString ';']); %this does the current logical filter vector
setAlignTime;
evalAlignTime;
% SwitchAxes;
EvalString='ImageRFMap;';
eval(EvalString);
LocalMarkerString='';
SetGObjectProperties;
% SwitchAxes;
EvalString='CircleRFMap;';
eval(EvalString);
LocalMarkerString='';
SetGObjectProperties;
clearvars;