Description of BaseCorrect
BaseCorrect
PURPOSE
This script does baseline correction for RFMap, for instance.
SYNOPSIS
This is a script file.
DESCRIPTION
    This script does baseline correction for RFMap,  for instance.
CROSS-REFERENCE INFORMATION
This function calls:
CountSpikes returns total spike counts for each Trial in a matrix
This function is called by:
SetBaseRate
CircleRFMap This script does the Circle RF Map
ImageRFMap This script does the ImageRFMap
SOURCE CODE
%    This script does baseline correction for RFMap,  for instance.
    if length(TotalFilter)==1, TotalFilter=logical(ones(1,length(CurrentAlignTime)));end;
        BaselineWindowVector=handles.BaselineWindow;
        if NextCommandSetBaseRate==1,     BaselineWindowVector=TimeWindowVector; %not using handles.baseline window
        end
        eval(['FindResult=find(TotalFilter);']);
        eval(['SpikeMat=CountSpikes(Trials,RFTrialIndex(FindResult),' CurrentAlignString '(FindResult),BaselineWindowVector,CurrentUnitNumber, CurrentAnalogCorrect);']);
    BaseRate=nanmean(SpikeMat)*1000/(BaselineWindowVector(2)-BaselineWindowVector(1));
    if BaseRate==0, fprintf('%s\n','baseline is zero'); keyboard;end
    if NextCommandSetBaseRate~=1&&~isnan(handles.BaselineFiringRate), BaseRate=handles.BaselineFiringRate;
%    fprintf('%s\n','Using stored baseline rate (!)');
    fprintf('Using stored baseline rate of %6.3f Hz\n',BaseRate);
    end