Description of CountSpikes
CountSpikes
PURPOSE
returns total spike counts for each Trial in a matrix
SYNOPSIS
function [countsmat]=CountSpikes(Trials,indices,alignTimes,xVec,unitCode,AnalogCorrect)
DESCRIPTION
    returns total spike counts for each Trial in a matrix
    [countsmat]=CountSpikes(Trials,indices,alignTimes,xVec,unitCode,AnalogCorrect)
CROSS-REFERENCE INFORMATION
This function calls:
un This function takes in a vector (or a matrix) , and returns unique values (or rows). NaNs (and rows with NaNs) are removed.
This function is called by:
AnalCountSpikes
AnalImageMap
AnalImageMapBAKALF Analtuningcurve is trying to do the population analysis in imagemap form
AnalScatter AnalScatter does the analysis for the scatterplot
AnalTuningCurve Analtuningcurve does the analysis for the tuning curve
doAnalysis This is a script so that it can be run in any format anywhere
BaseCorrect This script does baseline correction for RFMap, for instance.
getLatency This script gets the latency
CircleRFMap This script does the Circle RF Map
ImageRFMap This script does the ImageRFMap
SOURCE CODE
function [countsmat]=CountSpikes(Trials,indices,alignTimes,xVec,unitCode,AnalogCorrect)
%    returns total spike counts for each Trial in a matrix
%    [countsmat]=CountSpikes(Trials,indices,alignTimes,xVec,unitCode,AnalogCorrect)
if ~exist('AnalogCorrect','var') AnalogCorrect=1;end
countsmat=nan*ones(length(indices),1);
xx=1;
for ind=indices
    cur=Trials(ind);
    ee=[cur.Events];
    if ~isempty(ee)
    cc=double([ee.Code]);
    tt=double([ee.Time]);
    end
    spikeTimes=[];
    un=[cur.Units];
    if ~isempty(un)
    temp=find([un.Code]==unitCode);
    if ~isempty(temp)
    spikeTimes=double([un(temp).Times]);
    end
    end
    AnalogStartTime=cur.aStartTime;
    AnalogEndTime=cur.aEndTime;
    if AnalogCorrect==1, spikeTimes=spikeTimes(spikeTimes<=AnalogEndTime & spikeTimes>=AnalogStartTime);end
    if ~isempty(spikeTimes) && ~isnan(alignTimes(xx))  %just changed these from ind to xx
    countsmat(xx)=length(find(spikeTimes-alignTimes(xx) >=xVec(1) & spikeTimes-alignTimes(xx) <=xVec(2)));
    end
    xx=xx+1;
end