Description of ArrayFiddleCodeBit
ArrayFiddleCodeBit
PURPOSE
A little scriplet that does
SYNOPSIS
This is a script file.
DESCRIPTION
A little scriplet that does
a little fiddling to take care of occasions where rex doenst drop an arrya code. details.
 Verify this IMP
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
MGS This function analyzes files from the MGS paradigm
OneJump This function analyzes trials from the Jump paradigms
OneJump1215 This function analyzes trials from the Jump paradigms
PostSac This function analyzes trials from the old jumping eye-position task
SOURCE CODE
   %A little scriplet that does
   %a little fiddling to take care of occasions where rex doenst drop an arrya code. details.
    % Verify this IMP
    TemporaryArrayNumber=find(CurrentCodes>=2000&CurrentCodes<=2060);
    if ~isempty(TemporaryArrayNumber)
        if length(TemporaryArrayNumber)==1 ArrayNumber(TrialIndex)=CurrentCodes(TemporaryArrayNumber)-2000; ArrayBak=[];
        elseif length(TemporaryArrayNumber)==2 ArrayNumber(TrialIndex)=CurrentCodes(TemporaryArrayNumber(1))-2000; ArrayBak=CurrentCodes(TemporaryArrayNumber(2))-2000;
        else ArrayNumber(TrialIndex)=-1; ArrayBak=[];
        end
    elseif ~isempty(ArrayBak) ArrayNumber(TrialIndex)=ArrayBak; ArrayBak=[];
    end