Description of attachvars
attachvars
PURPOSE
This script evaluates what variables are present in the calling
SYNOPSIS
This is a script file.
DESCRIPTION
This script evaluates what variables are present in the calling
workspace and assigns them to a structure variable called
Current_Variables. Anything called Trials is excluded from the attachment.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
LineMotion This function analyzes files from the line motion paradigm
MGS This function analyzes files from the MGS paradigm
OneJump This function analyzes trials from the Jump paradigms
OneJump1215 This function analyzes trials from the Jump paradigms
PostSac This function analyzes trials from the old jumping eye-position task
QuickAnalysis This function analyzes trials for a quick analysis
RFMap This function analyzes trials from the RF map paradigm
TAnalysis This function analyzes data from the 2-T paradigm
TDistractor This function analyzes files from the line motion paradigm
VSearch This function analyzes data from the search paradigm
ParamEval This function works in PlotData and in Graphcommandprocessor and serves to
SOURCE CODE
%This script evaluates what variables are present in the calling
%workspace and assigns them to a structure variable called
%Current_Variables. Anything called Trials is excluded from the attachment.
CurrentVariableList=who;
WhereisTrials=strcmp(CurrentVariableList,'Trials');
CurrentVariableList=CurrentVariableList(~WhereisTrials); %removing Trials from the structure
for VariableListIndex=1:length(CurrentVariableList)
            eval(['CurrentVariables.',CurrentVariableList{VariableListIndex},'=',CurrentVariableList{VariableListIndex},';']);
end
clear CurrentVariableList WhereisTrials VariableListIndex;  %bookkeeping to prevent variable proliferation as this is a script