Description of clearvars
clearvars
PURPOSE
This function clears all the variables that were recently detached
SYNOPSIS
This is a script file.
DESCRIPTION
This function clears all the variables that were recently detached
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
AngularTuningCurve Script to produce an angular tuning curve. Uses PlotTuningCurve to do the hard work
CircleMap Script to produce an RFMap. Uses ImageRFMap and CircleRFMap to do the hard work
DiscHist Script to produce an histogram. Uses PlotHist to do the hard work
DrawKDE Script to produce an kernel density estimate. Uses PlotKDE to do the hard work
DrawPSTH Script to produce a PSTH. Uses PlotPSTH to do the hard work
DrawRasters Script to produce a rasterplot. Does the hard work by itself
DrawTuningCurve Script to produce a tuning curve. Uses PlotTuningCurve to do the hard work
ISIH Script to produce an ISI histogram. Uses PlotISI to do the hard work
ImageMap Script to produce an RFMap. Uses ImageRFMap and CircleRFMap to do the hard work
MakeHist Script to produce an histogram. Uses PlotHist to do the hard work
PlotRFMap Script to produce an RFMap. Uses ImageRFMap and CircleRFMap to do the hard work
PlotScatter Script to produce a scatter plot. Uses ScatterPlotter to do the hard work
SpikeDensity Script to produce a spike-density. Uses PlotPSTD to do the hard work
UpdateCellOrLoadGFX this script does all the hard work for updating a cell or loading
UpdateGObjects this script does the hard work for updateaxis
UpdateSlider this is the major update graphic objects file. poorly called
XeX XEX M-file for XeX.fig
SOURCE CODE
%This function clears all the variables that were recently detached
StructVariableNames=fieldnames(CurrentVariables);
for ListIndex=1:length(StructVariableNames)
    CurrentVariableName=StructVariableNames{ListIndex};
    clear(CurrentVariableName);
end
clear StructVariableNames ListIndex CurrentVariableName;