Description of detachvars
detachvars
PURPOSE
This script detaches all the variables from a structure and assigns them
SYNOPSIS
This is a script file.
DESCRIPTION
This script detaches all the variables from a structure and assigns them
to variables in the workspace. If those variables already existed, they
will be overwritten, but a warning message will appear.
detachvars
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
AngularTuningCurve Script to produce an angular tuning curve. Uses PlotTuningCurve to do the hard work
CircleMap Script to produce an RFMap. Uses ImageRFMap and CircleRFMap to do the hard work
DiscHist Script to produce an histogram. Uses PlotHist to do the hard work
DrawKDE Script to produce an kernel density estimate. Uses PlotKDE to do the hard work
DrawPSTH Script to produce a PSTH. Uses PlotPSTH to do the hard work
DrawRasters Script to produce a rasterplot. Does the hard work by itself
DrawTuningCurve Script to produce a tuning curve. Uses PlotTuningCurve to do the hard work
ISIH Script to produce an ISI histogram. Uses PlotISI to do the hard work
ImageMap Script to produce an RFMap. Uses ImageRFMap and CircleRFMap to do the hard work
MakeHist Script to produce an histogram. Uses PlotHist to do the hard work
PlotRFMap Script to produce an RFMap. Uses ImageRFMap and CircleRFMap to do the hard work
PlotScatter Script to produce a scatter plot. Uses ScatterPlotter to do the hard work
SpikeDensity Script to produce a spike-density. Uses PlotPSTD to do the hard work
FullSession suggested analysis script
SampleSession
ParamEval This function works in PlotData and in Graphcommandprocessor and serves to
SetBaseRate
UpdateCellOrLoadGFX this script does all the hard work for updating a cell or loading
UpdateGObjects this script does the hard work for updateaxis
UpdateSlider this is the major update graphic objects file. poorly called
XeX XEX M-file for XeX.fig
SOURCE CODE
%This script detaches all the variables from a structure and assigns them
%to variables in the workspace. If those variables already existed, they
%will be overwritten, but a warning message will appear.
%detachvars
StructVariableNames=fieldnames(CurrentVariables);
AmOverwriting=0;
for ListIndex=1:length(StructVariableNames)
    CurrentVariableName=StructVariableNames{ListIndex};
    if exist(CurrentVariableName,'var') AmOverwriting=AmOverwriting+1;end
    eval([CurrentVariableName '=CurrentVariables.' CurrentVariableName ';']);
end
% if AmOverwriting>0, fprintf('%s\n',['*************Overwrote ',num2str(AmOverwriting),' Variables****************']);end
clear AmOverwriting StructVariableNames CurrentVariableName ListIndex  %bookkeeping to prevent variable proliferation as this is a script