Description of MakeSacStruct
MakeSacStruct
PURPOSE
function SacStruct=MakeSacStruct(WhichType)
SYNOPSIS
function SacStruct=MakeSacStruct(WhichType)
DESCRIPTION
function SacStruct=MakeSacStruct(WhichType)
WhichType=1 gives you the normal version
WhichType=2 gives you the fuller version
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
MGS This function analyzes files from the MGS paradigm
OneJump This function analyzes trials from the Jump paradigms
OneJump1215 This function analyzes trials from the Jump paradigms
PostSac This function analyzes trials from the old jumping eye-position task
CreateTempSac This scriptlet is used in OneJump, for instance.
SacFind The main XeX saccade parser
SOURCE CODE
function SacStruct=MakeSacStruct(WhichType)
%function SacStruct=MakeSacStruct(WhichType)
%WhichType=1 gives you the normal version
%WhichType=2 gives you the fuller version
if ~exist('WhichType','var')|WhichType==1
%     SacStruct=struct('latency',NaN,'duration',NaN,'peakvelocity',NaN ,'amplitude',NaN,'velocitrace',NaN,'startx',NaN,'starty',NaN,'endx',NaN,'endy',NaN,'rfdistance',NaN,'gaplatency',NaN,'whichsac',NaN,'angle',NaN);
    SacStruct=struct('latency',NaN,'duration',NaN,'peakvelocity',NaN ,'amplitude',NaN,'velocitrace',NaN,'startx',NaN,'starty',NaN,'endx',NaN,'endy',NaN,'eyex',NaN,'eyey',NaN,'curvature',NaN);
else
    SacStruct=struct('latency',NaN,'duration',NaN,'peakvelocity',NaN ,'amplitude',NaN,'velocitrace',NaN,'startx',NaN,'starty',NaN,'endx',NaN,'endy',NaN,'eyex',NaN,'eyey',NaN,'curvature',NaN,'rfdistance',NaN,'rf2distance',NaN,'gaplatency',NaN,'whichsac',NaN,'angle',NaN);
end