Description of ParamEval
ParamEval
PURPOSE
This function works in PlotData and in Graphcommandprocessor and serves to
SYNOPSIS
function CurrentVariables=ParamEval(XexParameters,CurrentVariables)
DESCRIPTION
This function works in PlotData and in Graphcommandprocessor and serves to
include variables that come out of RUN into the CurrentVariables structure
ParamEval.m
CROSS-REFERENCE INFORMATION
This function calls:
attachvars This script evaluates what variables are present in the calling
detachvars This script detaches all the variables from a structure and assigns them
This function is called by:
GraphCommandProcessor Basically does what Plot data does, but reads in commands from a gfx
XeX XEX M-file for XeX.fig
SOURCE CODE
function CurrentVariables=ParamEval(XexParameters,CurrentVariables)
%This function works in PlotData and in Graphcommandprocessor and serves to
%include variables that come out of RUN into the CurrentVariables structure
%ParamEval.m
detachvars;
eval(XexParameters);
clear CurrentVariables;
attachvars;