Description of TellMe
TellMe
PURPOSE
This function uses tts to speak out the stringvar if speaktovar is set, else fprintfs it to cmd window
SYNOPSIS
function TellMe(formatvar,stringvar,speakvar)
DESCRIPTION
    This function uses tts to speak out the stringvar if speaktovar is set, else fprintfs it to cmd window
    TellMe(formatvar,stringvar,speakvar)
CROSS-REFERENCE INFORMATION
This function calls:
tts tts Text To Speech function, version 1.0
This function is called by:
XeXUtters Legacy function (too slow) to speak out instead of printing to screen, if SpeakToMe is set
GraphCommandProcessor Basically does what Plot data does, but reads in commands from a gfx
FTPScript
PlotPSTD Script that plots spike-densities
PlotPSTH This function plots the PSTH, after calling AnalPSTH for analysis
UpdateCellOrLoadGFX this script does all the hard work for updating a cell or loading
XeX XEX M-file for XeX.fig
SOURCE CODE
function TellMe(formatvar,stringvar,speakvar)
%    This function uses tts to speak out the stringvar if speaktovar is set, else fprintfs it to cmd window
%    TellMe(formatvar,stringvar,speakvar)
if speakvar==1
    tts(stringvar);
else
    fprintf(formatvar,stringvar);
end