Description of un
un
PURPOSE
This function takes in a vector (or a matrix) , and returns unique values (or rows). NaNs (and rows with NaNs) are removed.
SYNOPSIS
function X1=un(X)
DESCRIPTION
    This function takes in a vector (or a matrix) , and returns unique values (or rows). NaNs (and rows with NaNs) are removed.
     Currently has a major bug; if supplied a matrix with one row, it
     screws up and treats it as a vector. Fix at some point; other
     functions may crash as a result...aaargh.
    X1=un(X)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
LineMotion This function analyzes files from the line motion paradigm
MGS This function analyzes files from the MGS paradigm
OneJump This function analyzes trials from the Jump paradigms
OneJump1215 This function analyzes trials from the Jump paradigms
TAnalysis This function analyzes data from the 2-T paradigm
TDistractor This function analyzes files from the line motion paradigm
VSearch This function analyzes data from the search paradigm
MarkerAnalyze
BinSpikes returns binned spike counts for each Trial in a matrix.
CountSpikes returns total spike counts for each Trial in a matrix
ISISpikes function used in isi calculation, modeled after binspikes
PlotDiscHist Plots histograms
XeX XEX M-file for XeX.fig
SOURCE CODE
function X1=un(X)
%    This function takes in a vector (or a matrix) , and returns unique values (or rows). NaNs (and rows with NaNs) are removed.
%     Currently has a major bug; if supplied a matrix with one row, it
%     screws up and treats it as a vector. Fix at some point; other
%     functions may crash as a result...aaargh.
%    X1=un(X)
% if column vector, make row vector
if size(X,1)>1&size(X,2)==1, X=X';end
% effectively returns unique(x(~isnan(x)))
if size(X,1)==1
X1=unique(X(~isnan(X)));
elseif size(X,1)>1
        nanrow=nan*ones(1,size(X,1));
        for ind=1:size(X,2)
            nanrow(isnan(X(:,ind)))=1;
        end
        X1=unique(X(nanrow~=1,:),'rows');
end