
% This makes AnalysisStruct
% See also: DoAnalysis

AnalysisStruct=struct('WhichAnalysis','TuningCurve','FilterString','GoodTrial==1&PhotoBad~=1','AlignString','RFOnTime','AnalogCorrect',1,...
    'UnitNumber',613,'RF',[100 100],'BinWidth',20,'SliderValue',0.5,'XVector',[-400 400],...
    'WhichVariable','ReactionTime','ErrorBarType','Regular','XAxisVariable','RFx','X1AxisVariable','RFy','YAxisVariable','SpikeRate',...
    'XAxisCenters',NaN,'X1AxisCenters',NaN,'PValue',0.05);
