
function XeXUtters(DarkVar,SpeakToMe)

%	Legacy function (too slow) to speak out instead of printing to screen, if SpeakToMe is set
%	DarkVar toggles depressed or manic status of XeX Utters
%	XeXUtters(DarkVar,SpeakToMe)

BrightUtterances={...
  'Hey, you are looking REALLY GOOD'...
  'Nature. N A T U R E.       Publish !!'...
  'You Got It !! Significance.' ...
  'Ooh La La !!' ...
  'Oh My, That looks so wonderful'...
  'How do you do it ?? You must be a Genius !!'...
  'That is some data !!! WOW !!'...
  'Is that your data ?? WOW !!!' ...
  'Oh my God !! You are so cool !'...
  };


DarkUtterances={...
  'I knew you were stupid, but this is TOO much !!'...
  'You idiot !'...
  'Stop fooling around and get to work !'...
  'Do they pay you for this ? REally ??'...
  'Did you even think about what you just did ?'...
  'How do you sleep ??'.....
  'Is this slow enough for you ??? M !! O !! R  !! O !! N !!'...
  'Sigh ! There you go again ... '...
  'How many times do I have to explain this to you ?'...
  'Are you retarded or what ?? '...
  'Did you get dropped a lot when you were a baby ?'...
  'Stop smoking that stuff !! Not in the lab, for heaven''s sake'...
  };


if ~exist('SpeakToMe','var') || isempty(SpeakToMe), SpeakToMe=1;end
if ~exist('DarkVar','var')
    randomDark=rand;
    if randomDark>=.5,
    TellMe('%s\n',BrightUtterances{ceil(rand*length(BrightUtterances))},1);
    else
    TellMe('%s\n',DarkUtterances{ceil(rand*length(DarkUtterances))},1);
    end

elseif DarkVar==1,
    
    TellMe('%s\n',DarkUtterances{ceil(rand*length(DarkUtterances))},SpeakToMe);

else    TellMe('%s\n',BrightUtterances{ceil(rand*length(BrightUtterances))},SpeakToMe);
 
end